---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      github-actions:
        patterns:
          - "*"
      github-actions-security:
        applies-to: "security-updates"
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "python"
    groups:
      python-dependencies:
        patterns:
          - "*"
      python-security:
        applies-to: "security-updates"
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/serve/cockpit/web"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "javascript"
    groups:
      npm-dependencies:
        patterns:
          - "*"
      npm-security:
        applies-to: "security-updates"
        patterns:
          - "*"
