"""Failing tests for task #470: Add start_work compound tool to mcp-kanban server.

Covers all AC items from #470:
  - start_work(task_id, claim?) tool exists in server.py and is importable
  - When no claim provided, auto-generates via kanban-md agent-name subprocess
  - Claim the task at its current status (no status change via --status flag)
  - Returns JSON: full task details from show --json + injected claim_name field
  - Explicit claim: agent-name NOT called, provided claim used directly
  - Already-claimed error: edit rc!=0 → error string returned, show NOT called
  - agent-name failure → error string returned, edit NOT called
  - show failure → error string returned

All tests FAIL in RED phase — start_work does not exist yet in server.py.
"""

from __future__ import annotations

import inspect
import json
from pathlib import Path
from typing import Any
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

# start_work does not exist yet — import guard prevents collection failure so
# the existence tests fail as AssertionError rather than a collection error.
try:
    from owlbear_mcp_kanban.server import start_work as _start_work
except ImportError:
    _start_work = None  # type: ignore[assignment]

from owlbear_mcp_kanban.server import AppContext


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_SAMPLE_TASK: dict[str, Any] = {
    "id": 470,
    "title": "Add start_work compound tool",
    "status": "todo",
    "priority": "needed",
    "tags": ["scope:mcp"],
    "body": "## AC\n- do stuff",
    "file": "/kanban/tasks/470-start-work.md",
    "claimed_by": "",
    "blocked": False,
    "block_reason": "",
    "class": "standard",
    "created": "2026-01-01T00:00:00Z",
    "updated": "2026-01-02T00:00:00Z",
    "depends_on": "",
}

_GENERATED_CLAIM_NAME = "cedar-cloud"


def _make_app_ctx() -> AppContext:
    return AppContext(kanban_bin=Path("/fake/kanban-md"), kanban_dir=Path("/fake/kanban"))


def _make_mcp_ctx(app_ctx: AppContext | None = None) -> MagicMock:
    ctx = MagicMock()
    ctx.request_context.lifespan_context = app_ctx or _make_app_ctx()
    return ctx


def _patch_run_seq(*responses: tuple[str, str, int]) -> Any:
    """Patch _run_kanban with a sequence of (stdout, stderr, rc) responses."""
    return patch(
        "owlbear_mcp_kanban.server._run_kanban",
        new=AsyncMock(side_effect=list(responses)),
    )


# ---------------------------------------------------------------------------
# TestFromAC_StartWorkExists — tool presence and signature contract
# ---------------------------------------------------------------------------


class TestFromAC_StartWorkExists:
    """start_work must exist, be importable from server, and have the right signature."""

    # AC: New start_work(task_id, claim?) tool in server.py
    def test_start_work_importable_from_server(self) -> None:
        """start_work must be importable from owlbear_mcp_kanban.server."""
        assert _start_work is not None, (
            "start_work is not importable from owlbear_mcp_kanban.server; "
            "builder must implement and export start_work in server.py"
        )

    def test_start_work_is_callable(self) -> None:
        """start_work must be callable (async function or MCP tool wrapper)."""
        assert _start_work is not None, "start_work not importable"
        assert callable(_start_work), "start_work must be callable"

    def test_has_task_id_parameter(self) -> None:
        """start_work must accept task_id as a required parameter."""
        assert _start_work is not None, "start_work not importable"
        sig = inspect.signature(_start_work)
        assert "task_id" in sig.parameters, "start_work must accept task_id parameter"

    def test_claim_parameter_is_optional(self) -> None:
        """start_work must accept optional claim parameter defaulting to '' or None."""
        assert _start_work is not None, "start_work not importable"
        sig = inspect.signature(_start_work)
        assert "claim" in sig.parameters, "start_work must have an optional claim parameter"
        param = sig.parameters["claim"]
        assert param.default in ("", None), f"claim default must be '' or None (optional), got: {param.default!r}"


# ---------------------------------------------------------------------------
# TestFromAC_StartWorkAutoGeneratedClaim — auto-generated claim contract
# ---------------------------------------------------------------------------


class TestFromAC_StartWorkAutoGeneratedClaim:
    """When no claim is provided, start_work auto-generates one via kanban-md agent-name."""

    # AC: If no claim provided, generate one via kanban-md agent-name subprocess call
    @pytest.mark.asyncio
    async def test_calls_agent_name_when_no_claim_provided(self) -> None:
        """start_work must invoke kanban-md agent-name when no claim argument is given."""
        assert _start_work is not None, "start_work not importable"
        mcp_ctx = _make_mcp_ctx()
        with _patch_run_seq(
            (_GENERATED_CLAIM_NAME + "\n", "", 0),  # agent-name
            ("Updated task.", "", 0),  # edit --claim
            (json.dumps(_SAMPLE_TASK), "", 0),  # show --json
        ) as mock_run:
            await _start_work(mcp_ctx, task_id="470")

        all_args = [ca[0] for ca in mock_run.call_args_list]
        assert any("agent-name" in args for args in all_args), (
            "start_work must call kanban-md agent-name to generate a claim name when no explicit claim is provided"
        )

    @pytest.mark.asyncio
    async def test_generated_claim_name_used_in_edit_call(self) -> None:
        """The name returned by agent-name must be passed as --claim to kanban-md edit."""
        assert _start_work is not None, "start_work not importable"
        mcp_ctx = _make_mcp_ctx()
        with _patch_run_seq(
            (_GENERATED_CLAIM_NAME + "\n", "", 0),
            ("Updated task.", "", 0),
            (json.dumps(_SAMPLE_TASK), "", 0),
        ) as mock_run:
            await _start_work(mcp_ctx, task_id="470")

        all_args = [ca[0] for ca in mock_run.call_args_list]
        edit_calls = [args for args in all_args if "edit" in args]
        assert edit_calls, "start_work must call kanban-md edit"
        edit_args = edit_calls[0]
        assert "--claim" in edit_args, "edit call must include --claim flag"
        claim_idx = list(edit_args).index("--claim")
        assert edit_args[claim_idx + 1] == _GENERATED_CLAIM_NAME, (
            f"edit --claim must use the generated name '{_GENERATED_CLAIM_NAME}' "
            f"(stripped of whitespace), got: {edit_args[claim_idx + 1]!r}"
        )

    # AC: claim_name field with the name used
    @pytest.mark.asyncio
    async def test_generated_claim_name_present_in_json_response(self) -> None:
        """claim_name in the response must match the name returned by agent-name."""
        assert _start_work is not None, "start_work not importable"
        mcp_ctx = _make_mcp_ctx()
        with _patch_run_seq(
            (_GENERATED_CLAIM_NAME + "\n", "", 0),
            ("Updated task.", "", 0),
            (json.dumps(_SAMPLE_TASK), "", 0),
        ):
            result = await _start_work(mcp_ctx, task_id="470")

        data = json.loads(result)
        assert data.get("claim_name") == _GENERATED_CLAIM_NAME, (
            f"claim_name must be '{_GENERATED_CLAIM_NAME}' (stripped), got: {data.get('claim_name')!r}"
        )

    @pytest.mark.asyncio
    async def test_generated_claim_name_stripped_of_whitespace(self) -> None:
        """Whitespace/newlines in agent-name output must be stripped before use."""
        assert _start_work is not None, "start_work not importable"
        mcp_ctx = _make_mcp_ctx()
        dirty_name = "  solar-swift  \n"
        with _patch_run_seq(
            (dirty_name, "", 0),
            ("Updated task.", "", 0),
            (json.dumps(_SAMPLE_TASK), "", 0),
        ):
            result = await _start_work(mcp_ctx, task_id="470")

        data = json.loads(result)
        assert data.get("claim_name") == "solar-swift", (
            f"claim_name must be stripped of surrounding whitespace/newlines, got: {data.get('claim_name')!r}"
        )


# ---------------------------------------------------------------------------
# TestFromAC_StartWorkExplicitClaim — explicit claim contract
# ---------------------------------------------------------------------------


class TestFromAC_StartWorkExplicitClaim:
    """When an explicit claim is provided, agent-name is skipped and that name is used."""

    @pytest.mark.asyncio
    async def test_agent_name_not_called_when_claim_provided(self) -> None:
        """start_work must NOT call agent-name when an explicit claim is given."""
        assert _start_work is not None, "start_work not importable"
        mcp_ctx = _make_mcp_ctx()
        with _patch_run_seq(
            ("Updated task.", "", 0),  # edit --claim (no agent-name step)
            (json.dumps(_SAMPLE_TASK), "", 0),  # show --json
        ) as mock_run:
            await _start_work(mcp_ctx, task_id="470", claim="my-agent")

        all_args = [ca[0] for ca in mock_run.call_args_list]
        assert not any("agent-name" in args for args in all_args), (
            "start_work must NOT call agent-name when an explicit claim is provided"
        )

    @pytest.mark.asyncio
    async def test_explicit_claim_used_in_edit_call(self) -> None:
        """The provided claim name must appear as the --claim value in edit call."""
        assert _start_work is not None, "start_work not importable"
        mcp_ctx = _make_mcp_ctx()
        with _patch_run_seq(
            ("Updated task.", "", 0),
            (json.dumps(_SAMPLE_TASK), "", 0),
        ) as mock_run:
            await _start_work(mcp_ctx, task_id="470", claim="my-agent")

        all_args = [ca[0] for ca in mock_run.call_args_list]
        edit_calls = [args for args in all_args if "edit" in args]
        assert edit_calls, "start_work must call kanban-md edit"
        edit_args = edit_calls[0]
        assert "--claim" in edit_args, "edit call must include --claim flag"
        assert "my-agent" in edit_args, "edit call must pass 'my-agent' as the --claim value"

    @pytest.mark.asyncio
    async def test_explicit_claim_name_in_json_response(self) -> None:
        """claim_name in the response must equal the explicitly provided claim."""
        assert _start_work is not None, "start_work not importable"
        mcp_ctx = _make_mcp_ctx()
        with _patch_run_seq(
            ("Updated task.", "", 0),
            (json.dumps(_SAMPLE_TASK), "", 0),
        ):
            result = await _start_work(mcp_ctx, task_id="470", claim="my-agent")

        data = json.loads(result)
        assert data.get("claim_name") == "my-agent", (
            f"claim_name must be 'my-agent' when explicit claim was provided, got: {data.get('claim_name')!r}"
        )


# ---------------------------------------------------------------------------
# TestFromAC_StartWorkJsonResponse — JSON response structure contract
# ---------------------------------------------------------------------------


class TestFromAC_StartWorkJsonResponse:
    """start_work must return valid JSON merging show_task output with claim_name."""

    # AC: Return JSON: task details (full, like show_task) + claim_name field
    @pytest.mark.asyncio
    async def test_response_is_valid_json(self) -> None:
        """start_work must return a valid JSON string (not plain text, not error)."""
        assert _start_work is not None, "start_work not importable"
        mcp_ctx = _make_mcp_ctx()
        with _patch_run_seq(
            ("Updated task.", "", 0),
            (json.dumps(_SAMPLE_TASK), "", 0),
        ):
            result = await _start_work(mcp_ctx, task_id="470", claim="agent-x")

        try:
            data = json.loads(result)
        except json.JSONDecodeError as exc:
            pytest.fail(f"start_work returned non-JSON: {exc!r}; got: {result!r}")
        assert isinstance(data, dict), "JSON response must be an object (dict), not array"

    @pytest.mark.asyncio
    async def test_response_includes_core_task_fields_from_show(self) -> None:
        """Response must include core task fields from show --json output."""
        assert _start_work is not None, "start_work not importable"
        mcp_ctx = _make_mcp_ctx()
        with _patch_run_seq(
            ("Updated task.", "", 0),
            (json.dumps(_SAMPLE_TASK), "", 0),
        ):
            result = await _start_work(mcp_ctx, task_id="470", claim="agent-x")

        data = json.loads(result)
        required = {"id", "title", "status", "priority"}
        missing = required - data.keys()
        assert not missing, (
            f"start_work response missing task fields: {missing}. Response must include all show_task fields."
        )

    @pytest.mark.asyncio
    async def test_response_includes_claim_name_field(self) -> None:
        """Response must include claim_name — a field not present in show --json."""
        assert _start_work is not None, "start_work not importable"
        mcp_ctx = _make_mcp_ctx()
        with _patch_run_seq(
            ("Updated task.", "", 0),
            (json.dumps(_SAMPLE_TASK), "", 0),
        ):
            result = await _start_work(mcp_ctx, task_id="470", claim="agent-x")

        data = json.loads(result)
        assert "claim_name" in data, (
            "start_work response must include claim_name field "
            "(builder must inject it — it is absent from show --json output)"
        )

    @pytest.mark.asyncio
    async def test_show_called_with_json_flag(self) -> None:
        """start_work must call kanban-md show with --json flag to get structured data."""
        assert _start_work is not None, "start_work not importable"
        mcp_ctx = _make_mcp_ctx()
        with _patch_run_seq(
            ("Updated task.", "", 0),
            (json.dumps(_SAMPLE_TASK), "", 0),
        ) as mock_run:
            await _start_work(mcp_ctx, task_id="470", claim="agent-x")

        all_args = [ca[0] for ca in mock_run.call_args_list]
        show_calls = [args for args in all_args if "show" in args]
        assert show_calls, "start_work must call kanban-md show"
        assert "--json" in show_calls[0], "show call must include --json flag to return structured task JSON"

    # AC: Claim the task at its current status (no status change)
    @pytest.mark.asyncio
    async def test_edit_call_does_not_include_status_flag(self) -> None:
        """start_work must NOT pass --status to edit; task remains at its current status."""
        assert _start_work is not None, "start_work not importable"
        mcp_ctx = _make_mcp_ctx()
        with _patch_run_seq(
            ("Updated task.", "", 0),
            (json.dumps(_SAMPLE_TASK), "", 0),
        ) as mock_run:
            await _start_work(mcp_ctx, task_id="470", claim="agent-x")

        all_args = [ca[0] for ca in mock_run.call_args_list]
        edit_calls = [args for args in all_args if "edit" in args]
        assert edit_calls, "start_work must call kanban-md edit"
        assert "--status" not in edit_calls[0], (
            "start_work must NOT pass --status to edit; the dispatcher already placed the task at the correct status"
        )


# ---------------------------------------------------------------------------
# TestFromAC_StartWorkErrors — error handling contract
# ---------------------------------------------------------------------------


class TestFromAC_StartWorkErrors:
    """start_work must return error strings for all failure cases without raising."""

    # AC: Tests cover: already-claimed error
    @pytest.mark.asyncio
    async def test_already_claimed_returns_error_string(self) -> None:
        """When kanban-md edit rc!=0, start_work must return an 'error:' prefixed string."""
        assert _start_work is not None, "start_work not importable"
        mcp_ctx = _make_mcp_ctx()
        claim_err = 'task #470 is claimed by "other-agent" (expires in 30m0s)'
        with _patch_run_seq(
            ("", claim_err, 1),  # edit --claim fails
            ("unused show response", "", 0),  # show (must not be reached)
        ):
            result = await _start_work(mcp_ctx, task_id="470", claim="my-agent")

        assert result.startswith("error:"), f"start_work must return 'error: ...' when claim fails, got: {result!r}"

    @pytest.mark.asyncio
    async def test_already_claimed_does_not_call_show(self) -> None:
        """When claim step fails, start_work must not proceed to call show."""
        assert _start_work is not None, "start_work not importable"
        mcp_ctx = _make_mcp_ctx()
        with _patch_run_seq(
            ("", "task #470 is claimed by other", 1),  # claim fails
            ("unused", "", 0),  # show (must not be reached)
        ) as mock_run:
            await _start_work(mcp_ctx, task_id="470", claim="my-agent")

        all_args = [ca[0] for ca in mock_run.call_args_list]
        show_calls = [args for args in all_args if "show" in args]
        assert not show_calls, "start_work must NOT call kanban-md show when the claim step fails"

    @pytest.mark.asyncio
    async def test_agent_name_failure_returns_error_string(self) -> None:
        """When agent-name returns rc!=0, start_work returns an 'error:' string."""
        assert _start_work is not None, "start_work not importable"
        mcp_ctx = _make_mcp_ctx()
        with _patch_run_seq(
            ("", "agent-name failed: no entropy", 1),  # agent-name fails
            ("unused", "", 0),  # edit (must not be reached)
            ("unused", "", 0),  # show (must not be reached)
        ):
            result = await _start_work(mcp_ctx, task_id="470")

        assert result.startswith("error:"), (
            f"start_work must return 'error: ...' when agent-name fails, got: {result!r}"
        )

    @pytest.mark.asyncio
    async def test_show_failure_returns_error_string(self) -> None:
        """When show --json fails, start_work returns an 'error:' string."""
        assert _start_work is not None, "start_work not importable"
        mcp_ctx = _make_mcp_ctx()
        with _patch_run_seq(
            ("Updated.", "", 0),  # edit --claim succeeds
            ("", "task not found", 1),  # show --json fails
        ):
            result = await _start_work(mcp_ctx, task_id="999", claim="my-agent")

        assert result.startswith("error:"), f"start_work must return 'error: ...' when show fails, got: {result!r}"
