"""Tests for owlbear.tools.diagram.toolset — DiagramToolset."""

from __future__ import annotations

from pathlib import Path
from unittest.mock import AsyncMock, MagicMock

import pytest

from owlbear.tools.diagram.service import DiagramError
from owlbear.tools.diagram.toolset import DiagramToolset

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def diagram_svc() -> MagicMock:
    """Mock DiagramService with async generate."""
    svc = MagicMock()
    svc.generate = AsyncMock(return_value=b"<svg>diagram</svg>")
    return svc


@pytest.fixture
def screenshot_svc() -> MagicMock:
    """Mock ScreenshotService with sync save and async deliver."""
    svc = MagicMock()
    svc.save.return_value = Path("/fake/.owlbear/screenshots/12345_diagram.png")
    svc.deliver = AsyncMock()
    return svc


@pytest.fixture
def channel() -> AsyncMock:
    """Mock ChannelPlugin."""
    ch = AsyncMock()
    ch.name = "test"
    return ch


@pytest.fixture
def workspace(tmp_path: Path) -> Path:
    return tmp_path


@pytest.fixture
def toolset(
    diagram_svc: MagicMock,
    screenshot_svc: MagicMock,
    channel: AsyncMock,
    workspace: Path,
) -> DiagramToolset:
    return DiagramToolset(
        diagram_service=diagram_svc,
        screenshot_service=screenshot_svc,
        channel=channel,
        workspace=workspace,
    )


# ---------------------------------------------------------------------------
# Construction & registration
# ---------------------------------------------------------------------------


class TestConstruction:
    """DiagramToolset wires up correctly."""

    def test_is_function_toolset(self, toolset: DiagramToolset) -> None:
        """Should be a FunctionToolset subclass."""
        from pydantic_ai.toolsets import FunctionToolset

        assert isinstance(toolset, FunctionToolset)

    def test_registers_generate_diagram_tool(self, toolset: DiagramToolset) -> None:
        """Should register generate_diagram via add_function."""
        names = set(toolset.tools)
        assert "generate_diagram" in names

    def test_tool_alias_is_diagram(self) -> None:
        """Class var tool_alias should be 'diagram'."""
        assert DiagramToolset.tool_alias == "diagram"


# ---------------------------------------------------------------------------
# generate_diagram — happy path
# ---------------------------------------------------------------------------


class TestGenerateDiagram:
    """generate_diagram calls service, saves, delivers, returns path."""

    @pytest.mark.asyncio
    async def test_calls_diagram_service_generate(
        self,
        toolset: DiagramToolset,
        diagram_svc: MagicMock,
    ) -> None:
        """Should call DiagramService.generate with correct args."""
        await toolset.generate_diagram(
            diagram_type="mermaid",
            source="graph TD; A-->B",
            output_format="svg",
        )
        diagram_svc.generate.assert_awaited_once_with(
            diagram_type="mermaid",
            source="graph TD; A-->B",
            output_format="svg",
        )

    @pytest.mark.asyncio
    async def test_saves_output_via_screenshot_service(
        self,
        toolset: DiagramToolset,
        screenshot_svc: MagicMock,
        workspace: Path,
    ) -> None:
        """Should save the generated bytes via ScreenshotService.save."""
        await toolset.generate_diagram(
            diagram_type="mermaid",
            source="graph TD; A-->B",
            output_format="svg",
        )
        screenshot_svc.save.assert_called_once()
        args = screenshot_svc.save.call_args[0]
        assert args[0] == b"<svg>diagram</svg>"  # image_bytes
        assert args[1] == "diagram"  # name
        assert args[2] == workspace  # workspace

    @pytest.mark.asyncio
    async def test_delivers_to_channel(
        self,
        toolset: DiagramToolset,
        screenshot_svc: MagicMock,
    ) -> None:
        """Should deliver the saved path to the channel via ScreenshotService.deliver."""
        await toolset.generate_diagram(
            diagram_type="mermaid",
            source="graph TD; A-->B",
            output_format="svg",
        )
        screenshot_svc.deliver.assert_awaited_once()
        call_args = screenshot_svc.deliver.call_args[0]
        assert call_args[0] == Path("/fake/.owlbear/screenshots/12345_diagram.png")

    @pytest.mark.asyncio
    async def test_deliver_caption_includes_diagram_type(
        self,
        toolset: DiagramToolset,
        screenshot_svc: MagicMock,
    ) -> None:
        """Caption passed to deliver should include the diagram_type."""
        await toolset.generate_diagram(
            diagram_type="plantuml",
            source="@startuml\nA -> B\n@enduml",
            output_format="svg",
        )
        caption = screenshot_svc.deliver.call_args[0][2]
        assert "plantuml" in caption

    @pytest.mark.asyncio
    async def test_returns_path_string(
        self,
        toolset: DiagramToolset,
    ) -> None:
        """Should return the string representation of the saved path."""
        result = await toolset.generate_diagram(
            diagram_type="mermaid",
            source="graph TD; A-->B",
            output_format="svg",
        )
        assert result == str(Path("/fake/.owlbear/screenshots/12345_diagram.png"))

    @pytest.mark.asyncio
    async def test_default_output_format_is_svg(
        self,
        toolset: DiagramToolset,
        diagram_svc: MagicMock,
    ) -> None:
        """output_format should default to 'svg'."""
        await toolset.generate_diagram(
            diagram_type="mermaid",
            source="graph TD; A-->B",
        )
        _, kwargs = diagram_svc.generate.call_args
        assert kwargs["output_format"] == "svg"


# ---------------------------------------------------------------------------
# generate_diagram — error handling
# ---------------------------------------------------------------------------


class TestGenerateDiagramError:
    """DiagramError is caught and returned as a user-friendly string."""

    @pytest.mark.asyncio
    async def test_diagram_error_returns_friendly_string(
        self,
        toolset: DiagramToolset,
        diagram_svc: MagicMock,
    ) -> None:
        """DiagramError should be caught and returned as user-friendly message."""
        diagram_svc.generate = AsyncMock(
            side_effect=DiagramError(status_code=400, body="Bad syntax"),
        )
        result = await toolset.generate_diagram(
            diagram_type="mermaid",
            source="invalid{{}",
            output_format="svg",
        )
        assert isinstance(result, str)
        assert "400" in result or "Bad syntax" in result

    @pytest.mark.asyncio
    async def test_diagram_error_does_not_raise(
        self,
        toolset: DiagramToolset,
        diagram_svc: MagicMock,
    ) -> None:
        """DiagramError should NOT propagate — it returns a string instead."""
        diagram_svc.generate = AsyncMock(
            side_effect=DiagramError(status_code=500, body="Internal error"),
        )
        # Should not raise
        result = await toolset.generate_diagram(
            diagram_type="mermaid",
            source="bad",
            output_format="svg",
        )
        assert isinstance(result, str)

    @pytest.mark.asyncio
    async def test_diagram_error_skips_save_and_deliver(
        self,
        toolset: DiagramToolset,
        diagram_svc: MagicMock,
        screenshot_svc: MagicMock,
    ) -> None:
        """When DiagramError occurs, save and deliver should NOT be called."""
        diagram_svc.generate = AsyncMock(
            side_effect=DiagramError(status_code=400, body="Bad syntax"),
        )
        await toolset.generate_diagram(
            diagram_type="mermaid",
            source="bad",
            output_format="svg",
        )
        screenshot_svc.save.assert_not_called()
        screenshot_svc.deliver.assert_not_awaited()


# ---------------------------------------------------------------------------
# generate_diagram — ValueError handling
# ---------------------------------------------------------------------------


class TestGenerateDiagramValueError:
    """ValueError from DiagramService.generate is caught and returned as string."""

    @pytest.mark.asyncio
    async def test_value_error_returns_friendly_string(
        self,
        toolset: DiagramToolset,
        diagram_svc: MagicMock,
    ) -> None:
        """ValueError should be caught and returned as user-friendly message."""
        diagram_svc.generate = AsyncMock(
            side_effect=ValueError("Unsupported diagram type: 'nope'"),
        )
        result = await toolset.generate_diagram(
            diagram_type="nope",
            source="graph TD; A-->B",
            output_format="svg",
        )
        assert isinstance(result, str)
        assert "Invalid input" in result
        assert "Unsupported diagram type" in result

    @pytest.mark.asyncio
    async def test_value_error_does_not_raise(
        self,
        toolset: DiagramToolset,
        diagram_svc: MagicMock,
    ) -> None:
        """ValueError should NOT propagate — it returns a string instead."""
        diagram_svc.generate = AsyncMock(
            side_effect=ValueError("source must not be empty"),
        )
        result = await toolset.generate_diagram(
            diagram_type="mermaid",
            source="",
            output_format="svg",
        )
        assert isinstance(result, str)

    @pytest.mark.asyncio
    async def test_value_error_skips_save_and_deliver(
        self,
        toolset: DiagramToolset,
        diagram_svc: MagicMock,
        screenshot_svc: MagicMock,
    ) -> None:
        """When ValueError occurs, save and deliver should NOT be called."""
        diagram_svc.generate = AsyncMock(
            side_effect=ValueError("Unsupported output format: 'bmp'"),
        )
        await toolset.generate_diagram(
            diagram_type="mermaid",
            source="graph TD; A-->B",
            output_format="bmp",
        )
        screenshot_svc.save.assert_not_called()
        screenshot_svc.deliver.assert_not_awaited()
