"""Failing tests for doc-index script (#1018).

RED phase — all tests must fail until owlbear_tools is implemented in GREEN (#1020).

AC coverage:
  - Filesystem walk with exclusion list (12 paths)
  - Markdown output format — auto-generated header, file headers, heading bullets,
    ### Outbound links sub-section
  - Outbound link extraction excludes code blocks
  - Diagram entries include `describes` field
  - Index is idempotent (same input → same output)
  - Conditional regen (skip when index mtime > newest doc mtime)
  - CLI entry point `doc-index` is resolvable
  - Parser round-trip — extracts file entries, headings, and outbound links
"""

from __future__ import annotations

import importlib.metadata
import os
import sys
import textwrap
import time
from pathlib import Path

import pytest

from owlbear_tools.doc_index import (
    collect_docs,
    generate_index,
    main,
    parse_index,
    should_regenerate,
)

# ---------------------------------------------------------------------------
# Expected exclusion dirs (§4.3 + Architecture Review refinements)
# ---------------------------------------------------------------------------

_EXCLUDED_PATHS = [
    ".owlbear/scratch",
    ".owlbear/research",
    ".owlbear/kanban",
    ".owlbear/decisions",
    ".owlbear/briefs",
    ".owlbear/sources",
    "store",
    "tests",
]

_EXCLUDED_NAMES = [
    "node_modules",
    ".git",
    ".venv",
    "dist",
    "build",
]

_EXCLUDED_DIRS = _EXCLUDED_PATHS + _EXCLUDED_NAMES

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_AUTO_GENERATED_HEADER = "<!-- AUTO-GENERATED by serve/tools/doc-index. DO NOT EDIT. Regenerated on demand. -->"


def _make_md(tmp_path: Path, rel: str, content: str = "# Title\n") -> Path:
    """Write a markdown file at *rel* relative to *tmp_path* and return the path."""
    p = tmp_path / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content)
    return p


def _make_excalidraw(tmp_path: Path, rel: str, content: str = "{}") -> Path:
    """Write an Excalidraw file at *rel* relative to *tmp_path* and return the path."""
    p = tmp_path / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content)
    return p


# ===========================================================================
# TestFromAC_FilesystemWalk
# ===========================================================================


class TestFromAC_FilesystemWalk:
    """AC: filesystem walk with exclusion list."""

    def test_collects_markdown_files(self, tmp_path: Path) -> None:
        """Happy: .md files in an unexcluded directory are returned."""
        doc = _make_md(tmp_path, "README.md")
        result = collect_docs(tmp_path)
        assert doc in result

    def test_collects_excalidraw_files(self, tmp_path: Path) -> None:
        """Happy: .excalidraw diagram files are also collected."""
        diagram = _make_excalidraw(tmp_path, "share/diagrams/overview.excalidraw")
        result = collect_docs(tmp_path)
        assert diagram in result

    def test_ignores_non_doc_file_extensions(self, tmp_path: Path) -> None:
        """Edge: .py, .json, .yaml, and other non-doc files are not collected."""
        py_file = tmp_path / "script.py"
        py_file.write_text("print('hello')")
        json_file = tmp_path / "config.json"
        json_file.write_text("{}")
        result = collect_docs(tmp_path)
        assert py_file not in result
        assert json_file not in result

    @pytest.mark.parametrize("excluded_dir", _EXCLUDED_DIRS)
    def test_excludes_all_exclusion_dirs(
        self, tmp_path: Path, excluded_dir: str
    ) -> None:
        """Boundary: each of the 12 exclusion dirs is skipped during walk."""
        excluded_path = tmp_path / excluded_dir
        excluded_path.mkdir(parents=True, exist_ok=True)
        excluded_doc = excluded_path / "some.md"
        excluded_doc.write_text("# Excluded\n")
        result = collect_docs(tmp_path)
        assert excluded_doc not in result

    def test_excludes_files_nested_inside_excluded_dir(self, tmp_path: Path) -> None:
        """Edge: files nested deeper inside an excluded dir are also excluded."""
        nested = tmp_path / ".owlbear" / "scratch" / "subdir" / "deep.md"
        nested.parent.mkdir(parents=True)
        nested.write_text("# Deep\n")
        result = collect_docs(tmp_path)
        assert nested not in result

    def test_dir_name_prefix_match_is_not_excluded(self, tmp_path: Path) -> None:
        """Boundary: 'store-backup/' shares a prefix with 'store/' but must NOT be excluded."""
        similar = tmp_path / "store-backup" / "README.md"
        similar.parent.mkdir(parents=True)
        similar.write_text("# Backup\n")
        result = collect_docs(tmp_path)
        assert similar in result

    @pytest.mark.parametrize("excluded_name", _EXCLUDED_NAMES)
    def test_excludes_name_based_dirs_at_any_depth(
        self, tmp_path: Path, excluded_name: str
    ) -> None:
        """Boundary: name-based exclusions (node_modules, .venv, etc.) work at any nesting depth."""
        nested = (
            tmp_path / "serve" / "cockpit" / "web" / excluded_name / "pkg" / "README.md"
        )
        nested.parent.mkdir(parents=True)
        nested.write_text("# Nested excluded\n")
        result = collect_docs(tmp_path)
        assert nested not in result

    def test_empty_directory_returns_empty_list(self, tmp_path: Path) -> None:
        """Edge: a tree with no doc files returns an empty list."""
        result = collect_docs(tmp_path)
        assert result == []


# ===========================================================================
# TestFromAC_MarkdownFormat
# ===========================================================================


class TestFromAC_MarkdownFormat:
    """AC: markdown output format — header, file headers, heading bullets, links section."""

    def test_output_starts_with_auto_generated_header(self, tmp_path: Path) -> None:
        """Happy: index file starts with the exact auto-generated comment header."""
        _make_md(tmp_path, "README.md", "# Title\n")
        index_path = tmp_path / ".owlbear" / "doc-index.md"
        generate_index(tmp_path, index_path)
        text = index_path.read_text()
        assert text.startswith(_AUTO_GENERATED_HEADER)

    def test_output_header_contains_do_not_edit(self, tmp_path: Path) -> None:
        """Happy: header explicitly says DO NOT EDIT."""
        _make_md(tmp_path, "docs/guide.md", "# Guide\n")
        index_path = tmp_path / ".owlbear" / "doc-index.md"
        generate_index(tmp_path, index_path)
        text = index_path.read_text()
        assert "DO NOT EDIT" in text

    def test_file_entry_header_uses_relative_path(self, tmp_path: Path) -> None:
        """Happy: each file entry starts with '## <relative-path>' (literal path)."""
        _make_md(tmp_path, "share/agents/README.md", "# Agents\n")
        index_path = tmp_path / ".owlbear" / "doc-index.md"
        generate_index(tmp_path, index_path)
        text = index_path.read_text()
        assert "## share/agents/README.md" in text

    def test_headings_are_bullet_backtick_wrapped(self, tmp_path: Path) -> None:
        """Happy: headings in a file are emitted as backtick-wrapped bullets."""
        _make_md(
            tmp_path,
            "README.md",
            "# Setup & Installation\n\n## Configuration\n",
        )
        index_path = tmp_path / ".owlbear" / "doc-index.md"
        generate_index(tmp_path, index_path)
        text = index_path.read_text()
        assert "- # `Setup & Installation`" in text
        assert "- ## `Configuration`" in text

    def test_outbound_links_subsection_present_when_links_exist(
        self, tmp_path: Path
    ) -> None:
        """Happy: ### Outbound links sub-section appears when a file has links."""
        _make_md(
            tmp_path,
            "docs/page.md",
            "# Page\n\nSee [project](https://example.com).\n",
        )
        index_path = tmp_path / ".owlbear" / "doc-index.md"
        generate_index(tmp_path, index_path)
        text = index_path.read_text()
        assert "### Outbound links" in text

    def test_outbound_links_subsection_absent_when_no_links(
        self, tmp_path: Path
    ) -> None:
        """Edge: ### Outbound links sub-section is omitted when a file has no links."""
        _make_md(tmp_path, "docs/page.md", "# Page\n\nNo links here.\n")
        index_path = tmp_path / ".owlbear" / "doc-index.md"
        generate_index(tmp_path, index_path)
        # The index for this particular file should not have an Outbound links section
        text = index_path.read_text()
        # Find the section for this specific file
        entry_start = text.index("## docs/page.md")
        # Next file section starts with '## ' or end of file
        next_entry = text.find("\n## ", entry_start + 1)
        entry_text = (
            text[entry_start:] if next_entry == -1 else text[entry_start:next_entry]
        )
        assert "### Outbound links" not in entry_text


# ===========================================================================
# TestFromAC_OutboundLinkExtraction
# ===========================================================================


class TestFromAC_OutboundLinkExtraction:
    """AC: outbound link extraction excludes code blocks."""

    def test_prose_links_are_extracted(self, tmp_path: Path) -> None:
        """Happy: [text](url) in regular prose is collected as an outbound link."""
        content = "# Page\n\nSee [the repo](https://github.com/org/repo).\n"
        _make_md(tmp_path, "page.md", content)
        index_path = tmp_path / "doc-index.md"
        generate_index(tmp_path, index_path)
        text = index_path.read_text()
        assert "https://github.com/org/repo" in text

    def test_links_in_fenced_code_block_not_extracted(self, tmp_path: Path) -> None:
        """Edge: links inside a fenced code block (``` ... ```) are ignored."""
        content = textwrap.dedent(
            """\
            # Page

            ```markdown
            See [the repo](https://github.com/org/repo).
            ```
            """
        )
        _make_md(tmp_path, "page.md", content)
        index_path = tmp_path / "doc-index.md"
        generate_index(tmp_path, index_path)
        text = index_path.read_text()
        # The link from inside the code block must NOT appear in Outbound links
        entry_start = text.index("## page.md")
        next_entry = text.find("\n## ", entry_start + 1)
        entry_text = (
            text[entry_start:] if next_entry == -1 else text[entry_start:next_entry]
        )
        assert "https://github.com/org/repo" not in entry_text

    def test_links_in_inline_code_not_extracted(self, tmp_path: Path) -> None:
        """Edge: link-like text inside backtick inline code is not extracted."""
        content = "# Page\n\nRun `[text](https://example.com)` in the terminal.\n"
        _make_md(tmp_path, "page.md", content)
        index_path = tmp_path / "doc-index.md"
        generate_index(tmp_path, index_path)
        text = index_path.read_text()
        entry_start = text.index("## page.md")
        next_entry = text.find("\n## ", entry_start + 1)
        entry_text = (
            text[entry_start:] if next_entry == -1 else text[entry_start:next_entry]
        )
        assert "https://example.com" not in entry_text

    def test_link_in_indented_code_block_not_extracted(self, tmp_path: Path) -> None:
        """Boundary: link inside a 4-space-indented code block is not extracted."""
        content = textwrap.dedent(
            """\
            # Page

                [hidden](https://hidden.example.com)

            Normal prose.
            """
        )
        _make_md(tmp_path, "page.md", content)
        index_path = tmp_path / "doc-index.md"
        generate_index(tmp_path, index_path)
        text = index_path.read_text()
        entry_start = text.index("## page.md")
        next_entry = text.find("\n## ", entry_start + 1)
        entry_text = (
            text[entry_start:] if next_entry == -1 else text[entry_start:next_entry]
        )
        assert "https://hidden.example.com" not in entry_text


# ===========================================================================
# TestFromAC_DiagramDescribesField
# ===========================================================================


class TestFromAC_DiagramDescribesField:
    """AC: diagram entries include `describes` field (list of path globs)."""

    def test_excalidraw_entry_has_describes_field(self, tmp_path: Path) -> None:
        """Happy: an Excalidraw file entry in the index contains a `describes` field."""
        _make_excalidraw(
            tmp_path,
            "share/diagrams/overview.excalidraw",
            '{"describes": ["serve/**", "share/**"]}',
        )
        index_path = tmp_path / "doc-index.md"
        generate_index(tmp_path, index_path)
        text = index_path.read_text()
        entry_start = text.index("## share/diagrams/overview.excalidraw")
        next_entry = text.find("\n## ", entry_start + 1)
        entry_text = (
            text[entry_start:] if next_entry == -1 else text[entry_start:next_entry]
        )
        assert "describes" in entry_text

    def test_describes_field_contains_globs(self, tmp_path: Path) -> None:
        """Happy: `describes` field value contains path globs (not abstract concepts)."""
        _make_excalidraw(
            tmp_path,
            "share/diagrams/kanban.excalidraw",
            '{"describes": ["serve/kanban/**", "serve/mcp-kanban/**"]}',
        )
        index_path = tmp_path / "doc-index.md"
        generate_index(tmp_path, index_path)
        text = index_path.read_text()
        entry_start = text.index("## share/diagrams/kanban.excalidraw")
        next_entry = text.find("\n## ", entry_start + 1)
        entry_text = (
            text[entry_start:] if next_entry == -1 else text[entry_start:next_entry]
        )
        # At least one glob pattern (containing * or /) should appear
        assert "serve/kanban/**" in entry_text or "serve/mcp-kanban/**" in entry_text

    def test_non_diagram_entry_has_no_describes_field(self, tmp_path: Path) -> None:
        """Boundary: a regular .md file entry does NOT have a describes field."""
        _make_md(tmp_path, "README.md", "# Root\n")
        index_path = tmp_path / "doc-index.md"
        generate_index(tmp_path, index_path)
        text = index_path.read_text()
        entry_start = text.index("## README.md")
        next_entry = text.find("\n## ", entry_start + 1)
        entry_text = (
            text[entry_start:] if next_entry == -1 else text[entry_start:next_entry]
        )
        assert "describes" not in entry_text


# ===========================================================================
# TestFromAC_Idempotency
# ===========================================================================


class TestFromAC_Idempotency:
    """AC: index is idempotent — same input produces same output."""

    def test_two_runs_produce_identical_output(self, tmp_path: Path) -> None:
        """Happy: calling generate_index twice on the same tree yields bit-for-bit identical files."""
        _make_md(tmp_path, "README.md", "# Root\n\nSee [link](https://example.com).\n")
        _make_md(tmp_path, "docs/guide.md", "# Guide\n\n## Usage\n")
        index_path = tmp_path / "doc-index.md"
        generate_index(tmp_path, index_path)
        first_output = index_path.read_text()
        generate_index(tmp_path, index_path)
        second_output = index_path.read_text()
        assert first_output == second_output

    def test_output_file_order_is_stable(self, tmp_path: Path) -> None:
        """Boundary: file order in the index is deterministic across repeated calls."""
        _make_md(tmp_path, "z_last.md", "# Z\n")
        _make_md(tmp_path, "a_first.md", "# A\n")
        _make_md(tmp_path, "m_middle.md", "# M\n")
        index_path = tmp_path / "doc-index.md"
        generate_index(tmp_path, index_path)
        run1 = index_path.read_text()
        generate_index(tmp_path, index_path)
        run2 = index_path.read_text()
        assert run1 == run2


# ===========================================================================
# TestFromAC_ConditionalRegen
# ===========================================================================


class TestFromAC_ConditionalRegen:
    """AC: conditional regen — skip when index mtime > newest doc mtime."""

    def test_no_regen_needed_when_index_is_newer(self, tmp_path: Path) -> None:
        """Happy: should_regenerate returns False when the index is newer than all docs."""
        doc = _make_md(tmp_path, "README.md", "# Root\n")
        index_path = tmp_path / "doc-index.md"
        index_path.write_text("# old index\n")
        # Set doc mtime to the past; index mtime to the future
        past = time.time() - 100
        future = time.time() + 100
        os.utime(doc, (past, past))
        os.utime(index_path, (future, future))
        assert should_regenerate(index_path, tmp_path) is False

    def test_regen_needed_when_index_does_not_exist(self, tmp_path: Path) -> None:
        """Edge: should_regenerate returns True when no index file exists."""
        _make_md(tmp_path, "README.md", "# Root\n")
        index_path = tmp_path / "doc-index.md"  # not created
        assert should_regenerate(index_path, tmp_path) is True

    def test_regen_needed_when_doc_is_newer_than_index(self, tmp_path: Path) -> None:
        """Boundary: should_regenerate returns True when any doc is newer than the index."""
        doc = _make_md(tmp_path, "README.md", "# Root\n")
        index_path = tmp_path / "doc-index.md"
        index_path.write_text("# old index\n")
        # Set index mtime to the past; doc mtime to now
        past = time.time() - 100
        present = time.time()
        os.utime(index_path, (past, past))
        os.utime(doc, (present, present))
        assert should_regenerate(index_path, tmp_path) is True


# ===========================================================================
# TestFromAC_CLIEntryPoint
# ===========================================================================


class TestFromAC_CLIEntryPoint:
    """AC: CLI entry point `doc-index` is resolvable."""

    def test_doc_index_entry_point_is_registered(self) -> None:
        """Happy: 'doc-index' is registered as a console_scripts entry point."""
        eps = importlib.metadata.entry_points(group="console_scripts")
        names = {ep.name for ep in eps}
        assert "doc-index" in names

    def test_doc_index_entry_point_is_callable(self) -> None:
        """Happy: the entry point loads to a callable without error."""
        eps = importlib.metadata.entry_points(group="console_scripts")
        ep = next((e for e in eps if e.name == "doc-index"), None)
        assert ep is not None, "doc-index entry point not found"
        func = ep.load()
        assert callable(func)


# ===========================================================================
# TestFromAC_Parser
# ===========================================================================


_WELL_FORMED_INDEX = textwrap.dedent(
    """\
    <!-- AUTO-GENERATED by serve/tools/doc-index. DO NOT EDIT. Regenerated on demand. -->

    ## README.md
    - # `Project Root`
    - ## `Overview`

    ### Outbound links
    - [docs](https://docs.example.com)
    - [repo](https://github.com/org/repo)

    ## docs/guide.md
    - # `Setup Guide`
    - ## `Installation`
    - ## `Configuration`

    ## share/diagrams/overview.excalidraw
    describes: serve/**, share/**
    """
)


class TestFromAC_Parser:
    """AC: parser round-trip — extracts file entries, headings, and outbound links."""

    def test_parser_extracts_file_entry_paths(self) -> None:
        """Happy: parse_index returns an entry for each ## file header in the index."""
        entries = parse_index(_WELL_FORMED_INDEX)
        paths = [e["path"] for e in entries]
        assert "README.md" in paths
        assert "docs/guide.md" in paths
        assert "share/diagrams/overview.excalidraw" in paths

    def test_parser_extracts_headings_from_entry(self) -> None:
        """Happy: each entry's 'headings' list matches the backtick-wrapped bullets."""
        entries = parse_index(_WELL_FORMED_INDEX)
        readme = next(e for e in entries if e["path"] == "README.md")
        assert "# Project Root" in readme["headings"]
        assert "## Overview" in readme["headings"]

    def test_parser_extracts_outbound_links(self) -> None:
        """Happy: links under ### Outbound links are returned in each entry."""
        entries = parse_index(_WELL_FORMED_INDEX)
        readme = next(e for e in entries if e["path"] == "README.md")
        link_targets = [link["target"] for link in readme["outbound_links"]]
        assert "https://docs.example.com" in link_targets
        assert "https://github.com/org/repo" in link_targets

    def test_parser_handles_entry_with_no_outbound_links(self) -> None:
        """Edge: an entry without ### Outbound links returns an empty list for that key."""
        entries = parse_index(_WELL_FORMED_INDEX)
        guide = next(e for e in entries if e["path"] == "docs/guide.md")
        assert guide["outbound_links"] == []

    def test_parser_round_trip_entry_count(self, tmp_path: Path) -> None:
        """Happy: generate_index + parse_index returns one entry per collected doc file."""
        _make_md(tmp_path, "README.md", "# Root\n")
        _make_md(tmp_path, "docs/guide.md", "# Guide\n")
        index_path = tmp_path / "doc-index.md"
        generate_index(tmp_path, index_path)
        entries = parse_index(index_path.read_text())
        assert len(entries) == 2


# ===========================================================================
# TestBuilderDiscovered
# ===========================================================================


class TestBuilderDiscovered:
    """Builder-discovered tests for uncovered paths in doc_index."""

    def test_excalidraw_invalid_json_no_crash(self, tmp_path: Path) -> None:
        """Invalid JSON in .excalidraw file is handled gracefully — no exception raised."""
        _make_excalidraw(tmp_path, "broken.excalidraw", "not valid json {{")
        index_path = tmp_path / "doc-index.md"
        generate_index(tmp_path, index_path)
        text = index_path.read_text()
        assert "## broken.excalidraw" in text

    def test_excalidraw_describes_as_string_is_rendered(self, tmp_path: Path) -> None:
        """describes field stored as a plain JSON string (not a list) appears in the index."""
        _make_excalidraw(
            tmp_path,
            "arch.excalidraw",
            '{"describes": "serve/**"}',
        )
        index_path = tmp_path / "doc-index.md"
        generate_index(tmp_path, index_path)
        text = index_path.read_text()
        entry_start = text.index("## arch.excalidraw")
        next_entry = text.find("\n## ", entry_start + 1)
        entry_text = (
            text[entry_start:] if next_entry == -1 else text[entry_start:next_entry]
        )
        assert "describes" in entry_text
        assert "serve/**" in entry_text

    def test_parser_non_outbound_section_header_resets_outbound_flag(self) -> None:
        """A ### header other than '### Outbound links' closes the outbound section."""
        index_text = textwrap.dedent(
            """\
            <!-- AUTO-GENERATED ... -->

            ## README.md
            - # `Title`

            ### Outbound links
            - [first](https://first.example.com)

            ### Notes
            - [ignored](https://ignored.example.com)
            """
        )
        entries = parse_index(index_text)
        readme = next(e for e in entries if e["path"] == "README.md")
        link_targets = [lnk["target"] for lnk in readme["outbound_links"]]
        assert "https://first.example.com" in link_targets
        assert "https://ignored.example.com" not in link_targets

    def test_main_generates_index_when_absent(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """main() creates the index at .owlbear/doc-index.md when it does not exist."""
        _make_md(tmp_path, "README.md", "# Root\n")
        index_path = tmp_path / ".owlbear" / "doc-index.md"
        monkeypatch.setattr(sys, "argv", ["doc-index", str(tmp_path)])
        main()
        assert index_path.exists()
        assert "## README.md" in index_path.read_text()

    def test_main_skips_regen_when_index_is_current(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """main() does not overwrite the index when it is already up-to-date."""
        doc = _make_md(tmp_path, "README.md", "# Root\n")
        index_path = tmp_path / ".owlbear" / "doc-index.md"
        index_path.parent.mkdir(parents=True)
        index_path.write_text("existing content")
        past = time.time() - 100
        future = time.time() + 100
        os.utime(doc, (past, past))
        os.utime(index_path, (future, future))
        monkeypatch.setattr(sys, "argv", ["doc-index", str(tmp_path)])
        main()
        assert index_path.read_text() == "existing content"

    def test_main_rejects_absolute_output_path(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """main() raises SystemExit when --output resolves to a path outside the workspace root."""
        _make_md(tmp_path, "README.md", "# Root\n")
        monkeypatch.setattr(
            sys,
            "argv",
            ["doc-index", str(tmp_path), "--output", "/tmp/steal.md"],  # noqa: S108
        )
        with pytest.raises(SystemExit):
            main()

    def test_should_regenerate_empty_workspace_with_existing_index(
        self, tmp_path: Path
    ) -> None:
        """should_regenerate returns False when no docs exist but an index exists — no stale trigger."""
        index_path = tmp_path / "doc-index.md"
        index_path.write_text("# existing\n")
        assert should_regenerate(index_path, tmp_path) is False

    def test_excalidraw_empty_describes_list_no_describes_line(
        self, tmp_path: Path
    ) -> None:
        """Excalidraw with describes=[] silently emits no describes line in the index entry."""
        _make_excalidraw(tmp_path, "empty.excalidraw", '{"describes": []}')
        index_path = tmp_path / "doc-index.md"
        generate_index(tmp_path, index_path)
        text = index_path.read_text()
        entry_start = text.index("## empty.excalidraw")
        next_entry = text.find("\n## ", entry_start + 1)
        entry_text = (
            text[entry_start:] if next_entry == -1 else text[entry_start:next_entry]
        )
        assert "describes" not in entry_text
