"""Behavioral tests for documentation collection, indexing, and parsing."""

from __future__ import annotations

import json
import sys
import textwrap
from pathlib import Path

import pytest

from owlbear_tools.doc_index import (
    collect_docs,
    generate_index,
    main,
    parse_index,
)

# Mined from #1018: documentation collection, output, link filtering, and parsing.
# Mined from #1020: CLI regeneration behavior.

# ---------------------------------------------------------------------------
# Expected exclusion dirs (§4.3 + Architecture Review refinements)
# ---------------------------------------------------------------------------

_EXCLUDED_PATHS = [
    ".owlbear/scratch",
    ".owlbear/research",
    ".owlbear/kanban",
    ".owlbear/sources",
    ".owlbear/memory",
    ".owlbear/delivery",
    ".owlbear/legacy",
    ".owlbear/target",
    ".owlbear/worktrees",
    "seed/.github",
    "store",
    "tests",
    "megalinter-reports",
]

_EXCLUDED_NAMES = [
    "node_modules",
    ".git",
    ".venv",
    ".pytest_cache",
    "dist",
    "build",
    "fixtures",
]

_EXCLUDED_DIRS = _EXCLUDED_PATHS + _EXCLUDED_NAMES

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_AUTO_GENERATED_HEADER = "<!-- AUTO-GENERATED by serve/tools/doc-index. DO NOT EDIT. Regenerated on demand. -->"


def _make_md(tmp_path: Path, rel: str, content: str = "# Title\n") -> Path:
    """Write a markdown file at *rel* relative to *tmp_path* and return the path."""
    p = tmp_path / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content)
    return p


def _make_manifest(tmp_path: Path, diagrams: list[dict[str, object]]) -> Path:
    """Write a diagram manifest under *tmp_path*."""
    p = tmp_path / "share/diagrams/manifest.json"
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps({"schema_version": 1, "diagrams": diagrams}))
    return p


def _make_diagram_source(tmp_path: Path, rel: str, content: str = "{}") -> Path:
    """Write an architecture source at *rel* relative to *tmp_path* and return the path."""
    p = tmp_path / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content)
    return p


# ===========================================================================
# TestFromAC_FilesystemWalk
# ===========================================================================


class TestDocIndexCollection:
    """AC: filesystem walk with exclusion list."""

    def test_collects_markdown_files(self, tmp_path: Path) -> None:
        """Happy: .md files in an unexcluded directory are returned."""
        doc = _make_md(tmp_path, "README.md")
        result = collect_docs(tmp_path)
        assert doc in result

    def test_does_not_collect_architecture_sources(self, tmp_path: Path) -> None:
        """Architecture JSON sources are indexed through the diagram manifest."""
        source = _make_diagram_source(tmp_path, "share/diagrams/overview.architecture.json")
        result = collect_docs(tmp_path)
        assert source not in result

    def test_ignores_non_doc_file_extensions(self, tmp_path: Path) -> None:
        """Edge: .py, .json, .yaml, and other non-doc files are not collected."""
        py_file = tmp_path / "script.py"
        py_file.write_text("print('hello')")
        json_file = tmp_path / "config.json"
        json_file.write_text("{}")
        result = collect_docs(tmp_path)
        assert py_file not in result
        assert json_file not in result

    @pytest.mark.parametrize("excluded_dir", _EXCLUDED_DIRS)
    def test_excludes_all_exclusion_dirs(self, tmp_path: Path, excluded_dir: str) -> None:
        """Boundary: each of the 12 exclusion dirs is skipped during walk."""
        excluded_path = tmp_path / excluded_dir
        excluded_path.mkdir(parents=True, exist_ok=True)
        excluded_doc = excluded_path / "some.md"
        excluded_doc.write_text("# Excluded\n")
        result = collect_docs(tmp_path)
        assert excluded_doc not in result

    def test_excludes_files_nested_inside_excluded_dir(self, tmp_path: Path) -> None:
        """Edge: files nested deeper inside an excluded dir are also excluded."""
        nested = tmp_path / ".owlbear" / "scratch" / "subdir" / "deep.md"
        nested.parent.mkdir(parents=True)
        nested.write_text("# Deep\n")
        result = collect_docs(tmp_path)
        assert nested not in result

    def test_collects_orientation_readmes_from_excluded_roots(self, tmp_path: Path) -> None:
        """Boundary: root orientation guides survive store/ and tests/ exclusions."""
        store_readme = _make_md(tmp_path, "store/README.md")
        tests_readme = _make_md(tmp_path, "tests/README.md")
        _make_md(tmp_path, "store/knowledge/ignored.md")
        _make_md(tmp_path, "tests/fixtures/ignored.md")

        result = collect_docs(tmp_path)

        assert store_readme in result
        assert tests_readme in result
        assert tmp_path / "store/knowledge/ignored.md" not in result
        assert tmp_path / "tests/fixtures/ignored.md" not in result

    def test_dir_name_prefix_match_is_not_excluded(self, tmp_path: Path) -> None:
        """Boundary: 'store-backup/' shares a prefix with 'store/' but must NOT be excluded."""
        similar = tmp_path / "store-backup" / "README.md"
        similar.parent.mkdir(parents=True)
        similar.write_text("# Backup\n")
        result = collect_docs(tmp_path)
        assert similar in result

    @pytest.mark.parametrize("excluded_name", _EXCLUDED_NAMES)
    def test_excludes_name_based_dirs_at_any_depth(self, tmp_path: Path, excluded_name: str) -> None:
        """Boundary: name-based exclusions (node_modules, .venv, etc.) work at any nesting depth."""
        nested = tmp_path / "serve" / "cockpit" / "web" / excluded_name / "pkg" / "README.md"
        nested.parent.mkdir(parents=True)
        nested.write_text("# Nested excluded\n")
        result = collect_docs(tmp_path)
        assert nested not in result

    def test_empty_directory_returns_empty_list(self, tmp_path: Path) -> None:
        """Edge: a tree with no doc files returns an empty list."""
        result = collect_docs(tmp_path)
        assert result == []


# ===========================================================================
# TestFromAC_MarkdownFormat
# ===========================================================================


class TestDocIndexMarkdownOutput:
    """AC: markdown output format — header, file headers, heading bullets, links section."""

    def test_output_starts_with_auto_generated_header(self, tmp_path: Path) -> None:
        """Happy: index file starts with the exact auto-generated comment header."""
        _make_md(tmp_path, "README.md", "# Title\n")
        index_path = tmp_path / ".owlbear" / "doc-index.md"
        generate_index(tmp_path)
        text = index_path.read_text()
        assert text.startswith(_AUTO_GENERATED_HEADER)

    def test_output_header_contains_do_not_edit(self, tmp_path: Path) -> None:
        """Happy: header explicitly says DO NOT EDIT."""
        _make_md(tmp_path, "docs/guide.md", "# Guide\n")
        index_path = tmp_path / ".owlbear" / "doc-index.md"
        generate_index(tmp_path)
        text = index_path.read_text()
        assert "DO NOT EDIT" in text

    def test_file_entry_header_uses_relative_path(self, tmp_path: Path) -> None:
        """Happy: each file entry starts with '## <relative-path>' (literal path)."""
        _make_md(tmp_path, "share/agents/README.md", "# Agents\n")
        index_path = tmp_path / ".owlbear" / "doc-index.md"
        generate_index(tmp_path)
        text = index_path.read_text()
        assert "## share/agents/README.md" in text

    def test_manifest_diagram_metadata_is_rendered(self, tmp_path: Path) -> None:
        """Happy: static diagram source, artifact, and source globs reach the index."""
        _make_manifest(
            tmp_path,
            [
                {
                    "source": "share/diagrams/overview.architecture.json",
                    "artifact": "share/diagrams/overview.svg",
                    "describes": ["serve/**", "share/**"],
                }
            ],
        )
        index_path = tmp_path / ".owlbear" / "doc-index.md"

        generate_index(tmp_path)

        text = index_path.read_text()
        assert "## share/diagrams/overview.svg" in text
        assert "source: share/diagrams/overview.architecture.json" in text
        assert "describes: serve/**, share/**" in text

    def test_headings_are_bullet_backtick_wrapped(self, tmp_path: Path) -> None:
        """Happy: headings in a file are emitted as backtick-wrapped bullets."""
        _make_md(
            tmp_path,
            "README.md",
            "# Setup & Installation\n\n## Configuration\n",
        )
        index_path = tmp_path / ".owlbear" / "doc-index.md"
        generate_index(tmp_path)
        text = index_path.read_text()
        assert "- # `Setup & Installation`" in text
        assert "- ## `Configuration`" in text

    def test_outbound_links_subsection_present_when_links_exist(self, tmp_path: Path) -> None:
        """Happy: ### Outbound links sub-section appears when a file has links."""
        _make_md(
            tmp_path,
            "docs/page.md",
            "# Page\n\nSee [project](https://example.com).\n",
        )
        index_path = tmp_path / ".owlbear" / "doc-index.md"
        generate_index(tmp_path)
        text = index_path.read_text()
        assert "### Outbound links" in text

    def test_outbound_links_subsection_absent_when_no_links(self, tmp_path: Path) -> None:
        """Edge: ### Outbound links sub-section is omitted when a file has no links."""
        _make_md(tmp_path, "docs/page.md", "# Page\n\nNo links here.\n")
        index_path = tmp_path / ".owlbear" / "doc-index.md"
        generate_index(tmp_path)
        # The index for this particular file should not have an Outbound links section
        text = index_path.read_text()
        # Find the section for this specific file
        entry_start = text.index("## docs/page.md")
        # Next file section starts with '## ' or end of file
        next_entry = text.find("\n## ", entry_start + 1)
        entry_text = text[entry_start:] if next_entry == -1 else text[entry_start:next_entry]
        assert "### Outbound links" not in entry_text

    def test_relative_outbound_links_are_rebased_to_index(self, tmp_path: Path) -> None:
        """Boundary: generated links resolve from .owlbear/doc-index.md, not their source file."""
        _make_md(tmp_path, "README.md", "# Root\n")
        _make_md(
            tmp_path,
            "serve/example/README.md",
            "# Package\n\n[Root](../../README.md) [Section](#configuration)\n",
        )
        index_path = tmp_path / ".owlbear" / "doc-index.md"

        generate_index(tmp_path)

        text = index_path.read_text()
        entry_start = text.index("## serve/example/README.md")
        next_entry = text.find("\n## ", entry_start + 1)
        entry_text = text[entry_start:] if next_entry == -1 else text[entry_start:next_entry]
        assert "[Root](../README.md)" in entry_text
        assert "[Section](../serve/example/README.md#configuration)" in entry_text


# ===========================================================================
# TestFromAC_OutboundLinkExtraction
# ===========================================================================


class TestDocIndexOutboundLinks:
    """AC: outbound link extraction excludes code blocks."""

    def test_prose_links_are_extracted(self, tmp_path: Path) -> None:
        """Happy: [text](url) in regular prose is collected as an outbound link."""
        content = "# Page\n\nSee [the repo](https://github.com/org/repo).\n"
        _make_md(tmp_path, "page.md", content)
        index_path = tmp_path / ".owlbear/doc-index.md"
        generate_index(tmp_path)
        text = index_path.read_text()
        assert "https://github.com/org/repo" in text

    def test_links_in_fenced_code_block_not_extracted(self, tmp_path: Path) -> None:
        """Edge: links inside a fenced code block (``` ... ```) are ignored."""
        content = textwrap.dedent(
            """\
            # Page

            ```markdown
            See [the repo](https://github.com/org/repo).
            ```
            """
        )
        _make_md(tmp_path, "page.md", content)
        index_path = tmp_path / ".owlbear/doc-index.md"
        generate_index(tmp_path)
        text = index_path.read_text()
        # The link from inside the code block must NOT appear in Outbound links
        entry_start = text.index("## page.md")
        next_entry = text.find("\n## ", entry_start + 1)
        entry_text = text[entry_start:] if next_entry == -1 else text[entry_start:next_entry]
        assert "https://github.com/org/repo" not in entry_text

    def test_links_in_inline_code_not_extracted(self, tmp_path: Path) -> None:
        """Edge: link-like text inside backtick inline code is not extracted."""
        content = "# Page\n\nRun `[text](https://example.com)` in the terminal.\n"
        _make_md(tmp_path, "page.md", content)
        index_path = tmp_path / ".owlbear/doc-index.md"
        generate_index(tmp_path)
        text = index_path.read_text()
        entry_start = text.index("## page.md")
        next_entry = text.find("\n## ", entry_start + 1)
        entry_text = text[entry_start:] if next_entry == -1 else text[entry_start:next_entry]
        assert "https://example.com" not in entry_text

    def test_inline_code_in_link_label_is_preserved(self, tmp_path: Path) -> None:
        """Happy: inline-code formatting in a prose link label reaches the index."""
        content = "# Page\n\nSee [`the repo`](https://github.com/org/repo).\n"
        _make_md(tmp_path, "page.md", content)
        index_path = tmp_path / ".owlbear/doc-index.md"
        generate_index(tmp_path)
        text = index_path.read_text()
        assert "[`the repo`](https://github.com/org/repo)" in text

    def test_link_in_indented_code_block_not_extracted(self, tmp_path: Path) -> None:
        """Boundary: link inside a 4-space-indented code block is not extracted."""
        content = textwrap.dedent(
            """\
            # Page

                [hidden](https://hidden.example.com)

            Normal prose.
            """
        )
        _make_md(tmp_path, "page.md", content)
        index_path = tmp_path / ".owlbear/doc-index.md"
        generate_index(tmp_path)
        text = index_path.read_text()
        entry_start = text.index("## page.md")
        next_entry = text.find("\n## ", entry_start + 1)
        entry_text = text[entry_start:] if next_entry == -1 else text[entry_start:next_entry]
        assert "https://hidden.example.com" not in entry_text


# ===========================================================================
# TestFromAC_Idempotency
# ===========================================================================


class TestDocIndexDeterminism:
    """AC: index is idempotent — same input produces same output."""

    def test_two_runs_produce_identical_output(self, tmp_path: Path) -> None:
        """Happy: calling generate_index twice on the same tree yields bit-for-bit identical files."""
        _make_md(tmp_path, "README.md", "# Root\n\nSee [link](https://example.com).\n")
        _make_md(tmp_path, "docs/guide.md", "# Guide\n\n## Usage\n")
        index_path = tmp_path / ".owlbear/doc-index.md"
        generate_index(tmp_path)
        first_output = index_path.read_text()
        generate_index(tmp_path)
        second_output = index_path.read_text()
        assert first_output == second_output

    def test_output_file_order_is_stable(self, tmp_path: Path) -> None:
        """Boundary: file order in the index is deterministic across repeated calls."""
        _make_md(tmp_path, "z_last.md", "# Z\n")
        _make_md(tmp_path, "a_first.md", "# A\n")
        _make_md(tmp_path, "m_middle.md", "# M\n")
        index_path = tmp_path / ".owlbear/doc-index.md"
        generate_index(tmp_path)
        run1 = index_path.read_text()
        generate_index(tmp_path)
        run2 = index_path.read_text()
        assert run1 == run2


# ===========================================================================
# Parser
# ===========================================================================


_WELL_FORMED_INDEX = textwrap.dedent(
    """\
    <!-- AUTO-GENERATED by serve/tools/doc-index. DO NOT EDIT. Regenerated on demand. -->

    ## README.md
    - # `Project Root`
    - ## `Overview`

    ### Outbound links
    - [docs](https://docs.example.com)
    - [repo](https://github.com/org/repo)

    ## docs/guide.md
    - # `Setup Guide`
    - ## `Installation`
    - ## `Configuration`

    ## share/diagrams/overview.svg
    source: share/diagrams/overview.architecture.json
    describes: serve/**, share/**
    """
)


class TestDocIndexParser:
    """AC: parser round-trip — extracts file entries, headings, and outbound links."""

    def test_parser_extracts_file_entry_paths(self) -> None:
        """Happy: parse_index returns an entry for each ## file header in the index."""
        entries = parse_index(_WELL_FORMED_INDEX)
        paths = [e["path"] for e in entries]
        assert "README.md" in paths
        assert "docs/guide.md" in paths
        assert "share/diagrams/overview.svg" in paths

    def test_parser_extracts_diagram_source_and_describes(self) -> None:
        """Happy: parser retains static diagram source and coverage globs."""
        entries = parse_index(_WELL_FORMED_INDEX)
        diagram = next(e for e in entries if e["path"] == "share/diagrams/overview.svg")
        assert diagram["source"] == "share/diagrams/overview.architecture.json"
        assert diagram["describes"] == ["serve/**", "share/**"]

    def test_parser_extracts_headings_from_entry(self) -> None:
        """Happy: each entry's 'headings' list matches the backtick-wrapped bullets."""
        entries = parse_index(_WELL_FORMED_INDEX)
        readme = next(e for e in entries if e["path"] == "README.md")
        assert "# Project Root" in readme["headings"]
        assert "## Overview" in readme["headings"]

    def test_parser_extracts_outbound_links(self) -> None:
        """Happy: links under ### Outbound links are returned in each entry."""
        entries = parse_index(_WELL_FORMED_INDEX)
        readme = next(e for e in entries if e["path"] == "README.md")
        link_targets = [link["target"] for link in readme["outbound_links"]]
        assert "https://docs.example.com" in link_targets
        assert "https://github.com/org/repo" in link_targets

    def test_parser_handles_entry_with_no_outbound_links(self) -> None:
        """Edge: an entry without ### Outbound links returns an empty list for that key."""
        entries = parse_index(_WELL_FORMED_INDEX)
        guide = next(e for e in entries if e["path"] == "docs/guide.md")
        assert guide["outbound_links"] == []

    def test_parser_round_trip_entry_count(self, tmp_path: Path) -> None:
        """Happy: generate_index + parse_index returns one entry per collected doc file."""
        _make_md(tmp_path, "README.md", "# Root\n")
        _make_md(tmp_path, "docs/guide.md", "# Guide\n")
        index_path = tmp_path / ".owlbear/doc-index.md"
        generate_index(tmp_path)
        entries = parse_index(index_path.read_text())
        assert len(entries) == 2


# ===========================================================================
# TestBuilderDiscovered
# ===========================================================================


class TestDocIndexCli:
    """Builder-discovered tests for uncovered paths in doc_index."""

    def test_parser_non_outbound_section_header_resets_outbound_flag(self) -> None:
        """A ### header other than '### Outbound links' closes the outbound section."""
        index_text = textwrap.dedent(
            """\
            <!-- AUTO-GENERATED ... -->

            ## README.md
            - # `Title`

            ### Outbound links
            - [first](https://first.example.com)

            ### Notes
            - [ignored](https://ignored.example.com)
            """
        )
        entries = parse_index(index_text)
        readme = next(e for e in entries if e["path"] == "README.md")
        link_targets = [lnk["target"] for lnk in readme["outbound_links"]]
        assert "https://first.example.com" in link_targets
        assert "https://ignored.example.com" not in link_targets

    def test_main_generates_index_when_absent(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        """main() creates the index at .owlbear/doc-index.md when it does not exist."""
        _make_md(tmp_path, "README.md", "# Root\n")
        index_path = tmp_path / ".owlbear" / "doc-index.md"
        monkeypatch.setattr(sys, "argv", ["doc-index", str(tmp_path)])
        main()
        assert index_path.exists()
        assert "## README.md" in index_path.read_text()

    def test_main_always_regenerates(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        """main() overwrites an existing index from current documentation."""
        _make_md(tmp_path, "README.md", "# Root\n")
        index_path = tmp_path / ".owlbear" / "doc-index.md"
        index_path.parent.mkdir(parents=True)
        index_path.write_text("existing content")
        monkeypatch.setattr(sys, "argv", ["doc-index", str(tmp_path)])
        main()
        assert "## README.md" in index_path.read_text()
