"""``delivery-lc``: live-compatibility gate on an isolated copy of live Delivery state.

``prepare`` copies the live checkout's ``.git`` and ``.owlbear/delivery`` into a stage and hashes the
live records. ``run`` creates a container whose only bind mount at (or under) the live absolute path
is the stage copy, validates its ``docker inspect`` launch provenance before starting it, proves that
isolation again inside, then runs the candidate's inspector, gate and load or full form against the copy.
``compare`` proves the live records unchanged. Record and receipt bytes, including absolute
main-checkout paths, are never rewritten: inside the container those paths resolve into the copy.

The module is stdlib-only at import, so the container can run its isolation proof before any
candidate dependency is synced; the load and full forms import Delivery lazily.
"""

from __future__ import annotations

import argparse
import contextlib
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tarfile
import tempfile
from collections import Counter
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from collections.abc import Callable

COPY_MARKER = ".lc-copy-marker"
CONTROL_MOUNT = "/lc"
UV_CACHE_MOUNT = "/root/.cache/uv"
LAUNCH_REPORT = "launch.json"
CA_BUNDLE = "ca-bundle.crt"
DEFAULT_IMAGE = "ubuntu:24.04"
_FORMAT_MARKER = "runtime/format.json"
_CONTROLLER = ".owlbear/controller"
_RELEASE_DESCRIPTOR = "RELEASE.json"
_FORMS = ("load", "full", "upgrade")
_RECORD_ROOTS = ("config.json", "runtime", "packages")
_COPY_EXCLUDES = (".venv", "node_modules", "dist", "__pycache__", ".pytest_cache", ".ruff_cache", ".mypy_cache")
_PREVIOUS_GATE = "serve/delivery/src/owlbear_delivery/state_formats.py"
_GATE_PROBE = """
import importlib.machinery, importlib.util, json, sys
from pathlib import Path
loader = importlib.machinery.SourceFileLoader("previous_state_formats", sys.argv[1])
spec = importlib.util.spec_from_loader(loader.name, loader)
module = importlib.util.module_from_spec(spec)
sys.modules[loader.name] = module
loader.exec_module(module)
report = module.scan_capability(Path(sys.argv[2]))
print(json.dumps({"supported_format": module.SUPPORTED_FORMAT,
                  "read_versions": {kind.kind_id: list(kind.read_versions) for kind in module.RECORD_KINDS},
                  "refusals": [[item.code, item.locator] for item in report.refusals]}))
"""
_INSIDE = """#!/bin/sh
# Container side, generated by delivery-lc run. The stage copy is mounted at the live path.
set -eu
LIVE="$1"; CANDIDATE="$2"; FORM="$3"; PREVIOUS="$4"
apt-get update -qq >/dev/null && apt-get install -y -qq git curl ca-certificates >/dev/null
# Trust the system store (plus an optional extra CA from --ca-bundle) for curl, uv and Python TLS.
if [ -f /lc/ca-bundle.crt ]; then cat /lc/ca-bundle.crt >> /etc/ssl/certs/ca-certificates.crt; fi
export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt UV_NATIVE_TLS=1
curl -LsSf https://astral.sh/uv/install.sh | sh >/dev/null 2>&1
export PATH="$HOME/.local/bin:$PATH"
git config --global --add safe.directory '*'
git config --global user.email lc@example.invalid && git config --global user.name lc
uv run --no-project --python 3.14 python /lc/delivery_lc.py prove-isolation --live "$LIVE" \\
  --stage-source "$(cat /lc/stage-source)" --launch /lc/launch.json --report /lc/isolation.json
ORIGIN_URL="$(git -C "$LIVE" remote get-url origin)"
git init -q --bare /remote.git
git -C "$LIVE" push -q /remote.git 'refs/remotes/origin/*:refs/heads/*'
git -C "$LIVE" config "url./remote.git.insteadOf" "$ORIGIN_URL"
git -C "$LIVE" checkout -q -f --detach "$CANDIDATE"
cd "$LIVE"
uv sync --locked --quiet
PYTHONDONTWRITEBYTECODE=1 uv run --no-sync delivery-lc inside --live "$LIVE" --form "$FORM" \\
  --previous "$PREVIOUS" --report /lc/report.json
"""


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def record_hashes(live: Path) -> dict[str, str]:
    """Hash live Delivery records (config, runtime, packages) and controller pin state without following links.

    Controller entries (``pin.json``, launchers and each release's ``RELEASE.json``) are keyed ``controller/...``.
    """
    delivery = live / ".owlbear/delivery"
    hashes: dict[str, str] = {}
    for name in _RECORD_ROOTS:
        root = delivery / name
        paths = [root] if root.is_file() else sorted(path for path in root.rglob("*") if path.is_file())
        for path in paths:
            locator = path.relative_to(delivery).as_posix()
            hashes[locator] = f"symlink:{path.readlink()}" if path.is_symlink() else _sha256(path)
    for path in _controller_state_files(live):
        locator = path.relative_to(live / ".owlbear").as_posix()
        hashes[locator] = f"symlink:{path.readlink()}" if path.is_symlink() else _sha256(path)
    return hashes


def _controller_state_files(live: Path) -> list[Path]:
    """Pin state that an upgrade rehearsal must reproduce: the pin, launchers and release descriptors."""
    controller = live / _CONTROLLER
    files = [controller / "pin.json", *sorted((controller / "bin").glob("*"))]
    files += sorted((controller / "releases").glob(f"*/{_RELEASE_DESCRIPTOR}"))
    return [path for path in files if path.is_file() or path.is_symlink()]


def _copy_tree(source: Path, destination: Path) -> None:
    shutil.copytree(source, destination, symlinks=True, ignore=shutil.ignore_patterns(*_COPY_EXCLUDES))


def _copy_pin_state(live: Path, root: Path, control: Path) -> None:
    """Copy the pin and launchers into the copy and release descriptors and ``mcp.json`` beside it.

    Release trees are platform-specific and never copied; ``run`` rebuilds them from their commits.
    """
    controller = live / _CONTROLLER
    for path in _controller_state_files(live):
        relative = path.relative_to(controller)
        target = (control / "controller" if relative.parts[0] == "releases" else root / _CONTROLLER) / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(path, target, follow_symlinks=False)
    if (live / ".vscode/mcp.json").is_file():
        shutil.copy2(live / ".vscode/mcp.json", control / "mcp.json")


def prepare(live: Path, stage: Path) -> dict[str, object]:
    """Copy live Git and Delivery state into ``stage/root`` and record live hashes in ``stage/control``."""
    live = live.resolve()
    if stage.exists():
        msg = f"stage already exists: {stage}"
        raise FileExistsError(msg)
    root, control = stage / "root", stage / "control"
    (root / ".owlbear").mkdir(parents=True)
    control.mkdir()
    _copy_tree(live / ".git", root / ".git")
    _copy_tree(live / ".owlbear/delivery", root / ".owlbear/delivery")
    _copy_pin_state(live, root, control)
    stamp = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    (root / COPY_MARKER).write_text(f"copy-of-{live} {stamp}\n", encoding="utf-8")
    hashes = record_hashes(live)
    (control / "live-before.json").write_text(json.dumps(hashes, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    (control / "stage-source").write_text(f"{root.resolve()}\n", encoding="utf-8")
    return {"live": str(live), "stage": str(stage.resolve()), "records": len(hashes)}


def compare(live: Path, stage: Path) -> dict[str, object]:
    """Return whether every live record still has its prepared hash."""
    before = json.loads((stage / "control/live-before.json").read_text(encoding="utf-8"))
    after = record_hashes(live.resolve())
    changed = sorted(locator for locator in set(before) | set(after) if before.get(locator) != after.get(locator))
    return {"live_unchanged": not changed, "changed": changed, "records": len(after)}


@dataclass(frozen=True, slots=True)
class Mount:
    """One ``/proc/self/mountinfo`` row: source ``root``, ``mount_point``, filesystem type and mount source."""

    root: str
    mount_point: str
    fstype: str = ""
    source: str = ""


# Kernel pseudo filesystems: their ``root`` is never a host directory; accepted only under the kernel trees.
_KERNEL_FILESYSTEMS = frozenset(
    {
        "autofs",
        "binfmt_misc",
        "bpf",
        "cgroup",
        "cgroup2",
        "configfs",
        "debugfs",
        "devpts",
        "devtmpfs",
        "efivarfs",
        "fusectl",
        "hugetlbfs",
        "mqueue",
        "nsfs",
        "proc",
        "pstore",
        "securityfs",
        "sysfs",
        "tracefs",
    }
)
_KERNEL_TREES = ("/proc", "/sys", "/dev")
# A bind mount keeps its source filesystem type and a bound tmpfs directory can show ``root`` ``/``, so
# neither proves a fresh instance in mountinfo. Overlay is exempt only as the container root; tmpfs only
# once each at the points the runtime creates itself (runc ``/dev``, ``/dev/shm`` and Docker's masked
# directories) with an anonymous source, and only when the validated host-side launch provenance shows no
# user-specified mount there. Any other tmpfs, under ``/run`` or elsewhere, is inspected like a bind.
_ROOT_FILESYSTEMS = frozenset({"overlay", "fuse.fuse-overlayfs"})
_RUNTIME_TMPFS_POINTS = frozenset(
    {
        "/dev",
        "/dev/shm",  # noqa: S108 - a mount point compared, never a file opened.
        "/proc/acpi",
        "/proc/asound",
        "/proc/scsi",
        "/sys/firmware",
        "/sys/devices/virtual/powercap",
    }
)
_RUNTIME_TMPFS_SOURCES = frozenset({"tmpfs", "shm", "none"})
# Docker Desktop shares a host directory as ``/run/host_mark/<top>``; ``root`` is then relative to it.
_HOST_SHARE = "/run/host_mark"
_HOST_ALIASES = ("/host_mnt", "/private")


def _unescape(field: str) -> str:
    return re.sub(r"\\([0-7]{3})", lambda match: chr(int(match.group(1), 8)), field)


def parse_mountinfo(text: str) -> list[Mount]:
    """Parse mountinfo rows into root, mount point, filesystem type and mount source."""
    mounts = []
    for line in text.splitlines():
        fields = line.split()
        if len(fields) < 5:  # noqa: PLR2004 - mountinfo: id, parent, device, root, mount point.
            continue
        tail = fields[fields.index("-", 5) + 1 :] if "-" in fields[5:] else []
        fstype, source = [*tail, "", ""][:2]
        mounts.append(Mount(_unescape(fields[3]), _unescape(fields[4]), fstype, _unescape(source)))
    return mounts


def _within(path: str, root: str) -> bool:
    return path == root or path.startswith(root.rstrip("/") + "/")


def _without_aliases(path: str) -> str:
    for alias in _HOST_ALIASES:
        if _within(path, alias):
            path = path.removeprefix(alias) or "/"
    return path


def _host_path(mount: Mount) -> str:
    """Return the host directory a mount exposes, joining a Docker Desktop share and removing host aliases."""
    path = mount.root
    if mount.source.startswith(f"{_HOST_SHARE}/"):
        share = mount.source.removeprefix(_HOST_SHARE).rstrip("/")
        path = share if mount.root == "/" else f"{share}{mount.root}"
    return _without_aliases(path)


def _container_mount(mount: Mount, *, stacked: bool, launch_points: frozenset[str] | None) -> bool:
    """Return whether a mount is positively the container root or a runtime-created pseudo mount."""
    if mount.mount_point == "/":
        return mount.fstype in _ROOT_FILESYSTEMS
    if mount.fstype in _KERNEL_FILESYSTEMS:
        return any(_within(mount.mount_point, tree) for tree in _KERNEL_TREES)
    return (
        mount.fstype == "tmpfs"
        and launch_points is not None
        and mount.mount_point not in launch_points
        and not stacked
        and mount.root == "/"
        and mount.mount_point in _RUNTIME_TMPFS_POINTS
        and mount.source in _RUNTIME_TMPFS_SOURCES
    )


def _exposes_checkout(mount: Mount, live: str, *, stacked: bool, launch_points: frozenset[str] | None) -> bool:
    """Return whether a mount may expose the real checkout, an ancestor or a descendant, at any mount point.

    ``root`` is relative to its own filesystem, whose host mount point is unknown, so any mount whose
    host path is a component run of the checkout (an ancestor) or starts with a trailing run of it (a
    descendant) fails closed.
    """
    if _container_mount(mount, stacked=stacked, launch_points=launch_points):
        return False
    exposed = Path(_host_path(mount)).parts[1:]
    checkout = Path(_without_aliases(live)).parts[1:]
    ancestor = any(checkout[end - len(exposed) : end] == exposed for end in range(len(exposed), len(checkout) + 1))
    descendant = any(exposed[:size] == checkout[-size:] for size in range(1, min(len(exposed), len(checkout)) + 1))
    return ancestor or descendant


def _source_matches(root: str, stage_source: str) -> bool:
    candidates = {stage_source, stage_source.removeprefix("/private")}
    return any(root == source or root.endswith(source) for source in candidates)


def isolation_failures(  # noqa: PLR0913 - each isolation input is an explicit keyword.
    mounts: list[Mount],
    *,
    live: str,
    stage_source: str,
    marker_present: bool,
    common_dirs: dict[str, str],
    launch_points: frozenset[str] | None,
) -> list[str]:
    """Return why the container is not isolated (D9); an empty list proves isolation.

    ``launch_points`` are the mount destinations of the validated host-side launch provenance; without
    them no runtime tmpfs is exempt and the proof fails.
    """
    failures = [] if launch_points is not None else ["no validated host-side launch provenance"]
    at_live = [mount for mount in mounts if _within(mount.mount_point, live)]
    if len(at_live) != 1 or at_live[0].mount_point != live:
        failures.append(f"expected exactly one mount at the live path, found {len(at_live)}")
    elif not _source_matches(_host_path(at_live[0]), stage_source):
        failures.append("the mount at the live path is not the stage copy")
    top = "/" + live.strip("/").split("/", 1)[0]
    outside = [mount for mount in mounts if _within(mount.mount_point, top) and not _within(mount.mount_point, live)]
    if outside:
        failures.append(f"unexpected mounts under {top}: {[mount.mount_point for mount in outside]}")
    points = Counter(mount.mount_point for mount in mounts)
    failures.extend(
        f"the real checkout, an ancestor or a descendant of it is mounted at {mount.mount_point}"
        for mount in mounts
        if _exposes_checkout(mount, live, stacked=points[mount.mount_point] > 1, launch_points=launch_points)
    )
    if not marker_present:
        failures.append("the copy marker is absent at the live path")
    expected = f"{live.rstrip('/')}/.git"
    failures.extend(
        f"{name} resolves Git outside the copy: {resolved}"
        for name, resolved in common_dirs.items()
        if resolved != expected
    )
    return failures


def _git_common_dir(path: Path) -> str:
    completed = subprocess.run(  # noqa: S603 - fixed Git argument vector inside the isolated container.
        ("git", "-C", str(path), "rev-parse", "--path-format=absolute", "--git-common-dir"),  # noqa: S607
        check=False,
        capture_output=True,
        text=True,
    )
    return completed.stdout.strip() if completed.returncode == 0 else f"<git failed: {completed.returncode}>"


def prove_isolation(live: Path, stage_source: str, launch: Path) -> dict[str, object]:
    """Inside the container: prove the stage is the only mount at the live path before any load."""
    worktrees = live / ".owlbear/delivery/worktrees"
    common_dirs = {"copy": _git_common_dir(live)}
    if worktrees.is_dir():
        common_dirs.update({child.name: _git_common_dir(child) for child in sorted(worktrees.iterdir())})
    provenance = json.loads(launch.read_text(encoding="utf-8")) if launch.is_file() else {}
    failures = isolation_failures(
        parse_mountinfo(Path("/proc/self/mountinfo").read_text(encoding="utf-8")),
        live=str(live),
        stage_source=stage_source,
        marker_present=(live / COPY_MARKER).is_file(),
        common_dirs=common_dirs,
        launch_points=frozenset(provenance["mount_points"]) if provenance.get("validated") is True else None,
    )
    return {"isolated": not failures, "failures": failures, "common_dirs": common_dirs}


def docker_command(  # noqa: PLR0913 - one container invocation binds each isolation input explicitly.
    stage: Path,
    live: Path,
    candidate: str,
    form: str,
    previous: str,
    *,
    image: str = DEFAULT_IMAGE,
    uv_cache_volume: str | None = None,
) -> list[str]:
    """Return the ``docker create`` command: the stage copy at the live path and control files at ``/lc`` only.

    The uv cache must be a Docker named volume; a path would become a host bind.
    """
    if uv_cache_volume is not None and not _VOLUME_NAME.fullmatch(uv_cache_volume):
        msg = f"--uv-cache-volume must name a Docker volume, not a path: {uv_cache_volume!r}"
        raise ValueError(msg)
    command = ["docker", "create", "-v", f"{(stage / 'root').resolve()}:{live}"]
    command += ["-v", f"{(stage / 'control').resolve()}:{CONTROL_MOUNT}"]
    if uv_cache_volume:
        command += ["-v", f"{uv_cache_volume}:{UV_CACHE_MOUNT}"]
    return [*command, image, "sh", f"{CONTROL_MOUNT}/inside.sh", str(live), candidate, form, previous]


# ---------------------------------------------------------------------------
# Host-side launch provenance (trusted ``docker inspect`` of the created container)
# ---------------------------------------------------------------------------

_VOLUME_NAME = re.compile(r"[A-Za-z0-9][A-Za-z0-9_.-]+")
_EMPTY_HOST_CONFIG = ("CapAdd", "DeviceRequests", "Devices", "Mounts", "Tmpfs", "VolumesFrom")
_NAMESPACE_MODES = {"PidMode": frozenset({""}), "IpcMode": frozenset({"", "private", "shareable"})}
_RECORDED_HOST_CONFIG = ("Binds", "Privileged", "PidMode", "IpcMode", *_EMPTY_HOST_CONFIG)


def _overlaps(path: str, live: str) -> bool:
    """Return whether a host path is the checkout, an ancestor or a descendant of it."""
    path, checkout = _without_aliases(path), _without_aliases(live)
    return _within(path, checkout) or _within(checkout, path)


def volume_failures(volume: dict[str, Any] | None, *, name: str, live: str) -> list[str]:
    """Return why ``docker volume inspect`` does not show a local named uv cache clear of the checkout."""
    if not volume or volume.get("Name") != name:
        return [f"the uv cache volume {name!r} is not an inspected named volume"]
    failures = []
    if volume.get("Driver") != "local":
        failures.append(f"the uv cache volume driver is {volume.get('Driver')!r}, not local")
    options = volume.get("Options") or {}
    device = str(options.get("device", ""))
    bind = options.get("type") == "none" or "bind" in str(options.get("o", "")).split(",")
    if options and not (bind and set(options) <= {"type", "o", "device"} and device.startswith("/")):
        failures.append(f"the uv cache volume has unsupported options: {options}")
    elif options and any(_overlaps(path, live) for path in (device, os.path.realpath(device))):
        failures.append(f"the uv cache volume is bound to {device}, overlapping the real checkout")
    return failures


def _host_config_failures(host: dict[str, Any]) -> list[str]:
    failures = ["the container is privileged"] if host.get("Privileged") else []
    failures.extend(f"HostConfig.{key} is not empty: {host[key]}" for key in _EMPTY_HOST_CONFIG if host.get(key))
    failures.extend(
        f"HostConfig.{key} shares a namespace: {host.get(key)!r}"
        for key, allowed in _NAMESPACE_MODES.items()
        if (host.get(key) or "") not in allowed
    )
    return failures


def _mount_failures(mounts: list[dict[str, Any]], expected: dict[str, tuple[str, str]]) -> list[str]:
    """Compare ``.Mounts`` with the expected destination -> (type, source or volume name) map exactly."""
    actual: dict[str, list[tuple[str, str]]] = {}
    for mount in mounts:
        kind = str(mount.get("Type"))
        if kind == "volume":
            identity = str(mount.get("Name")) if mount.get("Driver") == "local" else f"driver:{mount.get('Driver')}"
        else:
            identity = _without_aliases(str(mount.get("Source")))
        actual.setdefault(str(mount.get("Destination")), []).append((kind, identity))
    wanted = {
        point: [(kind, _without_aliases(source) if kind == "bind" else source)]
        for point, (kind, source) in expected.items()
    }
    return [
        f"mounts at {point} are {actual.get(point, [])}, expected {wanted.get(point, [])}"
        for point in sorted(set(actual) | set(wanted))
        if actual.get(point) != wanted.get(point)
    ]


def launch_failures(container: dict[str, Any], *, stage: Path, live: Path, uv_cache_volume: str | None) -> list[str]:
    """Return why a created container's inspect output is not exactly the LC launch (D9, host side).

    Allowed: the stage root bound at the live path, the control directory at ``/lc`` and the optional
    uv cache named volume; nothing else mounted, no device, tmpfs, shared volumes, privilege or capability.
    """
    root, control, checkout = str((stage / "root").resolve()), str((stage / "control").resolve()), str(live)
    failures = [
        f"the stage path {path} overlaps the real checkout" for path in (root, control) if _overlaps(path, checkout)
    ]
    host = container.get("HostConfig") or {}
    failures += _host_config_failures(host)
    binds = [f"{root}:{checkout}", f"{control}:{CONTROL_MOUNT}"]
    expected = {checkout: ("bind", root), CONTROL_MOUNT: ("bind", control)}
    if uv_cache_volume:
        binds.append(f"{uv_cache_volume}:{UV_CACHE_MOUNT}")
        expected[UV_CACHE_MOUNT] = ("volume", uv_cache_volume)
    if sorted(host.get("Binds") or []) != sorted(binds):
        failures.append(f"HostConfig.Binds is {host.get('Binds')}, expected {binds}")
    return failures + _mount_failures(container.get("Mounts") or [], expected)


def launch_report(
    container: dict[str, Any],
    volume: dict[str, Any] | None,
    *,
    stage: Path,
    live: Path,
    uv_cache_volume: str | None,
) -> dict[str, Any]:
    """Validate and record the provenance-relevant subset of ``docker inspect`` (and the cache volume)."""
    failures = launch_failures(container, stage=stage, live=live, uv_cache_volume=uv_cache_volume)
    if uv_cache_volume:
        failures += volume_failures(volume, name=uv_cache_volume, live=str(live))
    host = container.get("HostConfig") or {}
    mounts = container.get("Mounts") or []
    return {
        "validated": not failures,
        "failures": failures,
        "container": container.get("Id"),
        "mount_points": sorted(str(mount.get("Destination")) for mount in mounts),
        "mounts": mounts,
        "host_config": {key: host.get(key) for key in _RECORDED_HOST_CONFIG},
        "volume": volume,
    }


def _docker(*arguments: str, check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(("docker", *arguments), check=check, capture_output=True, text=True)  # noqa: S603, S607


def _inspected(*arguments: str) -> dict[str, Any]:
    return json.loads(_docker(*arguments).stdout)[0]


def _start(container: str, log: Path) -> int:
    with log.open("wb") as handle:
        completed = subprocess.run(  # noqa: S603 - fixed Docker argument vector.
            ("docker", "start", "-a", container),  # noqa: S607
            check=False,
            stdout=handle,
            stderr=subprocess.STDOUT,
        )
    return completed.returncode


def _launch(
    command: list[str], control: Path, *, stage: Path, live: Path, uv_cache_volume: str | None
) -> dict[str, Any]:
    """Create the container, validate its inspect provenance, then start it attached; always remove it."""
    volume = None
    if uv_cache_volume:
        _docker("volume", "create", uv_cache_volume)
        volume = _inspected("volume", "inspect", uv_cache_volume)
        refused = volume_failures(volume, name=uv_cache_volume, live=str(live))
        if refused:
            return {"exit": None, "report": {}, "launch": {"validated": False, "failures": refused, "volume": volume}}
    container = _docker(*command[1:]).stdout.strip()
    try:
        if uv_cache_volume:
            volume = _inspected("volume", "inspect", uv_cache_volume)
        launch = launch_report(
            _inspected("inspect", container), volume, stage=stage, live=live, uv_cache_volume=uv_cache_volume
        )
        (control / LAUNCH_REPORT).write_text(json.dumps(launch, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        if not launch["validated"]:
            return {"exit": None, "report": {}, "launch": launch}
        code = _start(container, control / "run.log")
    finally:
        _docker("rm", "-f", container, check=False)
    report = control / "report.json"
    result = json.loads(report.read_text(encoding="utf-8")) if report.is_file() else {}
    return {"exit": code, "report": result, "launch": launch, "log": str(control / "run.log")}


def run(  # noqa: PLR0913 - mirrors docker_command.
    stage: Path,
    live: Path,
    candidate: str,
    form: str,
    previous: str,
    *,
    image: str = DEFAULT_IMAGE,
    uv_cache_volume: str | None = None,
    ca_bundle: Path | None = None,
    bundles: Path | None = None,
    dry_run: bool = False,
) -> dict[str, object]:
    """Write the container script, validate the created container's launch provenance and run the LC form.

    ``ca_bundle`` (PEM) is appended to the container trust store, for networks that intercept TLS.
    ``bundles`` holds prebuilt Cockpit bundles as ``<commit>/index.html``; the upgrade form needs them.
    """
    control = stage / "control"
    command = docker_command(stage, live, candidate, form, previous, image=image, uv_cache_volume=uv_cache_volume)
    (control / "inside.sh").write_text(_INSIDE, encoding="utf-8")
    shutil.copyfile(__file__, control / "delivery_lc.py")
    (control / LAUNCH_REPORT).unlink(missing_ok=True)
    if ca_bundle is not None:
        shutil.copyfile(ca_bundle, control / CA_BUNDLE)
    if bundles is not None:
        shutil.rmtree(control / "bundles", ignore_errors=True)
        shutil.copytree(bundles, control / "bundles")
    if dry_run:
        return {"command": command}
    return _launch(command, control, stage=stage, live=live, uv_cache_volume=uv_cache_volume)


# ---------------------------------------------------------------------------
# Inside the container (candidate code): load and full forms
# ---------------------------------------------------------------------------


def _read_config(path: Path) -> object:
    from owlbear_delivery.delivery_application_loader import DeliveryStartupConfig  # noqa: PLC0415

    return DeliveryStartupConfig.model_validate_json(path.read_bytes(), strict=True)


def _load_every_change(live: Path) -> dict[str, object]:
    """Normal composition (it may write); only the previous release's rollback load uses it."""
    from owlbear_delivery import close_delivery_application  # noqa: PLC0415
    from owlbear_delivery.application_models import DeliveryUnavailableChangeView  # noqa: PLC0415
    from owlbear_delivery.delivery_application_loader import (  # noqa: PLC0415
        DeliveryApplicationLoadError,
        load_configured_delivery_application,
    )

    try:
        application = load_configured_delivery_application(live, _read_config)  # type: ignore[arg-type]
    except DeliveryApplicationLoadError as exc:
        return {"loaded": False, "field": exc.field, "code": exc.code, "detail": exc.detail}
    try:
        changes = live / ".owlbear/delivery/runtime/changes"
        change_ids = sorted(path.name for path in changes.iterdir() if path.is_dir()) if changes.is_dir() else []
        unavailable = [
            change_id
            for change_id in change_ids
            if isinstance(application.get_change(change_id), DeliveryUnavailableChangeView)
        ]
        return {"loaded": True, "changes": change_ids, "unavailable": unavailable}
    finally:
        close_delivery_application(application)


def _read_only_load(live: Path) -> dict[str, object]:
    """Candidate load of every Change through the offline read-only composition."""
    from owlbear_delivery import close_delivery_application  # noqa: PLC0415
    from owlbear_delivery.application_models import DeliveryUnavailableChangeView  # noqa: PLC0415
    from owlbear_delivery.delivery_application_loader import (  # noqa: PLC0415
        DeliveryApplicationLoadError,
        load_read_only_application,
    )
    from owlbear_delivery.storage_io import ReadOnlyStateError, read_only_state  # noqa: PLC0415

    changes = live / ".owlbear/delivery/runtime/changes"
    change_ids = sorted(path.name for path in changes.iterdir() if path.is_dir()) if changes.is_dir() else []
    try:
        with read_only_state():
            application = load_read_only_application(live, _read_config)  # type: ignore[arg-type]
            try:
                unavailable = [
                    change_id
                    for change_id in change_ids
                    if isinstance(application.get_change(change_id), DeliveryUnavailableChangeView)
                ]
            finally:
                close_delivery_application(application)
    except DeliveryApplicationLoadError as exc:
        return {"loaded": False, "field": exc.field, "code": exc.code, "detail": exc.detail}
    except ReadOnlyStateError:
        return {"loaded": False, "code": "read-only-write-attempted", "detail": "the load attempted a record write"}
    return {"loaded": True, "changes": change_ids, "unavailable": unavailable}


def _changed(before: dict[str, str], after: dict[str, str]) -> list[str]:
    return sorted(locator for locator in set(before) | set(after) if before.get(locator) != after.get(locator))


def _read_phase(live: Path) -> dict[str, Any]:
    """Inspector, gate and read-only load, each bracketed by a complete record-tree comparison.

    ``records_changed`` names every record (excluding L-class locks and transients) that any of the
    three reads added, removed or rewrote; a compatibility read that changes one fails its form.
    """
    from owlbear_delivery.state_formats import record_tree_digest  # noqa: PLC0415

    phase: dict[str, Any] = {}
    changed: dict[str, list[str]] = {}
    for name, read in (("inspector", _inspect), ("gate", _gate), ("load", _read_only_load)):
        before = record_tree_digest(live)
        phase[name] = read(live)
        changed[name] = _changed(before, record_tree_digest(live))
    phase["records_changed"] = {name: locators for name, locators in changed.items() if locators}
    return phase


def _gate(live: Path) -> list[list[str]]:
    from owlbear_delivery.state_formats import scan_capability  # noqa: PLC0415

    return [[refusal.code, refusal.locator] for refusal in scan_capability(live).refusals]


def _inspect(live: Path) -> dict[str, object]:
    """Run the candidate ``delivery-diagnose inspect`` against the copy and keep its bounded summary."""
    module = (sys.executable, "-m", "owlbear_tools.delivery_diagnostics")
    completed = subprocess.run(  # noqa: S603 - fixed interpreter, module and argument vector.
        (*module, "inspect", "--project-root", str(live), "--format", "json"),
        check=False,
        capture_output=True,
        text=True,
    )
    try:
        result = json.loads(completed.stdout)
    except ValueError:
        return {"exit": completed.returncode, "status": "unavailable", "diagnostic_codes": ["INSPECTOR_OUTPUT_INVALID"]}
    return {
        "exit": completed.returncode,
        "status": result.get("status"),
        "inspection_complete": result.get("inspection_complete"),
        "diagnostic_codes": result.get("diagnostic_codes", []),
        "format": result.get("format"),
    }


_MIGRATION_DIAGNOSTIC = re.compile(r"[A-Z_]+_MIGRATION_REQUIRED")


def inspector_agrees(inspection: dict[str, Any], gate: list[list[str]], load: dict[str, Any]) -> bool:
    """Return whether the inspector's verdict matches the gate and the load (plan section 3.3).

    A loaded copy with no gate refusal must inspect as complete ``healthy-structure`` with no
    diagnostic; a copy refused only for migration must show only migration-required diagnostics,
    the format one exactly when the gate refuses the marker; any other refusal must not inspect healthy.
    """
    codes = list(inspection.get("diagnostic_codes") or [])
    if not gate:
        return bool(
            load.get("loaded")
            and not load.get("unavailable")
            and inspection.get("status") == "healthy-structure"
            and inspection.get("inspection_complete") is True
            and not codes
        )
    if all(code == "state-migration-required" for code, _locator in gate):
        format_refused = ["state-migration-required", _FORMAT_MARKER] in gate
        return bool(
            codes
            and all(_MIGRATION_DIAGNOSTIC.fullmatch(code) for code in codes)
            and ("FORMAT_MIGRATION_REQUIRED" in codes) == format_refused
        )
    return inspection.get("status") != "healthy-structure"


def _previous_gate(live: Path, previous: str, root: Path) -> dict[str, object]:
    """Run the previous release's stdlib gate from its commit against ``root`` (D3 oracle)."""
    source = subprocess.run(  # noqa: S603 - fixed Git argument vector.
        ("git", "-C", str(live), "show", f"{previous}:{_PREVIOUS_GATE}"),  # noqa: S607
        check=True,
        capture_output=True,
    ).stdout
    with tempfile.TemporaryDirectory() as directory:
        gate = Path(directory) / "state_formats.py"
        gate.write_bytes(source)
        completed = subprocess.run(  # noqa: S603 - fixed interpreter and argument vector.
            (sys.executable, "-I", "-c", _GATE_PROBE, str(gate), str(root)),
            check=True,
            capture_output=True,
            text=True,
        )
    return json.loads(completed.stdout)


def _previous_load(live: Path, previous: str) -> dict[str, object]:
    """Install the previous release from its commit and load every Change of ``live`` with it (rollback)."""
    environment = {key: value for key, value in os.environ.items() if key not in {"VIRTUAL_ENV", "PYTHONPATH"}}
    with tempfile.TemporaryDirectory() as directory:
        archive, tree = Path(directory) / "previous.tar", Path(directory) / "previous"
        subprocess.run(  # noqa: S603 - fixed Git argument vector.
            ("git", "-C", str(live), "archive", "--format=tar", "-o", str(archive), previous),  # noqa: S607
            check=True,
            capture_output=True,
        )
        with tarfile.open(archive) as handle:
            handle.extractall(tree, filter="data")
        synced = subprocess.run(
            ("uv", "sync", "--locked", "--quiet"),  # noqa: S607 - uv from PATH in the container.
            cwd=tree,
            env=environment,
            check=False,
            capture_output=True,
            text=True,
        )
        if synced.returncode != 0:
            return {"loaded": False, "code": "previous-release-unavailable", "detail": synced.stderr[-2000:]}
        completed = subprocess.run(  # noqa: S603 - the previous release's interpreter runs this module's loader.
            (str(tree / ".venv/bin/python"), "-I", __file__, "load-changes", "--live", str(live)),
            env=environment,
            check=False,
            capture_output=True,
            text=True,
        )
    try:
        return json.loads(completed.stdout)
    except ValueError:
        return {"loaded": False, "code": "previous-load-failed", "detail": completed.stderr[-2000:]}


def beyond_previous_release(report: dict[str, Any]) -> list[str]:
    """Locators of migrated records whose version exceeds every version the previous registry reads (D3).

    A record kind absent from the previous registry supports no version.
    """
    supported = report["previous_gate_after"].get("read_versions", {})
    return sorted(
        locator
        for kind_id, locator, version in report.get("migrated_versions", [])
        if version > max(supported.get(kind_id, ()), default=0)
    )


def previous_release_oracle(report: dict[str, Any]) -> bool:
    """D3 on the migrated copy: a release supporting its format and family versions loads it, else refuses it.

    Supported rollback needs no gate refusal and a load by that release listing the candidate's Changes,
    all available. Unsupported downgrade needs unchanged record hashes and the typed newer refusal: at
    ``runtime/format.json`` for a newer format, otherwise at exactly the records whose family version
    exceeds the previous registry, with no other refusal and no load. Any other refusal is not enough.
    """
    previous = report["previous_gate_after"]
    load = report.get("previous_load") or {}
    if previous["supported_format"] < report["target_format"]:
        return bool(
            ["state-newer-than-controller", _FORMAT_MARKER] in previous["refusals"]
            and report.get("previous_gate_hashes_unchanged") is True
        )
    if beyond := beyond_previous_release(report):
        return bool(
            sorted(previous["refusals"]) == [["state-newer-than-controller", locator] for locator in beyond]
            and report.get("previous_gate_hashes_unchanged") is True
            and not load.get("loaded")
        )
    return bool(
        previous["refusals"] == []
        and load.get("loaded") is True
        and load.get("changes") == report["migrated"]["load"].get("changes")
        and not load.get("unavailable")
    )


def _record_versions(live: Path) -> list[list[object]]:
    """Candidate registry kind, locator and version of every versioned record."""
    from owlbear_delivery.state_formats import scan_capability  # noqa: PLC0415

    return [
        [record.kind_id, record.locator, record.version]
        for record in scan_capability(live).records
        if record.kind_id is not None and record.version is not None
    ]


def _synthetic_newer(live: Path) -> list[list[str]]:
    """Refusal of a copy whose marker names a format newer than the candidate supports."""
    from owlbear_delivery.state_formats import SUPPORTED_FORMAT, format_marker_bytes  # noqa: PLC0415

    with tempfile.TemporaryDirectory() as directory:
        copy = Path(directory)
        shutil.copytree(
            live / ".owlbear/delivery",
            copy / ".owlbear/delivery",
            symlinks=True,
            ignore=shutil.ignore_patterns("worktrees"),
        )
        (copy / ".owlbear/delivery/runtime/format.json").write_bytes(format_marker_bytes(SUPPORTED_FORMAT + 1))
        return _gate(copy)


def load_form(live: Path) -> dict[str, object]:
    """Gate report, candidate inspector and read-only application load of the unmodified copy."""
    report: dict[str, Any] = {"form": "load", **_read_phase(live)}
    load = report["load"]
    report["inspector_agrees"] = inspector_agrees(report["inspector"], report["gate"], load)
    report["passed"] = bool(
        load.get("loaded")
        and not load.get("unavailable")
        and report["inspector_agrees"]
        and not report["records_changed"]
    )
    return report


def full_form(
    live: Path,
    previous: str,
    *,
    previous_load: Callable[[Path, str], dict[str, object]] = _previous_load,
) -> dict[str, object]:
    """Load form plus typed refusal of the unmigrated copy, migration, D3 oracle and newer-format refusal."""
    from owlbear_delivery import state_migration  # noqa: PLC0415
    from owlbear_delivery.state_formats import SUPPORTED_FORMAT, record_tree_digest  # noqa: PLC0415

    report: dict[str, Any] = {"form": "full", "previous": previous, "target_format": SUPPORTED_FORMAT}
    pre = record_tree_digest(live)
    pre_records = record_tree_digest(live, exclude_migrations=True)
    report["previous_gate_before"] = _previous_gate(live, previous, live)
    report["unmigrated"] = _read_phase(live)
    report["unmigrated_hashes_unchanged"] = record_tree_digest(live) == pre
    try:
        proposal = state_migration.propose(live)
        report["proposal"] = {
            "migration_id": proposal.migration_id,
            "source_format": proposal.source_format,
            "target_format": proposal.target_format,
            "steps": list(proposal.steps),
            "entries": [entry.model_dump(mode="json") for entry in proposal.entries],
        }
        report["apply"] = state_migration.apply(live, proposal.migration_id).state
        report["verify"] = state_migration.verify(live, proposal.migration_id).state
    except state_migration.MigrationError as exc:
        report["migration_error"] = {"code": exc.code, "detail": exc.detail, "locator": exc.locator}
        report["passed"] = False
        return report
    post = record_tree_digest(live, exclude_migrations=True)
    report["changed_records"] = sorted(k for k in set(pre_records) | set(post) if pre_records.get(k) != post.get(k))
    report["migrated"] = _read_phase(live)
    report["migrated_versions"] = _record_versions(live)
    migrated_hashes = record_tree_digest(live)
    report["previous_gate_after"] = _previous_gate(live, previous, live)
    report["previous_gate_hashes_unchanged"] = record_tree_digest(live) == migrated_hashes
    report["previous_beyond"] = beyond_previous_release(report)
    report["synthetic_newer"] = _synthetic_newer(live)
    if report["previous_gate_after"]["supported_format"] >= SUPPORTED_FORMAT and not report["previous_beyond"]:
        # Last: a normal load by the rollback release may write to the copy.
        report["previous_load"] = previous_load(live, previous)
    report["passed"] = _full_form_passed(report, {entry["locator"] for entry in report["proposal"]["entries"]})
    return report


def _full_form_passed(report: dict[str, Any], proposed: set[str]) -> bool:
    unmigrated, migrated = report["unmigrated"], report["migrated"]
    load = migrated["load"]
    return bool(
        unmigrated["load"].get("code", "").startswith("state-")
        and report["unmigrated_hashes_unchanged"]
        and not unmigrated["records_changed"]
        and not migrated["records_changed"]
        and inspector_agrees(unmigrated["inspector"], unmigrated["gate"], unmigrated["load"])
        and report.get("verify") == "verified"
        and set(report["changed_records"]) == proposed
        and migrated["gate"] == []
        and load.get("loaded")
        and not load.get("unavailable")
        and inspector_agrees(migrated["inspector"], migrated["gate"], load)
        and previous_release_oracle(report)
        and any(code == "state-newer-than-controller" for code, _locator in report["synthetic_newer"])
    )


# ---------------------------------------------------------------------------
# Inside the container: upgrade rehearsal (N02-D procedure on the copy)
# ---------------------------------------------------------------------------

_GATE_SOURCE = "serve/delivery/src/owlbear_delivery/state_formats.py"
_HTTP_OK = 200
_HEALTHY = "healthy"
_BLOCKING_READINESS = frozenset({"engine-action-interrupted", "worker-stall-wait"})
_UNGATED_PROBE = """
import json, sys
from pathlib import Path
from owlbear_delivery_mcp.server import load_delivery_application, load_delivery_config
root = Path(sys.argv[1])
application = load_delivery_application(load_delivery_config(root / ".owlbear/delivery/config.json"), root)
views = {change: application.get_change(change).model_dump(mode="json") for change in sys.argv[2:]}
print(json.dumps({"started": True, "health": application.delivery_health().model_dump(mode="json"), "views": views}))
"""


def readiness_blockers(payload: object) -> list[str]:
    """Readiness reasons in a controller projection that block an upgrade (running or interrupted custody)."""
    found: set[str] = set()
    pending: list[object] = [payload]
    while pending:
        value = pending.pop()
        if isinstance(value, dict):
            reason = value.get("reason_code")
            if isinstance(reason, str) and (value.get("state") == "running" or reason in _BLOCKING_READINESS):
                found.add(reason)
            pending.extend(value.values())
        elif isinstance(value, list):
            pending.extend(value)
    return sorted(found)


def _change_ids(live: Path) -> list[str]:
    changes = live / ".owlbear/delivery/runtime/changes"
    return sorted(path.name for path in changes.iterdir() if path.is_dir()) if changes.is_dir() else []


def _cli(executable: Path, *arguments: str) -> dict[str, Any]:
    completed = subprocess.run(  # noqa: S603 - release console scripts with fixed argument vectors.
        (str(executable), *arguments), check=False, capture_output=True, text=True
    )
    try:
        payload = json.loads(completed.stdout)
    except ValueError:
        payload = {"output": completed.stdout[-2000:], "stderr": completed.stderr[-2000:]}
    return {"exit": completed.returncode, **payload}


def _session_summary(views: dict[str, Any], health: object) -> dict[str, Any]:
    unavailable = sorted(change for change, view in views.items() if view.get("kind") == "unavailable")
    return {"unavailable": unavailable, "blockers": readiness_blockers([views, health]), "views": views}


async def _mcp_calls(command: list[str], live: Path, change_ids: list[str]) -> dict[str, Any]:
    from mcp import ClientSession, StdioServerParameters  # noqa: PLC0415
    from mcp.client.stdio import stdio_client  # noqa: PLC0415

    parameters = StdioServerParameters(command=command[0], args=command[1:], cwd=str(live), env=dict(os.environ))
    async with stdio_client(parameters) as (read, write), ClientSession(read, write) as session:
        await session.initialize()

        async def call(name: str, arguments: dict[str, str]) -> dict[str, Any]:
            result = await session.call_tool(name, arguments)
            return json.loads(result.content[0].text)  # type: ignore[union-attr]

        health = await call("delivery_health", {})
        views = {change: await call("get_change", {"change_id": change}) for change in change_ids}
    return {"started": True, "health_status": health.get("status"), **_session_summary(views, health)}


def mcp_session(command: list[str], live: Path, change_ids: list[str]) -> dict[str, Any]:
    """Start one MCP controller over stdio exactly as VS Code would, read health and every Change, stop it."""
    import asyncio  # noqa: PLC0415

    try:
        return asyncio.run(asyncio.wait_for(_mcp_calls(command, live, change_ids), 300))
    except Exception as exc:  # noqa: BLE001 - any startup or protocol failure is the recorded result.
        return {"started": False, "error": f"{type(exc).__name__}: {exc}"[:2000]}


def _ungated_session(live: Path, previous: str, change_ids: list[str]) -> dict[str, Any]:
    """Step 1 through an ungated (D03) controller run from its commit, as the live checkout runs it."""
    environment = {key: value for key, value in os.environ.items() if key not in {"VIRTUAL_ENV", "PYTHONPATH"}}
    with tempfile.TemporaryDirectory() as directory:
        tree = Path(directory) / "previous"
        archive = Path(directory) / "previous.tar"
        subprocess.run(  # noqa: S603 - fixed Git argument vector.
            ("git", "-C", str(live), "archive", "--format=tar", "-o", str(archive), previous),  # noqa: S607
            check=True,
            capture_output=True,
        )
        with tarfile.open(archive) as handle:
            handle.extractall(tree, filter="data")
        subprocess.run(("uv", "sync", "--locked", "--quiet"), cwd=tree, env=environment, check=True)  # noqa: S607
        completed = subprocess.run(  # noqa: S603 - the previous interpreter runs a fixed probe.
            (str(tree / ".venv/bin/python"), "-I", "-c", _UNGATED_PROBE, str(live), *change_ids),
            env=environment,
            check=False,
            capture_output=True,
            text=True,
        )
    try:
        probe = json.loads(completed.stdout)
    except ValueError:
        return {"started": False, "error": completed.stderr[-2000:]}
    health = probe["health"]
    return {"started": True, "health_status": health.get("status"), **_session_summary(probe["views"], health)}


def cockpit_check(launcher: Path, live: Path, index: Path) -> dict[str, Any]:
    """Start Cockpit through its launcher, read ``/api/work-items`` and compare ``/`` with the release bundle."""
    import socket  # noqa: PLC0415
    import time  # noqa: PLC0415
    import urllib.error  # noqa: PLC0415
    import urllib.request  # noqa: PLC0415

    with socket.socket() as probe:
        probe.bind(("127.0.0.1", 0))
        port = probe.getsockname()[1]
    environment = {**os.environ, "COCKPIT_NO_OPEN": "1", "COCKPIT_PORT": str(port)}
    process = subprocess.Popen(  # noqa: S603 - the generated release launcher, no arguments.
        (str(launcher),),
        cwd=live,
        env=environment,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.PIPE,
    )
    status, served = None, b""
    try:
        deadline = time.monotonic() + 120
        while status is None and process.poll() is None and time.monotonic() < deadline:
            try:
                with urllib.request.urlopen(f"http://127.0.0.1:{port}/api/work-items", timeout=10) as response:
                    status = response.status
                with urllib.request.urlopen(f"http://127.0.0.1:{port}/", timeout=10) as response:
                    served = response.read()
            except urllib.error.URLError, ConnectionError, TimeoutError:
                time.sleep(0.5)
    finally:
        process.terminate()
        try:
            _out, error = process.communicate(timeout=15)
        except subprocess.TimeoutExpired:
            process.kill()
            _out, error = process.communicate()
    return {
        "work_items_status": status,
        "index_matches_release": bool(served) and served == index.read_bytes(),
        "stderr": error.decode(errors="replace")[-1500:] if status != _HTTP_OK else "",
    }


def _mcp_command(live: Path) -> list[str]:
    """The tracked ``.vscode/mcp.json`` command for ``owlbear-delivery``, ``${workspaceFolder}`` resolved."""
    server = json.loads((live / ".vscode/mcp.json").read_text(encoding="utf-8"))["servers"]["owlbear-delivery"]
    return [part.replace("${workspaceFolder}", str(live)) for part in (server["command"], *server.get("args", []))]


def _migrate(release_bin: Path, live: Path) -> dict[str, Any]:
    proposal = _cli(release_bin / "delivery-migrate", "--project-root", str(live), "propose")
    if proposal["exit"] != 0:
        return (
            {"required": False, "proposal": proposal}
            if proposal.get("code") == "migration-not-required"
            else {"required": True, "proposal": proposal, "verified": False}
        )
    migration_id = str(proposal["migration_id"])
    applied = _cli(release_bin / "delivery-migrate", "--project-root", str(live), "apply", migration_id)
    verified = _cli(release_bin / "delivery-migrate", "--project-root", str(live), "verify", migration_id)
    return {
        "required": True,
        "proposal": proposal,
        "apply": applied,
        "verify": verified,
        "verified": verified.get("status") == "verified",
    }


def _install_release(live: Path, commit: str, control: Path) -> dict[str, Any]:
    from owlbear_tools import delivery_controller  # noqa: PLC0415

    layout = delivery_controller.Layout(live)
    try:
        result = delivery_controller.install(layout, commit, bundle_source=control / "bundles" / commit)
    except delivery_controller.ControllerError as exc:
        return {"installed": False, "code": exc.code, "detail": exc.detail}
    release = result.get("release") or {}
    copied = control / "controller/releases" / commit / _RELEASE_DESCRIPTOR
    if copied.is_file():
        recorded = json.loads(copied.read_text(encoding="utf-8"))
        same = {key: recorded.get(key) for key in ("commit", "supported_format")}
        if same != {key: release.get(key) for key in same}:
            return {"installed": False, "code": "release-differs-from-pinned", "copied": same}
    return {"installed": True, "commit": commit, "supported_format": release.get("supported_format")}


def _previous_controller(live: Path, previous: str, control: Path, change_ids: list[str]) -> dict[str, Any]:
    """Bring up the controller the copy runs before the upgrade and observe it read-only (procedure step 1)."""
    from owlbear_delivery.state_formats import read_controller_pin  # noqa: PLC0415
    from owlbear_tools import delivery_controller  # noqa: PLC0415

    gated = (
        subprocess.run(  # noqa: S603 - fixed Git argument vector.
            ("git", "-C", str(live), "cat-file", "-e", f"{previous}:{_GATE_SOURCE}"),  # noqa: S607
            check=False,
            capture_output=True,
        ).returncode
        == 0
    )
    if not gated:
        return {"gated": False, "online": _ungated_session(live, previous, change_ids)}
    pinned = read_controller_pin(live)
    if pinned is not None and pinned.commit != previous:
        return {"gated": True, "error": f"the copy is pinned to {pinned.commit}, not {previous}"}
    steps: dict[str, Any] = {"gated": True, "release": _install_release(live, previous, control)}
    if pinned is None:
        layout = delivery_controller.Layout(live)
        steps["migration"] = _migrate(layout.release(previous) / ".venv/bin", live)
        steps["pin"] = delivery_controller.run(["--project-root", str(live), "pin", previous])[1]
    steps["online"] = mcp_session(_mcp_command(live), live, change_ids)
    return steps


def upgrade_form(live: Path, previous: str, *, control: Path) -> dict[str, Any]:
    """Run the N02-D upgrade procedure from ``previous`` to the checked-out candidate on the copy."""
    from owlbear_delivery.state_formats import read_controller_pin, record_tree_digest  # noqa: PLC0415
    from owlbear_tools import delivery_controller  # noqa: PLC0415

    layout = delivery_controller.Layout(live)
    candidate = subprocess.run(  # noqa: S603 - fixed Git argument vector.
        ("git", "-C", str(live), "rev-parse", "HEAD"),  # noqa: S607
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()
    change_ids = _change_ids(live)
    report: dict[str, Any] = {"form": "upgrade", "candidate": candidate, "previous": previous, "changes": change_ids}
    report["previous_controller"] = _previous_controller(live, previous, control, change_ids)
    report["candidate_release"] = _install_release(live, candidate, control)
    new = layout.release(candidate) / ".venv/bin"
    root = ("--project-root", str(live))
    report["offline_preflight"] = _cli(new / "delivery-controller", *root, "preflight")
    report["backup"] = _cli(new / "delivery-controller", *root, "backup", "--destination", "/lc-backup")
    before = record_tree_digest(live, exclude_migrations=True)
    report["migration"] = _migrate(new, live)
    after = record_tree_digest(live, exclude_migrations=True)
    report["changed_records"] = sorted(key for key in set(before) | set(after) if before.get(key) != after.get(key))
    report["switch"] = _cli(
        new / "delivery-controller", *root, "switch" if read_controller_pin(live) else "pin", candidate
    )
    command = _mcp_command(live)
    report["mcp_json_names_launcher"] = command == [str(layout.bin / "delivery-mcp")]
    report["first_start"] = mcp_session(command, live, change_ids)
    between = record_tree_digest(live)
    report["second_start"] = mcp_session(command, live, change_ids)
    report["round_trip_unchanged"] = record_tree_digest(live) == between and report["first_start"].get(
        "views"
    ) == report["second_start"].get("views")
    index = layout.release(candidate) / "serve/cockpit/dist/index.html"
    report["cockpit"] = cockpit_check(layout.bin / "cockpit", live, index)
    report["checkout_controller"] = _load_every_change(live)
    report["verify"] = _cli(new / "delivery-controller", *root, "verify")
    report["rollback"] = _cli(new / "delivery-controller", *root, "switch", previous)
    if report["rollback"]["exit"] == 0:
        report["rollback_start"] = mcp_session(command, live, change_ids)
    report["passed"] = upgrade_passed(report)
    return report


def _session_ok(session: dict[str, Any]) -> bool:
    """A controller start passes only when ``delivery_health`` is healthy and every Change is available."""
    return bool(
        session.get("started")
        and session.get("health_status") == _HEALTHY
        and not session.get("unavailable")
        and not session.get("blockers")
    )


def upgrade_passed(report: dict[str, Any]) -> bool:
    """N02-D first-upgrade and rollback rehearsal criteria (plan section 3.5)."""
    previous = report["previous_controller"]
    migration = report["migration"]
    proposed = {entry["locator"] for entry in (migration.get("proposal") or {}).get("entries", [])}
    migrated = not migration["required"] or migration["verified"]
    rollback = report["rollback"]
    previous_format = (previous.get("release") or {}).get("supported_format")
    if not previous.get("gated"):
        rollback_ok = rollback["exit"] == 1 and rollback.get("code") == "release-invalid"
    elif previous_format == report["candidate_release"].get("supported_format"):
        rollback_ok = rollback["exit"] == 0 and _session_ok(report.get("rollback_start") or {})
    else:
        # The migrated state is newer than the previous release's format: its gate must refuse (D3).
        rollback_ok = rollback["exit"] == 1 and rollback.get("code") == "release-refuses-state"
    return bool(
        _session_ok(previous.get("online") or {})
        and report["candidate_release"].get("installed")
        and report["offline_preflight"]["exit"] == 0
        and not report["offline_preflight"].get("blockers")
        and report["backup"]["exit"] == 0
        and migrated
        and set(report["changed_records"]) == proposed
        and report["switch"]["exit"] == 0
        and report["mcp_json_names_launcher"]
        and _session_ok(report["first_start"])
        and _session_ok(report["second_start"])
        and report["round_trip_unchanged"]
        and report["cockpit"]["work_items_status"] == _HTTP_OK
        and report["cockpit"]["index_matches_release"]
        and report["checkout_controller"].get("code") == "controller-not-pinned"
        and report["verify"]["exit"] == 0
        and rollback_ok
    )


# ---------------------------------------------------------------------------
# Command line
# ---------------------------------------------------------------------------


def _primary_worktree() -> Path:
    completed = subprocess.run(
        ("git", "rev-parse", "--path-format=absolute", "--git-common-dir"),  # noqa: S607
        check=True,
        capture_output=True,
        text=True,
    )
    return Path(completed.stdout.strip()).parent


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="delivery-lc", description=__doc__.splitlines()[0])
    commands = parser.add_subparsers(dest="command", required=True)
    prepare_parser = commands.add_parser("prepare")
    prepare_parser.add_argument("--stage", type=Path, required=True)
    prepare_parser.add_argument("--live", type=Path, default=None)
    run_parser = commands.add_parser("run")
    run_parser.add_argument("--stage", type=Path, required=True)
    run_parser.add_argument("--live", type=Path, default=None)
    run_parser.add_argument("--candidate", required=True)
    run_parser.add_argument("--form", choices=_FORMS, required=True)
    run_parser.add_argument("--previous", default="")
    run_parser.add_argument("--image", default=DEFAULT_IMAGE)
    run_parser.add_argument("--uv-cache-volume", default=None)
    run_parser.add_argument("--ca-bundle", type=Path, default=None)
    run_parser.add_argument("--bundles", type=Path, default=None, help="prebuilt Cockpit bundles <commit>/index.html")
    run_parser.add_argument("--dry-run", action="store_true")
    compare_parser = commands.add_parser("compare")
    compare_parser.add_argument("--stage", type=Path, required=True)
    compare_parser.add_argument("--live", type=Path, default=None)
    proof_parser = commands.add_parser("prove-isolation")
    proof_parser.add_argument("--live", type=Path, required=True)
    proof_parser.add_argument("--stage-source", required=True)
    proof_parser.add_argument("--launch", type=Path, required=True)
    proof_parser.add_argument("--report", type=Path, required=True)
    inside_parser = commands.add_parser("inside")
    inside_parser.add_argument("--live", type=Path, required=True)
    inside_parser.add_argument("--form", choices=_FORMS, required=True)
    inside_parser.add_argument("--previous", default="")
    inside_parser.add_argument("--report", type=Path, required=True)
    load_parser = commands.add_parser("load-changes")
    load_parser.add_argument("--live", type=Path, required=True)
    return parser


def _run_command(args: argparse.Namespace, live: Path) -> tuple[int, dict[str, object]]:
    if args.form in {"full", "upgrade"} and not args.previous:
        return 2, {"error": f"the {args.form} form needs --previous (the merged predecessor or pinned release)"}
    if args.form == "upgrade" and args.bundles is None:
        return 2, {"error": "the upgrade form needs --bundles with the candidate's (and a gated previous) bundle"}
    try:
        result: dict[str, Any] = run(
            args.stage,
            live.resolve(),
            args.candidate,
            args.form,
            args.previous,
            image=args.image,
            uv_cache_volume=args.uv_cache_volume,
            ca_bundle=args.ca_bundle,
            bundles=args.bundles,
            dry_run=args.dry_run,
        )
    except ValueError as exc:
        return 2, {"error": str(exc)}
    passed = args.dry_run or (result["exit"] == 0 and result["report"].get("passed") is True)
    return (0 if passed else 1), result


def _execute(args: argparse.Namespace) -> tuple[int, dict[str, object]]:
    live = getattr(args, "live", None) or _primary_worktree()
    if args.command == "prepare":
        return 0, prepare(live, args.stage)
    if args.command == "compare":
        result = compare(live, args.stage)
        return (0 if result["live_unchanged"] else 1), result
    if args.command == "run":
        return _run_command(args, live)
    if args.command == "load-changes":
        result = _load_every_change(live)
        return (0 if result.get("loaded") else 1), result
    if args.command == "prove-isolation":
        result = prove_isolation(live, args.stage_source, args.launch)
    elif args.form == "upgrade":
        result = upgrade_form(live, args.previous, control=Path(CONTROL_MOUNT))
    else:
        result = full_form(live, args.previous) if args.form == "full" else load_form(live)
    args.report.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return (0 if result.get("isolated", result.get("passed")) else 1), result


def main(argv: list[str] | None = None) -> int:
    """Console entry point: print one JSON object; non-zero when the gate fails."""
    code, payload = _execute(_parser().parse_args(argv))
    with contextlib.suppress(BrokenPipeError):
        sys.stdout.write(json.dumps(payload, indent=2, sort_keys=True) + "\n")
    return code


if __name__ == "__main__":  # pragma: no cover - container entry point for the isolation proof.
    raise SystemExit(main())
