"""``delivery-lc``: live-compatibility gate on an isolated copy of live Delivery state.

``prepare`` copies the live checkout's ``.git`` and ``.owlbear/delivery`` into a stage and hashes the
live records. ``run`` starts a container whose only bind mount at (or under) the live absolute path
is the stage copy, proves that isolation, then runs the candidate's inspector, gate and load or full form
against the copy. ``compare`` proves the live records unchanged. Record and receipt bytes, including absolute
main-checkout paths, are never rewritten: inside the container those paths resolve into the copy.

The module is stdlib-only at import, so the container can run its isolation proof before any
candidate dependency is synced; the load and full forms import Delivery lazily.
"""

from __future__ import annotations

import argparse
import contextlib
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tarfile
import tempfile
from collections import Counter
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from collections.abc import Callable

COPY_MARKER = ".lc-copy-marker"
CONTROL_MOUNT = "/lc"
CA_BUNDLE = "ca-bundle.crt"
DEFAULT_IMAGE = "ubuntu:24.04"
_FORMAT_MARKER = "runtime/format.json"
_RECORD_ROOTS = ("config.json", "runtime", "packages")
_COPY_EXCLUDES = (".venv", "node_modules", "dist", "__pycache__", ".pytest_cache", ".ruff_cache", ".mypy_cache")
_PREVIOUS_GATE = "serve/delivery/src/owlbear_delivery/state_formats.py"
_GATE_PROBE = """
import importlib.machinery, importlib.util, json, sys
from pathlib import Path
loader = importlib.machinery.SourceFileLoader("previous_state_formats", sys.argv[1])
spec = importlib.util.spec_from_loader(loader.name, loader)
module = importlib.util.module_from_spec(spec)
sys.modules[loader.name] = module
loader.exec_module(module)
report = module.scan_capability(Path(sys.argv[2]))
print(json.dumps({"supported_format": module.SUPPORTED_FORMAT,
                  "refusals": [[item.code, item.locator] for item in report.refusals]}))
"""
_INSIDE = """#!/bin/sh
# Container side, generated by delivery-lc run. The stage copy is mounted at the live path.
set -eu
LIVE="$1"; CANDIDATE="$2"; FORM="$3"; PREVIOUS="$4"
apt-get update -qq >/dev/null && apt-get install -y -qq git curl ca-certificates >/dev/null
# Trust the system store (plus an optional extra CA from --ca-bundle) for curl, uv and Python TLS.
if [ -f /lc/ca-bundle.crt ]; then cat /lc/ca-bundle.crt >> /etc/ssl/certs/ca-certificates.crt; fi
export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt UV_NATIVE_TLS=1
curl -LsSf https://astral.sh/uv/install.sh | sh >/dev/null 2>&1
export PATH="$HOME/.local/bin:$PATH"
git config --global --add safe.directory '*'
git config --global user.email lc@example.invalid && git config --global user.name lc
uv run --no-project --python 3.14 python /lc/delivery_lc.py prove-isolation --live "$LIVE" \\
  --stage-source "$(cat /lc/stage-source)" --report /lc/isolation.json
ORIGIN_URL="$(git -C "$LIVE" remote get-url origin)"
git init -q --bare /remote.git
git -C "$LIVE" push -q /remote.git 'refs/remotes/origin/*:refs/heads/*'
git -C "$LIVE" config "url./remote.git.insteadOf" "$ORIGIN_URL"
git -C "$LIVE" checkout -q -f --detach "$CANDIDATE"
cd "$LIVE"
uv sync --locked --quiet
PYTHONDONTWRITEBYTECODE=1 uv run --no-sync delivery-lc inside --live "$LIVE" --form "$FORM" \\
  --previous "$PREVIOUS" --report /lc/report.json
"""


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def record_hashes(live: Path) -> dict[str, str]:
    """Hash live Delivery records (config, runtime, packages) without following links or worktrees."""
    delivery = live / ".owlbear/delivery"
    hashes: dict[str, str] = {}
    for name in _RECORD_ROOTS:
        root = delivery / name
        paths = [root] if root.is_file() else sorted(path for path in root.rglob("*") if path.is_file())
        for path in paths:
            locator = path.relative_to(delivery).as_posix()
            hashes[locator] = f"symlink:{path.readlink()}" if path.is_symlink() else _sha256(path)
    return hashes


def _copy_tree(source: Path, destination: Path) -> None:
    shutil.copytree(source, destination, symlinks=True, ignore=shutil.ignore_patterns(*_COPY_EXCLUDES))


def prepare(live: Path, stage: Path) -> dict[str, object]:
    """Copy live Git and Delivery state into ``stage/root`` and record live hashes in ``stage/control``."""
    live = live.resolve()
    if stage.exists():
        msg = f"stage already exists: {stage}"
        raise FileExistsError(msg)
    root, control = stage / "root", stage / "control"
    (root / ".owlbear").mkdir(parents=True)
    control.mkdir()
    _copy_tree(live / ".git", root / ".git")
    _copy_tree(live / ".owlbear/delivery", root / ".owlbear/delivery")
    stamp = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    (root / COPY_MARKER).write_text(f"copy-of-{live} {stamp}\n", encoding="utf-8")
    hashes = record_hashes(live)
    (control / "live-before.json").write_text(json.dumps(hashes, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    (control / "stage-source").write_text(f"{root.resolve()}\n", encoding="utf-8")
    return {"live": str(live), "stage": str(stage.resolve()), "records": len(hashes)}


def compare(live: Path, stage: Path) -> dict[str, object]:
    """Return whether every live record still has its prepared hash."""
    before = json.loads((stage / "control/live-before.json").read_text(encoding="utf-8"))
    after = record_hashes(live.resolve())
    changed = sorted(locator for locator in set(before) | set(after) if before.get(locator) != after.get(locator))
    return {"live_unchanged": not changed, "changed": changed, "records": len(after)}


@dataclass(frozen=True, slots=True)
class Mount:
    """One ``/proc/self/mountinfo`` row: source ``root``, ``mount_point``, filesystem type and mount source."""

    root: str
    mount_point: str
    fstype: str = ""
    source: str = ""


# Kernel pseudo filesystems: their ``root`` is never a host directory; accepted only under the kernel trees.
_KERNEL_FILESYSTEMS = frozenset(
    {
        "autofs",
        "binfmt_misc",
        "bpf",
        "cgroup",
        "cgroup2",
        "configfs",
        "debugfs",
        "devpts",
        "devtmpfs",
        "efivarfs",
        "fusectl",
        "hugetlbfs",
        "mqueue",
        "nsfs",
        "proc",
        "pstore",
        "securityfs",
        "sysfs",
        "tracefs",
    }
)
_KERNEL_TREES = ("/proc", "/sys", "/dev")
# A bind mount keeps its source filesystem type and a bound tmpfs directory can show ``root`` ``/``, so
# neither proves a fresh instance. Overlay is exempt only as the container root; tmpfs only once each at
# the points the runtime creates itself (runc ``/dev``, ``/dev/shm`` and Docker's masked directories)
# with an anonymous source. Any other tmpfs, under ``/run`` or elsewhere, is inspected like a bind.
_ROOT_FILESYSTEMS = frozenset({"overlay", "fuse.fuse-overlayfs"})
_RUNTIME_TMPFS_POINTS = frozenset(
    {
        "/dev",
        "/dev/shm",  # noqa: S108 - a mount point compared, never a file opened.
        "/proc/acpi",
        "/proc/asound",
        "/proc/scsi",
        "/sys/firmware",
        "/sys/devices/virtual/powercap",
    }
)
_RUNTIME_TMPFS_SOURCES = frozenset({"tmpfs", "shm", "none"})
# Docker Desktop shares a host directory as ``/run/host_mark/<top>``; ``root`` is then relative to it.
_HOST_SHARE = "/run/host_mark"
_HOST_ALIASES = ("/host_mnt", "/private")


def _unescape(field: str) -> str:
    return re.sub(r"\\([0-7]{3})", lambda match: chr(int(match.group(1), 8)), field)


def parse_mountinfo(text: str) -> list[Mount]:
    """Parse mountinfo rows into root, mount point, filesystem type and mount source."""
    mounts = []
    for line in text.splitlines():
        fields = line.split()
        if len(fields) < 5:  # noqa: PLR2004 - mountinfo: id, parent, device, root, mount point.
            continue
        tail = fields[fields.index("-", 5) + 1 :] if "-" in fields[5:] else []
        fstype, source = [*tail, "", ""][:2]
        mounts.append(Mount(_unescape(fields[3]), _unescape(fields[4]), fstype, _unescape(source)))
    return mounts


def _within(path: str, root: str) -> bool:
    return path == root or path.startswith(root.rstrip("/") + "/")


def _without_aliases(path: str) -> str:
    for alias in _HOST_ALIASES:
        if _within(path, alias):
            path = path.removeprefix(alias) or "/"
    return path


def _host_path(mount: Mount) -> str:
    """Return the host directory a mount exposes, joining a Docker Desktop share and removing host aliases."""
    path = mount.root
    if mount.source.startswith(f"{_HOST_SHARE}/"):
        share = mount.source.removeprefix(_HOST_SHARE).rstrip("/")
        path = share if mount.root == "/" else f"{share}{mount.root}"
    return _without_aliases(path)


def _container_mount(mount: Mount, *, stacked: bool) -> bool:
    """Return whether a mount is positively the container root or a runtime-created pseudo mount."""
    if mount.mount_point == "/":
        return mount.fstype in _ROOT_FILESYSTEMS
    if mount.fstype in _KERNEL_FILESYSTEMS:
        return any(_within(mount.mount_point, tree) for tree in _KERNEL_TREES)
    return (
        mount.fstype == "tmpfs"
        and not stacked
        and mount.root == "/"
        and mount.mount_point in _RUNTIME_TMPFS_POINTS
        and mount.source in _RUNTIME_TMPFS_SOURCES
    )


def _exposes_checkout(mount: Mount, live: str, *, stacked: bool) -> bool:
    """Return whether a mount may expose the real checkout or one of its ancestors, at any mount point.

    ``root`` is relative to its own filesystem, whose host mount point is unknown, so any mount whose
    host path is a trailing component sequence of the checkout or an ancestor fails closed.
    """
    if _container_mount(mount, stacked=stacked):
        return False
    exposed = Path(_host_path(mount)).parts[1:]
    checkout = Path(_without_aliases(live)).parts[1:]
    return any(checkout[:end][end - len(exposed) :] == exposed for end in range(len(exposed), len(checkout) + 1))


def _source_matches(root: str, stage_source: str) -> bool:
    candidates = {stage_source, stage_source.removeprefix("/private")}
    return any(root == source or root.endswith(source) for source in candidates)


def isolation_failures(
    mounts: list[Mount],
    *,
    live: str,
    stage_source: str,
    marker_present: bool,
    common_dirs: dict[str, str],
) -> list[str]:
    """Return why the container is not isolated (D9); an empty list proves isolation."""
    failures = []
    at_live = [mount for mount in mounts if _within(mount.mount_point, live)]
    if len(at_live) != 1 or at_live[0].mount_point != live:
        failures.append(f"expected exactly one mount at the live path, found {len(at_live)}")
    elif not _source_matches(_host_path(at_live[0]), stage_source):
        failures.append("the mount at the live path is not the stage copy")
    top = "/" + live.strip("/").split("/", 1)[0]
    outside = [mount for mount in mounts if _within(mount.mount_point, top) and not _within(mount.mount_point, live)]
    if outside:
        failures.append(f"unexpected mounts under {top}: {[mount.mount_point for mount in outside]}")
    points = Counter(mount.mount_point for mount in mounts)
    failures.extend(
        f"the real checkout or an ancestor of it is mounted at {mount.mount_point}"
        for mount in mounts
        if _exposes_checkout(mount, live, stacked=points[mount.mount_point] > 1)
    )
    if not marker_present:
        failures.append("the copy marker is absent at the live path")
    expected = f"{live.rstrip('/')}/.git"
    failures.extend(
        f"{name} resolves Git outside the copy: {resolved}"
        for name, resolved in common_dirs.items()
        if resolved != expected
    )
    return failures


def _git_common_dir(path: Path) -> str:
    completed = subprocess.run(  # noqa: S603 - fixed Git argument vector inside the isolated container.
        ("git", "-C", str(path), "rev-parse", "--path-format=absolute", "--git-common-dir"),  # noqa: S607
        check=False,
        capture_output=True,
        text=True,
    )
    return completed.stdout.strip() if completed.returncode == 0 else f"<git failed: {completed.returncode}>"


def prove_isolation(live: Path, stage_source: str) -> dict[str, object]:
    """Inside the container: prove the stage is the only mount at the live path before any load."""
    worktrees = live / ".owlbear/delivery/worktrees"
    common_dirs = {"copy": _git_common_dir(live)}
    if worktrees.is_dir():
        common_dirs.update({child.name: _git_common_dir(child) for child in sorted(worktrees.iterdir())})
    failures = isolation_failures(
        parse_mountinfo(Path("/proc/self/mountinfo").read_text(encoding="utf-8")),
        live=str(live),
        stage_source=stage_source,
        marker_present=(live / COPY_MARKER).is_file(),
        common_dirs=common_dirs,
    )
    return {"isolated": not failures, "failures": failures, "common_dirs": common_dirs}


def docker_command(  # noqa: PLR0913 - one container invocation binds each isolation input explicitly.
    stage: Path,
    live: Path,
    candidate: str,
    form: str,
    previous: str,
    *,
    image: str = DEFAULT_IMAGE,
    uv_cache_volume: str | None = None,
) -> list[str]:
    """Return the container command: the stage copy at the live path and control files at ``/lc`` only."""
    command = ["docker", "run", "--rm", "-v", f"{(stage / 'root').resolve()}:{live}"]
    command += ["-v", f"{(stage / 'control').resolve()}:{CONTROL_MOUNT}"]
    if uv_cache_volume:
        command += ["-v", f"{uv_cache_volume}:/root/.cache/uv"]
    return [*command, image, "sh", f"{CONTROL_MOUNT}/inside.sh", str(live), candidate, form, previous]


def run(  # noqa: PLR0913 - mirrors docker_command.
    stage: Path,
    live: Path,
    candidate: str,
    form: str,
    previous: str,
    *,
    image: str = DEFAULT_IMAGE,
    uv_cache_volume: str | None = None,
    ca_bundle: Path | None = None,
    dry_run: bool = False,
) -> dict[str, object]:
    """Write the container script and run the candidate's LC form against the stage copy.

    ``ca_bundle`` (PEM) is appended to the container trust store, for networks that intercept TLS.
    """
    control = stage / "control"
    (control / "inside.sh").write_text(_INSIDE, encoding="utf-8")
    shutil.copyfile(__file__, control / "delivery_lc.py")
    if ca_bundle is not None:
        shutil.copyfile(ca_bundle, control / CA_BUNDLE)
    command = docker_command(stage, live, candidate, form, previous, image=image, uv_cache_volume=uv_cache_volume)
    if dry_run:
        return {"command": command}
    with (control / "run.log").open("wb") as log:
        completed = subprocess.run(command, check=False, stdout=log, stderr=subprocess.STDOUT)  # noqa: S603
    report = control / "report.json"
    result = json.loads(report.read_text(encoding="utf-8")) if report.is_file() else {}
    return {"exit": completed.returncode, "report": result, "log": str(control / "run.log")}


# ---------------------------------------------------------------------------
# Inside the container (candidate code): load and full forms
# ---------------------------------------------------------------------------


def _read_config(path: Path) -> object:
    from owlbear_delivery.delivery_application_loader import DeliveryStartupConfig  # noqa: PLC0415

    return DeliveryStartupConfig.model_validate_json(path.read_bytes(), strict=True)


def _load_every_change(live: Path) -> dict[str, object]:
    """Normal composition (it may write); only the previous release's rollback load uses it."""
    from owlbear_delivery import close_delivery_application  # noqa: PLC0415
    from owlbear_delivery.application_models import DeliveryUnavailableChangeView  # noqa: PLC0415
    from owlbear_delivery.delivery_application_loader import (  # noqa: PLC0415
        DeliveryApplicationLoadError,
        load_configured_delivery_application,
    )

    try:
        application = load_configured_delivery_application(live, _read_config)  # type: ignore[arg-type]
    except DeliveryApplicationLoadError as exc:
        return {"loaded": False, "field": exc.field, "code": exc.code, "detail": exc.detail}
    try:
        changes = live / ".owlbear/delivery/runtime/changes"
        change_ids = sorted(path.name for path in changes.iterdir() if path.is_dir()) if changes.is_dir() else []
        unavailable = [
            change_id
            for change_id in change_ids
            if isinstance(application.get_change(change_id), DeliveryUnavailableChangeView)
        ]
        return {"loaded": True, "changes": change_ids, "unavailable": unavailable}
    finally:
        close_delivery_application(application)


def _read_only_load(live: Path) -> dict[str, object]:
    """Candidate load of every Change through the offline read-only composition."""
    from owlbear_delivery import close_delivery_application  # noqa: PLC0415
    from owlbear_delivery.application_models import DeliveryUnavailableChangeView  # noqa: PLC0415
    from owlbear_delivery.delivery_application_loader import (  # noqa: PLC0415
        DeliveryApplicationLoadError,
        load_read_only_application,
    )
    from owlbear_delivery.storage_io import ReadOnlyStateError, read_only_state  # noqa: PLC0415

    changes = live / ".owlbear/delivery/runtime/changes"
    change_ids = sorted(path.name for path in changes.iterdir() if path.is_dir()) if changes.is_dir() else []
    try:
        with read_only_state():
            application = load_read_only_application(live, _read_config)  # type: ignore[arg-type]
            try:
                unavailable = [
                    change_id
                    for change_id in change_ids
                    if isinstance(application.get_change(change_id), DeliveryUnavailableChangeView)
                ]
            finally:
                close_delivery_application(application)
    except DeliveryApplicationLoadError as exc:
        return {"loaded": False, "field": exc.field, "code": exc.code, "detail": exc.detail}
    except ReadOnlyStateError:
        return {"loaded": False, "code": "read-only-write-attempted", "detail": "the load attempted a record write"}
    return {"loaded": True, "changes": change_ids, "unavailable": unavailable}


def _changed(before: dict[str, str], after: dict[str, str]) -> list[str]:
    return sorted(locator for locator in set(before) | set(after) if before.get(locator) != after.get(locator))


def _read_phase(live: Path) -> dict[str, Any]:
    """Inspector, gate and read-only load, each bracketed by a complete record-tree comparison.

    ``records_changed`` names every record (excluding L-class locks and transients) that any of the
    three reads added, removed or rewrote; a compatibility read that changes one fails its form.
    """
    from owlbear_delivery.state_formats import record_tree_digest  # noqa: PLC0415

    phase: dict[str, Any] = {}
    changed: dict[str, list[str]] = {}
    for name, read in (("inspector", _inspect), ("gate", _gate), ("load", _read_only_load)):
        before = record_tree_digest(live)
        phase[name] = read(live)
        changed[name] = _changed(before, record_tree_digest(live))
    phase["records_changed"] = {name: locators for name, locators in changed.items() if locators}
    return phase


def _gate(live: Path) -> list[list[str]]:
    from owlbear_delivery.state_formats import scan_capability  # noqa: PLC0415

    return [[refusal.code, refusal.locator] for refusal in scan_capability(live).refusals]


def _inspect(live: Path) -> dict[str, object]:
    """Run the candidate ``delivery-diagnose inspect`` against the copy and keep its bounded summary."""
    module = (sys.executable, "-m", "owlbear_tools.delivery_diagnostics")
    completed = subprocess.run(  # noqa: S603 - fixed interpreter, module and argument vector.
        (*module, "inspect", "--project-root", str(live), "--format", "json"),
        check=False,
        capture_output=True,
        text=True,
    )
    try:
        result = json.loads(completed.stdout)
    except ValueError:
        return {"exit": completed.returncode, "status": "unavailable", "diagnostic_codes": ["INSPECTOR_OUTPUT_INVALID"]}
    return {
        "exit": completed.returncode,
        "status": result.get("status"),
        "inspection_complete": result.get("inspection_complete"),
        "diagnostic_codes": result.get("diagnostic_codes", []),
        "format": result.get("format"),
    }


_MIGRATION_DIAGNOSTIC = re.compile(r"[A-Z_]+_MIGRATION_REQUIRED")


def inspector_agrees(inspection: dict[str, Any], gate: list[list[str]], load: dict[str, Any]) -> bool:
    """Return whether the inspector's verdict matches the gate and the load (plan section 3.3).

    A loaded copy with no gate refusal must inspect as complete ``healthy-structure`` with no
    diagnostic; a copy refused only for migration must show only migration-required diagnostics,
    the format one exactly when the gate refuses the marker; any other refusal must not inspect healthy.
    """
    codes = list(inspection.get("diagnostic_codes") or [])
    if not gate:
        return bool(
            load.get("loaded")
            and not load.get("unavailable")
            and inspection.get("status") == "healthy-structure"
            and inspection.get("inspection_complete") is True
            and not codes
        )
    if all(code == "state-migration-required" for code, _locator in gate):
        format_refused = ["state-migration-required", _FORMAT_MARKER] in gate
        return bool(
            codes
            and all(_MIGRATION_DIAGNOSTIC.fullmatch(code) for code in codes)
            and ("FORMAT_MIGRATION_REQUIRED" in codes) == format_refused
        )
    return inspection.get("status") != "healthy-structure"


def _previous_gate(live: Path, previous: str, root: Path) -> dict[str, object]:
    """Run the previous release's stdlib gate from its commit against ``root`` (D3 oracle)."""
    source = subprocess.run(  # noqa: S603 - fixed Git argument vector.
        ("git", "-C", str(live), "show", f"{previous}:{_PREVIOUS_GATE}"),  # noqa: S607
        check=True,
        capture_output=True,
    ).stdout
    with tempfile.TemporaryDirectory() as directory:
        gate = Path(directory) / "state_formats.py"
        gate.write_bytes(source)
        completed = subprocess.run(  # noqa: S603 - fixed interpreter and argument vector.
            (sys.executable, "-I", "-c", _GATE_PROBE, str(gate), str(root)),
            check=True,
            capture_output=True,
            text=True,
        )
    return json.loads(completed.stdout)


def _previous_load(live: Path, previous: str) -> dict[str, object]:
    """Install the previous release from its commit and load every Change of ``live`` with it (rollback)."""
    environment = {key: value for key, value in os.environ.items() if key not in {"VIRTUAL_ENV", "PYTHONPATH"}}
    with tempfile.TemporaryDirectory() as directory:
        archive, tree = Path(directory) / "previous.tar", Path(directory) / "previous"
        subprocess.run(  # noqa: S603 - fixed Git argument vector.
            ("git", "-C", str(live), "archive", "--format=tar", "-o", str(archive), previous),  # noqa: S607
            check=True,
            capture_output=True,
        )
        with tarfile.open(archive) as handle:
            handle.extractall(tree, filter="data")
        synced = subprocess.run(
            ("uv", "sync", "--locked", "--quiet"),  # noqa: S607 - uv from PATH in the container.
            cwd=tree,
            env=environment,
            check=False,
            capture_output=True,
            text=True,
        )
        if synced.returncode != 0:
            return {"loaded": False, "code": "previous-release-unavailable", "detail": synced.stderr[-2000:]}
        completed = subprocess.run(  # noqa: S603 - the previous release's interpreter runs this module's loader.
            (str(tree / ".venv/bin/python"), "-I", __file__, "load-changes", "--live", str(live)),
            env=environment,
            check=False,
            capture_output=True,
            text=True,
        )
    try:
        return json.loads(completed.stdout)
    except ValueError:
        return {"loaded": False, "code": "previous-load-failed", "detail": completed.stderr[-2000:]}


def previous_release_oracle(report: dict[str, Any]) -> bool:
    """D3 on the migrated copy: a release supporting its format loads every Change, otherwise refuses it.

    Supported rollback needs no gate refusal and a load by that release listing the candidate's Changes,
    all available. Unsupported downgrade needs the typed newer-format refusal at ``runtime/format.json``
    and unchanged record hashes; any other refusal (for example only an incomplete journal) is not enough.
    """
    previous = report["previous_gate_after"]
    if previous["supported_format"] >= report["target_format"]:
        load = report.get("previous_load") or {}
        return bool(
            previous["refusals"] == []
            and load.get("loaded") is True
            and load.get("changes") == report["migrated"]["load"].get("changes")
            and not load.get("unavailable")
        )
    return bool(
        ["state-newer-than-controller", _FORMAT_MARKER] in previous["refusals"]
        and report.get("previous_gate_hashes_unchanged") is True
    )


def _synthetic_newer(live: Path) -> list[list[str]]:
    """Refusal of a copy whose marker names a format newer than the candidate supports."""
    from owlbear_delivery.state_formats import SUPPORTED_FORMAT, format_marker_bytes  # noqa: PLC0415

    with tempfile.TemporaryDirectory() as directory:
        copy = Path(directory)
        shutil.copytree(
            live / ".owlbear/delivery",
            copy / ".owlbear/delivery",
            symlinks=True,
            ignore=shutil.ignore_patterns("worktrees"),
        )
        (copy / ".owlbear/delivery/runtime/format.json").write_bytes(format_marker_bytes(SUPPORTED_FORMAT + 1))
        return _gate(copy)


def load_form(live: Path) -> dict[str, object]:
    """Gate report, candidate inspector and read-only application load of the unmodified copy."""
    report: dict[str, Any] = {"form": "load", **_read_phase(live)}
    load = report["load"]
    report["inspector_agrees"] = inspector_agrees(report["inspector"], report["gate"], load)
    report["passed"] = bool(
        load.get("loaded")
        and not load.get("unavailable")
        and report["inspector_agrees"]
        and not report["records_changed"]
    )
    return report


def full_form(
    live: Path,
    previous: str,
    *,
    previous_load: Callable[[Path, str], dict[str, object]] = _previous_load,
) -> dict[str, object]:
    """Load form plus typed refusal of the unmigrated copy, migration, D3 oracle and newer-format refusal."""
    from owlbear_delivery import state_migration  # noqa: PLC0415
    from owlbear_delivery.state_formats import SUPPORTED_FORMAT, record_tree_digest  # noqa: PLC0415

    report: dict[str, Any] = {"form": "full", "previous": previous, "target_format": SUPPORTED_FORMAT}
    pre = record_tree_digest(live)
    report["previous_gate_before"] = _previous_gate(live, previous, live)
    report["unmigrated"] = _read_phase(live)
    report["unmigrated_hashes_unchanged"] = record_tree_digest(live) == pre
    try:
        proposal = state_migration.propose(live)
        report["proposal"] = {
            "migration_id": proposal.migration_id,
            "entries": [entry.model_dump(mode="json") for entry in proposal.entries],
        }
        report["apply"] = state_migration.apply(live, proposal.migration_id).state
        report["verify"] = state_migration.verify(live, proposal.migration_id).state
    except state_migration.MigrationError as exc:
        report["migration_error"] = {"code": exc.code, "detail": exc.detail, "locator": exc.locator}
        report["passed"] = False
        return report
    post = record_tree_digest(live, exclude_migrations=True)
    report["changed_records"] = sorted(k for k in set(pre) | set(post) if pre.get(k) != post.get(k))
    report["migrated"] = _read_phase(live)
    migrated_hashes = record_tree_digest(live)
    report["previous_gate_after"] = _previous_gate(live, previous, live)
    report["previous_gate_hashes_unchanged"] = record_tree_digest(live) == migrated_hashes
    report["synthetic_newer"] = _synthetic_newer(live)
    if report["previous_gate_after"]["supported_format"] >= SUPPORTED_FORMAT:
        # Last: a normal load by the rollback release may write to the copy.
        report["previous_load"] = previous_load(live, previous)
    report["passed"] = _full_form_passed(report, {entry["locator"] for entry in report["proposal"]["entries"]})
    return report


def _full_form_passed(report: dict[str, Any], proposed: set[str]) -> bool:
    unmigrated, migrated = report["unmigrated"], report["migrated"]
    load = migrated["load"]
    return bool(
        unmigrated["load"].get("code", "").startswith("state-")
        and report["unmigrated_hashes_unchanged"]
        and not unmigrated["records_changed"]
        and not migrated["records_changed"]
        and inspector_agrees(unmigrated["inspector"], unmigrated["gate"], unmigrated["load"])
        and report.get("verify") == "verified"
        and set(report["changed_records"]) == proposed
        and migrated["gate"] == []
        and load.get("loaded")
        and not load.get("unavailable")
        and inspector_agrees(migrated["inspector"], migrated["gate"], load)
        and previous_release_oracle(report)
        and any(code == "state-newer-than-controller" for code, _locator in report["synthetic_newer"])
    )


# ---------------------------------------------------------------------------
# Command line
# ---------------------------------------------------------------------------


def _primary_worktree() -> Path:
    completed = subprocess.run(
        ("git", "rev-parse", "--path-format=absolute", "--git-common-dir"),  # noqa: S607
        check=True,
        capture_output=True,
        text=True,
    )
    return Path(completed.stdout.strip()).parent


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="delivery-lc", description=__doc__.splitlines()[0])
    commands = parser.add_subparsers(dest="command", required=True)
    prepare_parser = commands.add_parser("prepare")
    prepare_parser.add_argument("--stage", type=Path, required=True)
    prepare_parser.add_argument("--live", type=Path, default=None)
    run_parser = commands.add_parser("run")
    run_parser.add_argument("--stage", type=Path, required=True)
    run_parser.add_argument("--live", type=Path, default=None)
    run_parser.add_argument("--candidate", required=True)
    run_parser.add_argument("--form", choices=("load", "full"), required=True)
    run_parser.add_argument("--previous", default="")
    run_parser.add_argument("--image", default=DEFAULT_IMAGE)
    run_parser.add_argument("--uv-cache-volume", default=None)
    run_parser.add_argument("--ca-bundle", type=Path, default=None)
    run_parser.add_argument("--dry-run", action="store_true")
    compare_parser = commands.add_parser("compare")
    compare_parser.add_argument("--stage", type=Path, required=True)
    compare_parser.add_argument("--live", type=Path, default=None)
    proof_parser = commands.add_parser("prove-isolation")
    proof_parser.add_argument("--live", type=Path, required=True)
    proof_parser.add_argument("--stage-source", required=True)
    proof_parser.add_argument("--report", type=Path, required=True)
    inside_parser = commands.add_parser("inside")
    inside_parser.add_argument("--live", type=Path, required=True)
    inside_parser.add_argument("--form", choices=("load", "full"), required=True)
    inside_parser.add_argument("--previous", default="")
    inside_parser.add_argument("--report", type=Path, required=True)
    load_parser = commands.add_parser("load-changes")
    load_parser.add_argument("--live", type=Path, required=True)
    return parser


def _execute(args: argparse.Namespace) -> tuple[int, dict[str, object]]:
    live = getattr(args, "live", None) or _primary_worktree()
    if args.command == "prepare":
        return 0, prepare(live, args.stage)
    if args.command == "compare":
        result = compare(live, args.stage)
        return (0 if result["live_unchanged"] else 1), result
    if args.command == "run":
        if args.form == "full" and not args.previous:
            return 2, {"error": "the full form needs --previous (the merged predecessor phase head)"}
        result: dict[str, Any] = run(
            args.stage,
            live.resolve(),
            args.candidate,
            args.form,
            args.previous,
            image=args.image,
            uv_cache_volume=args.uv_cache_volume,
            ca_bundle=args.ca_bundle,
            dry_run=args.dry_run,
        )
        passed = args.dry_run or (result["exit"] == 0 and result["report"].get("passed") is True)
        return (0 if passed else 1), result
    if args.command == "load-changes":
        result = _load_every_change(live)
        return (0 if result.get("loaded") else 1), result
    if args.command == "prove-isolation":
        result = prove_isolation(live, args.stage_source)
    else:
        result = full_form(live, args.previous) if args.form == "full" else load_form(live)
    args.report.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return (0 if result.get("isolated", result.get("passed")) else 1), result


def main(argv: list[str] | None = None) -> int:
    """Console entry point: print one JSON object; non-zero when the gate fails."""
    code, payload = _execute(_parser().parse_args(argv))
    with contextlib.suppress(BrokenPipeError):
        sys.stdout.write(json.dumps(payload, indent=2, sort_keys=True) + "\n")
    return code


if __name__ == "__main__":  # pragma: no cover - container entry point for the isolation proof.
    raise SystemExit(main())
