"""Doc-index generator and parser for the OwlBear workspace."""

from __future__ import annotations

import argparse
import json
import os
import re
from pathlib import Path
from typing import TypedDict
from urllib.parse import urlsplit, urlunsplit

_AUTO_GENERATED_HEADER = "<!-- AUTO-GENERATED by serve/tools/doc-index. DO NOT EDIT. Regenerated on demand. -->"

_EXCLUDED_PATHS: frozenset[Path] = frozenset(
    Path(p)
    for p in [
        ".owlbear/scratch",
        ".owlbear/research",
        ".owlbear/kanban",
        ".owlbear/sources",
        ".owlbear/memory",
        ".owlbear/delivery",
        ".owlbear/legacy",
        ".owlbear/target",
        ".owlbear/worktrees",
        "seed/.github",
        "store",
        "tests",
        "megalinter-reports",
    ]
)

_EXCLUDED_NAMES: frozenset[str] = frozenset(
    {
        "node_modules",
        ".git",
        ".venv",
        ".pytest_cache",
        "dist",
        "build",
        "fixtures",
    }
)
_EXCLUDED_ROOT_READMES: frozenset[Path] = frozenset({Path("store/README.md"), Path("tests/README.md")})
_EXCLUDED_ROOTS_WITH_READMES: frozenset[Path] = frozenset({Path("store"), Path("tests")})

_DOC_SUFFIXES: frozenset[str] = frozenset({".md", ".excalidraw"})
_GENERATED_INDEX_PATHS: frozenset[Path] = frozenset(
    {Path(".owlbear/doc-index.md"), Path(".owlbear/py-index.md"), Path(".owlbear/ts-index.md")}
)

_HEADING_RE = re.compile(r"^(#{1,6})\s+(.*)")
_LINK_RE = re.compile(r"\[([^\]]*)\]\(([^)]+)\)")
_INLINE_CODE_SPAN_RE = re.compile(r"`+[^`\n]+`+")


class LinkEntry(TypedDict):
    """An outbound hyperlink extracted from a doc entry."""

    text: str
    target: str


class DocEntry(TypedDict):
    """A parsed document entry from the doc index."""

    path: str
    headings: list[str]
    outbound_links: list[LinkEntry]
    describes: list[str]


def _is_excluded_dir(dirpath: Path, root: Path) -> bool:
    """Return True if *dirpath* matches an excluded path or contains an excluded name."""
    try:
        rel = dirpath.relative_to(root)
    except ValueError:  # pragma: no cover
        return False  # pragma: no cover
    if rel in _EXCLUDED_PATHS:
        return True
    return any(part in _EXCLUDED_NAMES for part in rel.parts)


def collect_docs(root: Path) -> list[Path]:
    """Collect .md and .excalidraw files under *root*, skipping excluded dirs."""
    results: list[Path] = []
    for dirpath_str, dirnames, filenames in os.walk(root, topdown=True):
        dirpath = Path(dirpath_str)
        rel_dir = dirpath.relative_to(root)
        if rel_dir in _EXCLUDED_ROOTS_WITH_READMES:
            dirnames[:] = []
            results.extend(
                dirpath / filename for filename in sorted(filenames) if (rel_dir / filename) in _EXCLUDED_ROOT_READMES
            )
            continue
        dirnames[:] = sorted(
            d
            for d in dirnames
            if (rel_dir / d) in _EXCLUDED_ROOTS_WITH_READMES or not _is_excluded_dir(dirpath / d, root)
        )
        for filename in sorted(filenames):
            path = dirpath / filename
            if path.suffix in _DOC_SUFFIXES:
                results.append(path)
    return results


def _parse_markdown(content: str) -> tuple[list[str], list[tuple[str, str]]]:
    """Extract headings and (text, url) link pairs, skipping code blocks."""
    headings: list[str] = []
    links: list[tuple[str, str]] = []
    in_fenced = False
    fence_char = ""

    for raw_line in content.splitlines():
        stripped = raw_line.rstrip()

        if not in_fenced:
            fence_m = re.match(r"^(```+|~~~+)", stripped)
            if fence_m:
                in_fenced = True
                fence_char = fence_m.group(1)[0]
                continue
            if raw_line.startswith(("    ", "\t")):
                continue
        else:
            if re.match(rf"^{re.escape(fence_char)}{{3,}}", stripped):
                in_fenced = False
            continue

        heading_m = _HEADING_RE.match(stripped)
        if heading_m:
            level = heading_m.group(1)
            text = heading_m.group(2).strip()
            headings.append(f"{level} {text}")

        inline_code_spans = [(match.start(), match.end()) for match in _INLINE_CODE_SPAN_RE.finditer(stripped)]
        links.extend(
            (match.group(1), match.group(2))
            for match in _LINK_RE.finditer(stripped)
            if not any(start <= match.start() < end for start, end in inline_code_spans)
        )

    return headings, links


def _rebase_link_target(rel_path: Path, target: str, root: Path) -> str:
    """Rebase one source-document link so it resolves from the generated index."""
    parsed = urlsplit(target)
    if parsed.scheme or parsed.netloc or parsed.path.startswith("/"):
        return target

    source_path = root / rel_path
    target_path = source_path if not parsed.path else source_path.parent / parsed.path
    index_parent = root / ".owlbear"
    rebased_path = os.path.relpath(target_path, index_parent).replace(os.sep, "/")
    return urlunsplit(("", "", rebased_path, parsed.query, parsed.fragment))


def _read_diagram_describes(doc_path: Path) -> list[str]:
    """Read source globs from an Excalidraw document's describes metadata."""
    try:
        payload = json.loads(doc_path.read_text())
    except OSError, json.JSONDecodeError:
        return []
    describes = payload.get("describes") if isinstance(payload, dict) else None
    if isinstance(describes, str):
        return [describes]
    if not isinstance(describes, list):
        return []
    return [value for value in describes if isinstance(value, str) and value]


def _render_entry(rel_path: Path, doc_path: Path, root: Path) -> str:
    """Render a single index entry section for *doc_path*."""
    lines: list[str] = [f"## {rel_path.as_posix()}"]

    if doc_path.suffix == ".excalidraw":
        describes = _read_diagram_describes(doc_path)
        if describes:
            lines.append(f"describes: {', '.join(describes)}")
        return "\n".join(lines)

    content = doc_path.read_text()
    headings, links = _parse_markdown(content)
    for h in headings:
        parts = h.split(" ", 1)
        level_str = parts[0]
        text = parts[1] if len(parts) > 1 else ""
        lines.append(f"- {level_str} `{text}`")
    if links:
        lines.append("")
        lines.append("### Outbound links")
        for link_text, url in links:
            rebased_url = _rebase_link_target(rel_path, url, root)
            lines.append(f"- [{link_text}]({rebased_url})")

    return "\n".join(lines)


def generate_index(root: Path) -> None:
    """Write the documentation index under *root*."""
    index_path = root / ".owlbear/doc-index.md"
    resolved_index = index_path.resolve()
    docs = [
        doc
        for doc in collect_docs(root)
        if doc.resolve() != resolved_index and doc.relative_to(root) not in _GENERATED_INDEX_PATHS
    ]
    sections: list[str] = [_AUTO_GENERATED_HEADER]
    for doc in docs:
        rel = doc.relative_to(root)
        sections.append(_render_entry(rel, doc, root))
    content = "\n\n".join(sections) + "\n"
    index_path.parent.mkdir(parents=True, exist_ok=True)
    index_path.write_text(content)


def _update_entry(line: str, entry: DocEntry, *, in_outbound: bool) -> bool:
    """Process one non-header index line, mutating *entry* in place. Returns new in_outbound state."""
    if line.startswith("### Outbound links"):
        return True
    if line.startswith("### "):
        return False
    if line.startswith("describes:"):
        values = line.removeprefix("describes:").strip()
        if values:
            entry["describes"].extend(value.strip() for value in values.split(",") if value.strip())
        return in_outbound
    if in_outbound and line.startswith("- ["):
        link_m = _LINK_RE.match(line[2:])
        if link_m:
            entry["outbound_links"].append(LinkEntry(text=link_m.group(1), target=link_m.group(2)))
    elif not in_outbound and line.startswith("- "):
        bullet = line[2:].strip()
        hm = re.match(r"^(#{1,6})\s+`(.*)`$", bullet)
        if hm:
            entry["headings"].append(f"{hm.group(1)} {hm.group(2)}")
    return in_outbound


def parse_index(text: str) -> list[DocEntry]:
    """Parse a well-formed doc index and return a list of DocEntry mappings."""
    entries: list[DocEntry] = []
    current: DocEntry | None = None
    in_outbound = False

    for line in text.splitlines():
        if line.startswith("## "):
            if current is not None:
                entries.append(current)
            current = DocEntry(path=line[3:].strip(), headings=[], outbound_links=[], describes=[])
            in_outbound = False
        elif current is not None:
            in_outbound = _update_entry(line, current, in_outbound=in_outbound)

    if current is not None:
        entries.append(current)

    return entries


def main() -> None:
    """CLI entry point: regenerate the doc index for a workspace root."""
    parser = argparse.ArgumentParser(description="Generate or update the OwlBear doc index.")
    parser.add_argument("root", nargs="?", default=".", help="Workspace root directory")
    args = parser.parse_args()
    root = Path(args.root).resolve()
    generate_index(root)
