"""Doc-index generator and parser for the OwlBear workspace."""

from __future__ import annotations

import argparse
import json
import os
import re
from pathlib import Path, PurePosixPath
from typing import NotRequired, TypedDict
from urllib.parse import urlsplit, urlunsplit

_AUTO_GENERATED_HEADER = "<!-- AUTO-GENERATED by serve/tools/doc-index. DO NOT EDIT. Regenerated on demand. -->"

_EXCLUDED_PATHS: frozenset[Path] = frozenset(
    Path(p)
    for p in [
        ".owlbear/scratch",
        ".owlbear/research",
        ".owlbear/kanban",
        ".owlbear/sources",
        ".owlbear/memory",
        ".owlbear/delivery",
        ".owlbear/legacy",
        ".owlbear/target",
        ".owlbear/worktrees",
        "seed/.github",
        "store",
        "tests",
        "megalinter-reports",
    ]
)

_EXCLUDED_NAMES: frozenset[str] = frozenset(
    {
        "node_modules",
        ".git",
        ".venv",
        ".pytest_cache",
        "dist",
        "build",
        "fixtures",
    }
)
_EXCLUDED_ROOT_READMES: frozenset[Path] = frozenset({Path("store/README.md"), Path("tests/README.md")})
_EXCLUDED_ROOTS_WITH_READMES: frozenset[Path] = frozenset({Path("store"), Path("tests")})

_DOC_SUFFIXES: frozenset[str] = frozenset({".md"})
_DIAGRAM_MANIFEST_PATH = Path("share/diagrams/manifest.json")
_GENERATED_INDEX_PATHS: frozenset[Path] = frozenset(
    {Path(".owlbear/doc-index.md"), Path(".owlbear/py-index.md"), Path(".owlbear/ts-index.md")}
)

_HEADING_RE = re.compile(r"^(#{1,6})\s+(.*)")
_LINK_RE = re.compile(r"\[([^\]]*)\]\(([^)]+)\)")
_INLINE_CODE_SPAN_RE = re.compile(r"`+[^`\n]+`+")


class LinkEntry(TypedDict):
    """An outbound hyperlink extracted from a doc entry."""

    text: str
    target: str


class DocEntry(TypedDict):
    """A parsed document entry from the doc index."""

    path: str
    headings: list[str]
    outbound_links: list[LinkEntry]
    describes: list[str]
    source: NotRequired[str]


class DiagramEntry(TypedDict):
    """A manifest-backed static diagram entry."""

    source: str
    artifact: str
    describes: list[str]


class DiagramManifestError(ValueError):
    """Report an invalid diagram manifest."""

    def __init__(self, manifest_path: Path, detail: str) -> None:
        super().__init__(f"Invalid diagram manifest {manifest_path}: {detail}.")


class DiagramManifestTypeError(TypeError):
    """Report an invalid manifest field type."""

    def __init__(self, manifest_path: Path, detail: str) -> None:
        super().__init__(f"Invalid diagram manifest {manifest_path}: {detail}.")


def _is_excluded_dir(dirpath: Path, root: Path) -> bool:
    """Return True if *dirpath* matches an excluded path or contains an excluded name."""
    try:
        rel = dirpath.relative_to(root)
    except ValueError:  # pragma: no cover
        return False  # pragma: no cover
    if rel in _EXCLUDED_PATHS:
        return True
    return any(part in _EXCLUDED_NAMES for part in rel.parts)


def collect_docs(root: Path) -> list[Path]:
    """Collect Markdown files under *root*, skipping excluded dirs."""
    results: list[Path] = []
    for dirpath_str, dirnames, filenames in os.walk(root, topdown=True):
        dirpath = Path(dirpath_str)
        rel_dir = dirpath.relative_to(root)
        if rel_dir in _EXCLUDED_ROOTS_WITH_READMES:
            dirnames[:] = []
            results.extend(
                dirpath / filename for filename in sorted(filenames) if (rel_dir / filename) in _EXCLUDED_ROOT_READMES
            )
            continue
        dirnames[:] = sorted(
            d
            for d in dirnames
            if (rel_dir / d) in _EXCLUDED_ROOTS_WITH_READMES or not _is_excluded_dir(dirpath / d, root)
        )
        for filename in sorted(filenames):
            path = dirpath / filename
            if path.suffix in _DOC_SUFFIXES:
                results.append(path)
    return results


def _parse_markdown(content: str) -> tuple[list[str], list[tuple[str, str]]]:
    """Extract headings and (text, url) link pairs, skipping code blocks."""
    headings: list[str] = []
    links: list[tuple[str, str]] = []
    in_fenced = False
    fence_char = ""

    for raw_line in content.splitlines():
        stripped = raw_line.rstrip()

        if not in_fenced:
            fence_m = re.match(r"^(```+|~~~+)", stripped)
            if fence_m:
                in_fenced = True
                fence_char = fence_m.group(1)[0]
                continue
            if raw_line.startswith(("    ", "\t")):
                continue
        else:
            if re.match(rf"^{re.escape(fence_char)}{{3,}}", stripped):
                in_fenced = False
            continue

        heading_m = _HEADING_RE.match(stripped)
        if heading_m:
            level = heading_m.group(1)
            text = heading_m.group(2).strip()
            headings.append(f"{level} {text}")

        inline_code_spans = [(match.start(), match.end()) for match in _INLINE_CODE_SPAN_RE.finditer(stripped)]
        links.extend(
            (match.group(1), match.group(2))
            for match in _LINK_RE.finditer(stripped)
            if not any(start <= match.start() < end for start, end in inline_code_spans)
        )

    return headings, links


def _rebase_link_target(rel_path: Path, target: str, root: Path) -> str:
    """Rebase one source-document link so it resolves from the generated index."""
    parsed = urlsplit(target)
    if parsed.scheme or parsed.netloc or parsed.path.startswith("/"):
        return target

    source_path = root / rel_path
    target_path = source_path if not parsed.path else source_path.parent / parsed.path
    index_parent = root / ".owlbear"
    rebased_path = os.path.relpath(target_path, index_parent).replace(os.sep, "/")
    return urlunsplit(("", "", rebased_path, parsed.query, parsed.fragment))


def _manifest_path(root: Path, value: str, field: str, manifest_path: Path) -> Path:
    """Resolve one repository-local manifest path or raise a clear error."""
    relative = PurePosixPath(value)
    if relative.is_absolute() or "\\" in value or ".." in relative.parts:
        raise DiagramManifestError(manifest_path, f"{field} must be repository-relative")
    resolved_root = root.resolve()
    resolved = (root / Path(*relative.parts)).resolve()
    if resolved != resolved_root and resolved_root not in resolved.parents:
        raise DiagramManifestError(manifest_path, f"{field} escapes the repository")
    if not resolved.is_file():
        raise DiagramManifestError(manifest_path, f"{field} does not exist: {value}")
    return resolved


def _read_manifest_payload(manifest_path: Path) -> list[object]:
    """Read the manifest payload and validate its top-level shape."""
    if not manifest_path.exists():
        if manifest_path.parent.exists():
            raise DiagramManifestError(manifest_path, "manifest is missing")
        return []
    try:
        payload = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as error:
        raise DiagramManifestError(manifest_path, f"could not be read: {error}") from error
    if not isinstance(payload, dict) or payload.get("schema_version") != 1:
        raise DiagramManifestError(manifest_path, "schema_version must be 1")
    diagrams = payload.get("diagrams")
    if not isinstance(diagrams, list):
        raise DiagramManifestTypeError(manifest_path, "diagrams must be a list")
    return diagrams


def _read_diagram_entry(
    root: Path,
    manifest_path: Path,
    index: int,
    diagram: object,
    seen_paths: tuple[set[str], set[str]],
) -> DiagramEntry:
    """Validate and return one manifest diagram entry."""
    seen_sources, seen_artifacts = seen_paths
    if not isinstance(diagram, dict):
        raise DiagramManifestTypeError(manifest_path, f"entry {index} must be an object")
    source = diagram.get("source")
    artifact = diagram.get("artifact")
    describes = diagram.get("describes")
    if (
        not isinstance(source, str)
        or not source
        or not isinstance(artifact, str)
        or not artifact
        or not isinstance(describes, list)
        or not describes
        or not all(isinstance(value, str) and value for value in describes)
    ):
        raise DiagramManifestError(manifest_path, f"entry {index} has invalid fields")
    if source in seen_sources or artifact in seen_artifacts:
        raise DiagramManifestError(manifest_path, f"entry {index} duplicates a path")
    if source == artifact:
        raise DiagramManifestError(manifest_path, f"entry {index} reuses one path")
    _manifest_path(root, source, f"entry {index} source", manifest_path)
    _manifest_path(root, artifact, f"entry {index} artifact", manifest_path)
    seen_sources.add(source)
    seen_artifacts.add(artifact)
    return {"source": source, "artifact": artifact, "describes": describes}


def _read_diagram_manifest(root: Path) -> list[DiagramEntry]:
    """Read and validate static diagram metadata from the shared manifest."""
    manifest_path = root / _DIAGRAM_MANIFEST_PATH
    diagrams = _read_manifest_payload(manifest_path)
    valid: list[DiagramEntry] = []
    seen_sources: set[str] = set()
    seen_artifacts: set[str] = set()
    for index, diagram in enumerate(diagrams):
        valid.append(_read_diagram_entry(root, manifest_path, index, diagram, (seen_sources, seen_artifacts)))
    return valid


def _render_entry(rel_path: Path, doc_path: Path, root: Path) -> str:
    """Render a single index entry section for *doc_path*."""
    lines: list[str] = [f"## {rel_path.as_posix()}"]

    content = doc_path.read_text()
    headings, links = _parse_markdown(content)
    for h in headings:
        parts = h.split(" ", 1)
        level_str = parts[0]
        text = parts[1] if len(parts) > 1 else ""
        lines.append(f"- {level_str} `{text}`")
    if links:
        lines.append("")
        lines.append("### Outbound links")
        for link_text, url in links:
            rebased_url = _rebase_link_target(rel_path, url, root)
            lines.append(f"- [{link_text}]({rebased_url})")

    return "\n".join(lines)


def _render_diagram_entry(diagram: dict[str, object]) -> str:
    """Render one manifest-backed static diagram entry."""
    source = diagram.get("source")
    artifact = diagram.get("artifact")
    describes = diagram.get("describes")
    if not isinstance(source, str) or not isinstance(artifact, str):
        return ""
    if not isinstance(describes, list) or not all(isinstance(value, str) for value in describes):
        return ""
    return "\n".join(
        [
            f"## {artifact}",
            f"source: {source}",
            f"describes: {', '.join(describes)}",
        ]
    )


def generate_index(root: Path) -> None:
    """Write the documentation index under *root*."""
    index_path = root / ".owlbear/doc-index.md"
    resolved_index = index_path.resolve()
    docs = [
        doc
        for doc in collect_docs(root)
        if doc.resolve() != resolved_index and doc.relative_to(root) not in _GENERATED_INDEX_PATHS
    ]
    sections: list[str] = [_AUTO_GENERATED_HEADER]
    for doc in docs:
        rel = doc.relative_to(root)
        sections.append(_render_entry(rel, doc, root))
    sections.extend(_render_diagram_entry(diagram) for diagram in _read_diagram_manifest(root))
    content = "\n\n".join(sections) + "\n"
    index_path.parent.mkdir(parents=True, exist_ok=True)
    index_path.write_text(content)


def _update_entry(line: str, entry: DocEntry, *, in_outbound: bool) -> bool:  # noqa: C901
    """Process one non-header index line, mutating *entry* in place. Returns new in_outbound state."""
    if line.startswith("### Outbound links"):
        return True
    if line.startswith("### "):
        return False
    if line.startswith("describes:"):
        values = line.removeprefix("describes:").strip()
        if values:
            entry["describes"].extend(value.strip() for value in values.split(",") if value.strip())
        return in_outbound
    if line.startswith("source:"):
        source = line.removeprefix("source:").strip()
        if source:
            entry["source"] = source
        return in_outbound
    if in_outbound and line.startswith("- ["):
        link_m = _LINK_RE.match(line[2:])
        if link_m:
            entry["outbound_links"].append(LinkEntry(text=link_m.group(1), target=link_m.group(2)))
    elif not in_outbound and line.startswith("- "):
        bullet = line[2:].strip()
        hm = re.match(r"^(#{1,6})\s+`(.*)`$", bullet)
        if hm:
            entry["headings"].append(f"{hm.group(1)} {hm.group(2)}")
    return in_outbound


def parse_index(text: str) -> list[DocEntry]:
    """Parse a well-formed doc index and return a list of DocEntry mappings."""
    entries: list[DocEntry] = []
    current: DocEntry | None = None
    in_outbound = False

    for line in text.splitlines():
        if line.startswith("## "):
            if current is not None:
                entries.append(current)
            current = DocEntry(path=line[3:].strip(), headings=[], outbound_links=[], describes=[])
            in_outbound = False
        elif current is not None:
            in_outbound = _update_entry(line, current, in_outbound=in_outbound)

    if current is not None:
        entries.append(current)

    return entries


def main() -> None:
    """CLI entry point: regenerate the doc index for a workspace root."""
    parser = argparse.ArgumentParser(description="Generate or update the OwlBear doc index.")
    parser.add_argument("root", nargs="?", default=".", help="Workspace root directory")
    args = parser.parse_args()
    root = Path(args.root).resolve()
    generate_index(root)
