"""Generate a structural index of Python source files."""

from __future__ import annotations

import argparse
import ast
from pathlib import Path

from owlbear_tools.source_index import collect_sources

_SUFFIXES = frozenset({".py"})
_HEADER = "<!-- AUTO-GENERATED by serve/tools/py-index. ADVISORY ONLY; SOURCE IS AUTHORITATIVE. -->"


def _annotation(node: ast.expr | None) -> str:
    return ast.unparse(node) if node is not None else ""


def _argument(argument: ast.arg, default: ast.expr | None = None, *, prefix: str = "") -> str:
    text = f"{prefix}{argument.arg}"
    if argument.annotation is not None:
        text += f": {_annotation(argument.annotation)}"
    if default is not None:
        text += f" = {ast.unparse(default)}"
    return text


def _arguments(arguments: ast.arguments) -> str:
    """Render a compact function argument list without evaluating source."""
    positional = [*arguments.posonlyargs, *arguments.args]
    default_offset = len(positional) - len(arguments.defaults)
    parts: list[str] = []
    for index, argument in enumerate(positional):
        default = arguments.defaults[index - default_offset] if index >= default_offset else None
        parts.append(_argument(argument, default))
        if arguments.posonlyargs and index + 1 == len(arguments.posonlyargs):
            parts.append("/")
    if arguments.vararg is not None:
        parts.append(_argument(arguments.vararg, prefix="*"))
    elif arguments.kwonlyargs:
        parts.append("*")
    for argument, default in zip(arguments.kwonlyargs, arguments.kw_defaults, strict=True):
        parts.append(_argument(argument, default))
    if arguments.kwarg is not None:
        parts.append(_argument(arguments.kwarg, prefix="**"))
    return ", ".join(parts)


def _function_signature(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    prefix = "async def" if isinstance(node, ast.AsyncFunctionDef) else "def"
    result = f"{prefix} {node.name}({_arguments(node.args)})"
    if node.returns is not None:
        result += f" -> {_annotation(node.returns)}"
    return result


def _imports(tree: ast.Module) -> list[str]:
    imports: set[str] = set()
    for node in tree.body:
        if isinstance(node, ast.Import):
            imports.update(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom):
            imports.add("." * node.level + (node.module or ""))
    return sorted(imports)


def _render_module(path: Path, root: Path) -> str:
    tree = ast.parse(path.read_text(), filename=str(path))
    lines = [f"## {path.relative_to(root).as_posix()}"]
    docstring = ast.get_docstring(tree, clean=True)
    if docstring:
        lines.extend(["", docstring.splitlines()[0]])
    imports = _imports(tree)
    if imports:
        lines.extend(["", "### Imports", *[f"- `{name}`" for name in imports]])
    interfaces: list[str] = []
    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            bases = ", ".join(ast.unparse(base) for base in node.bases)
            interfaces.append(f"- `class {node.name}{f'({bases})' if bases else ''}`")
            interfaces.extend(
                f"  - `{_function_signature(child)}`"
                for child in node.body
                if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef))
            )
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            interfaces.append(f"- `{_function_signature(node)}`")
    if interfaces:
        lines.extend(["", "### Interfaces", *interfaces])
    return "\n".join(lines)


def generate_index(root: Path) -> None:
    """Write the Python source index under *root*."""
    index_path = root / ".owlbear/py-index.md"
    sources = collect_sources(root, _SUFFIXES)
    sections = [_HEADER, *[_render_module(path, root) for path in sources]]
    index_path.parent.mkdir(parents=True, exist_ok=True)
    index_path.write_text("\n\n".join(sections) + "\n")


def main() -> None:
    """Regenerate the Python source index."""
    parser = argparse.ArgumentParser(description="Generate OwlBear's advisory Python source index.")
    parser.add_argument("root", nargs="?", default=".", help="Workspace root directory")
    arguments = parser.parse_args()
    root = Path(arguments.root).resolve()
    generate_index(root)
