"""Generate a structural index of TypeScript and JavaScript source files."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import TYPE_CHECKING

from tree_sitter_language_pack import get_parser

from owlbear_tools.source_index import clean_line, collect_sources

if TYPE_CHECKING:
    from tree_sitter import Node

_SUFFIXES = frozenset({".ts", ".tsx", ".js", ".jsx"})
_HEADER = "<!-- AUTO-GENERATED by serve/tools/ts-index. ADVISORY ONLY; SOURCE IS AUTHORITATIVE. -->"
_DECLARATIONS = {
    "class_declaration",
    "function_declaration",
    "generator_function_declaration",
    "interface_declaration",
    "type_alias_declaration",
    "enum_declaration",
    "lexical_declaration",
    "variable_declaration",
}
_MEMBERS = {"method_definition", "method_signature", "public_field_definition"}


def _language(path: Path) -> str:
    return {".ts": "typescript", ".tsx": "tsx", ".js": "javascript", ".jsx": "tsx"}[path.suffix]


def _text(node: Node, source: bytes) -> str:
    return source[node.start_byte : node.end_byte].decode()


def _prefix_through(node: Node, source: bytes, stop_types: set[str]) -> str:
    stop = next((child for child in node.children if child.type in stop_types), None)
    end_byte = stop.start_byte if stop is not None else node.end_byte
    return clean_line(source[node.start_byte : end_byte].decode())


def _declaration(node: Node, source: bytes) -> str:
    if node.type in {"class_declaration", "function_declaration", "generator_function_declaration"}:
        return _prefix_through(node, source, {"class_body", "statement_block"})
    if node.type == "interface_declaration":
        return _prefix_through(node, source, {"interface_body", "object_type"})
    if node.type == "enum_declaration":
        return _prefix_through(node, source, {"enum_body"})
    if node.type in {"lexical_declaration", "variable_declaration"}:
        declarator = next((child for child in node.named_children if child.type == "variable_declarator"), None)
        if declarator is None:
            return clean_line(_text(node, source))
        value = declarator.child_by_field_name("value")
        end_byte = value.start_byte if value is not None else declarator.end_byte
        return clean_line(source[node.start_byte : end_byte].decode().rstrip("= "))
    return clean_line(_text(node, source))


def _unwrap_export(node: Node) -> tuple[Node, str]:
    declaration = node.child_by_field_name("declaration")
    if declaration is None:
        declaration = next((child for child in node.named_children if child.type in _DECLARATIONS), node)
    prefix = "export default " if any(child.type == "default" for child in node.children) else "export "
    return declaration, prefix


def _members(node: Node, source: bytes) -> list[str]:
    body = next((child for child in node.named_children if child.type in {"class_body", "interface_body"}), None)
    if body is None:
        return []
    return [
        _prefix_through(child, source, {"statement_block"}) for child in body.named_children if child.type in _MEMBERS
    ]


def _render_module(path: Path, root: Path) -> str:
    source = path.read_bytes()
    tree = get_parser(_language(path)).parse(source)
    lines = [f"## {path.relative_to(root).as_posix()}"]
    if tree.root_node.has_error:
        lines.extend(["", "Parse status: error; inspect source directly."])
    imports = [
        clean_line(_text(node, source))
        for node in tree.root_node.named_children
        if node.type in {"import_statement", "export_statement"} and node.child_by_field_name("source") is not None
    ]
    if imports:
        lines.extend(["", "### Imports", *[f"- `{item}`" for item in imports]])
    interfaces: list[str] = []
    for node in tree.root_node.named_children:
        prefix = ""
        declaration = node
        if node.type == "export_statement" and node.child_by_field_name("source") is None:
            declaration, prefix = _unwrap_export(node)
            if declaration is node:
                interfaces.append(f"- `{clean_line(_text(node, source))}`")
                continue
        if declaration.type not in _DECLARATIONS:
            continue
        interfaces.append(f"- `{prefix}{_declaration(declaration, source)}`")
        interfaces.extend(f"  - `{member}`" for member in _members(declaration, source))
    if interfaces:
        lines.extend(["", "### Interfaces", *interfaces])
    return "\n".join(lines)


def generate_index(root: Path) -> None:
    """Write the TypeScript and JavaScript source index under *root*."""
    index_path = root / ".owlbear/ts-index.md"
    sources = collect_sources(root, _SUFFIXES)
    sections = [_HEADER, *[_render_module(path, root) for path in sources]]
    index_path.parent.mkdir(parents=True, exist_ok=True)
    index_path.write_text("\n\n".join(sections) + "\n")


def main() -> None:
    """Regenerate the TypeScript and JavaScript source index."""
    parser = argparse.ArgumentParser(description="Generate OwlBear's advisory ECMAScript source index.")
    parser.add_argument("root", nargs="?", default=".", help="Workspace root directory")
    arguments = parser.parse_args()
    root = Path(arguments.root).resolve()
    generate_index(root)
