"""OwlBear kanban engine package.

Exports the transport-free kanban engine, its public models, error
classes.
"""

from __future__ import annotations

from owlbear_kanban.admission import (
    AdmissionAssessment,
    AdmissionDisposition,
    AdmissionEvidence,
    AdmissionFinding,
    AdmissionSeverity,
    evaluate_admission,
)
from owlbear_kanban.admission_transaction import (
    AdmissionConflictError,
    AdmissionPublicationError,
    AdmissionTransaction,
    AdmissionValidationError,
    validate_and_admit,
)
from owlbear_kanban.agent_view import AgentView
from owlbear_kanban.attempts import (
    AttemptEvent,
    AttemptEventDiagnostic,
    AttemptEventDiagnosticCode,
    AttemptEventParseResult,
    parse_attempt_event_mapping,
)
from owlbear_kanban.change import (
    ChangeDiagnostic,
    ChangeDiagnosticCode,
    ChangeLoadResult,
    ChangeRevision,
    DecisionsDocument,
    DeliveryGraph,
    compute_delivery_digest,
    load_change,
)
from owlbear_kanban.engine import KanbanEngine, WorkSession
from owlbear_kanban.errors import (
    ConcurrencyError,
    CorruptionError,
    NotFoundError,
    ValidationError,
)
from owlbear_kanban.finding import (
    Finding,
    FindingConflictError,
    FindingDiagnostic,
    FindingDiagnosticCode,
    FindingResult,
    FindingStore,
    parse_finding_mapping,
)
from owlbear_kanban.jobs import (
    JobConcurrencyError,
    JobConflictError,
    JobDiagnostic,
    JobDiagnosticCode,
    JobGeneration,
    JobParseResult,
    JobProjection,
    JobRecord,
    JobStore,
    ShapeJob,
    StoredJob,
    parse_job_mapping,
    plan_shape_jobs,
    project_job,
    read_job_generation,
)
from owlbear_kanban.models import BoardConfig, Task, TaskSummary
from owlbear_kanban.receipt import (
    ChangeHealthFinding,
    ChangeHealthResult,
    ReceiptConflictError,
    ReceiptDiagnostic,
    ReceiptDiagnosticCode,
    ReceiptParseDiagnostic,
    ReceiptParseDiagnosticCode,
    ReceiptParseResult,
    ReceiptRecord,
    ReceiptResult,
    ReceiptStore,
    ReceiptValidity,
    ReceiptValidityCode,
    change_health,
    evaluate_receipt_currentness,
    parse_receipt_mapping,
)
from owlbear_kanban.storage_io import atomic_write

__all__ = [
    "AdmissionAssessment",
    "AdmissionConflictError",
    "AdmissionDisposition",
    "AdmissionEvidence",
    "AdmissionFinding",
    "AdmissionPublicationError",
    "AdmissionSeverity",
    "AdmissionTransaction",
    "AdmissionValidationError",
    "AgentView",
    "AttemptEvent",
    "AttemptEventDiagnostic",
    "AttemptEventDiagnosticCode",
    "AttemptEventParseResult",
    "BoardConfig",
    "ChangeDiagnostic",
    "ChangeDiagnosticCode",
    "ChangeHealthFinding",
    "ChangeHealthResult",
    "ChangeLoadResult",
    "ChangeRevision",
    "ConcurrencyError",
    "CorruptionError",
    "DecisionsDocument",
    "DeliveryGraph",
    "Finding",
    "FindingConflictError",
    "FindingDiagnostic",
    "FindingDiagnosticCode",
    "FindingResult",
    "FindingStore",
    "JobConcurrencyError",
    "JobConflictError",
    "JobDiagnostic",
    "JobDiagnosticCode",
    "JobGeneration",
    "JobParseResult",
    "JobProjection",
    "JobRecord",
    "JobStore",
    "KanbanEngine",
    "NotFoundError",
    "ReceiptConflictError",
    "ReceiptDiagnostic",
    "ReceiptDiagnosticCode",
    "ReceiptParseDiagnostic",
    "ReceiptParseDiagnosticCode",
    "ReceiptParseResult",
    "ReceiptRecord",
    "ReceiptResult",
    "ReceiptStore",
    "ReceiptValidity",
    "ReceiptValidityCode",
    "ShapeJob",
    "StoredJob",
    "Task",
    "TaskSummary",
    "ValidationError",
    "WorkSession",
    "atomic_write",
    "change_health",
    "compute_delivery_digest",
    "evaluate_admission",
    "evaluate_receipt_currentness",
    "load_change",
    "parse_attempt_event_mapping",
    "parse_finding_mapping",
    "parse_job_mapping",
    "parse_receipt_mapping",
    "plan_shape_jobs",
    "project_job",
    "read_job_generation",
    "validate_and_admit",
]
