"""Replay-safe authored Design packages and semantic Git checkpoints."""

from __future__ import annotations

import hashlib
import json
import os
import re
import subprocess
from pathlib import Path
from typing import TYPE_CHECKING, Literal

from pydantic import BaseModel, ConfigDict, ValidationError

from owlbear_kanban.identities import ChangeId, Digest
from owlbear_kanban.runtime_transaction import (
    ReplacementTransactionParticipant,
    RuntimeTransaction,
    TransactionConflictError,
    TransactionParticipant,
)
from owlbear_kanban.storage_io import locked_roots

if TYPE_CHECKING:
    from collections.abc import Callable

_GIT_EXECUTABLE = "/usr/bin/git"
_MANIFEST_NAME = "manifest.json"
_PACKAGE_NAMES = ("authority.json", "design.md", "intent.md", _MANIFEST_NAME)
_SAFE_CHANGE_ID = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
_ZERO_OID = "0" * 40


class DesignPackageConflictError(RuntimeError):
    """An existing Design package differs from its claimed immutable bytes."""

    code = "ERR_DESIGN_PACKAGE_CONFLICT"


class _PackageModel(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True, strict=True)


class DesignPackageManifest(_PackageModel):
    """Canonical hashes binding one active Design package."""

    schema_version: Literal[1] = 1
    change_id: ChangeId
    authority_sha256: Digest
    design_sha256: Digest
    intent_sha256: Digest

    @classmethod
    def from_content(
        cls,
        change_id: str,
        intent_bytes: bytes,
        design_bytes: bytes,
        authority_bytes: bytes = b"",
    ) -> DesignPackageManifest:
        """Bind the package identity to exact caller-owned and generated bytes."""
        _validate_change_id(change_id)
        return cls(
            change_id=change_id,
            authority_sha256=_digest(authority_bytes),
            design_sha256=_digest(design_bytes),
            intent_sha256=_digest(intent_bytes),
        )

    def canonical_bytes(self) -> bytes:
        """Return the canonical persisted representation."""
        payload = self.model_dump(mode="json")
        return f"{json.dumps(payload, sort_keys=True, separators=(',', ':'))}\n".encode()


class DesignPackageResult(_PackageModel):
    """Identity and location of one created or replayed active package."""

    change_id: ChangeId
    package_id: Digest
    package_root: Path
    manifest: DesignPackageManifest
    replayed: bool


class VerifiedDesignPackage(_PackageModel):
    """Exact verified bytes and identity of one active Design package."""

    change_id: ChangeId
    package_id: Digest
    intent_bytes: bytes
    design_bytes: bytes
    authority_bytes: bytes
    manifest: DesignPackageManifest


class DesignCheckpointResult(_PackageModel):
    """One package-history checkpoint selected by its dedicated ref."""

    change_id: ChangeId
    package_id: Digest
    commit: str
    replayed: bool


class DesignPackageStore:
    """Own active authored packages and their isolated semantic history."""

    def __init__(
        self,
        active_root: Path,
        repository: Path,
        *,
        failure: Callable[[str], None] | None = None,
    ) -> None:
        self._active_root = active_root.resolve()
        self._repository = repository.resolve()
        self._failure = failure

    def create(self, change_id: str, intent_bytes: bytes, design_bytes: bytes) -> DesignPackageResult:
        """Create or replay one exact active Design package."""
        _validate_change_id(change_id)
        RuntimeTransaction.recover_all(self._active_root)
        manifest = DesignPackageManifest.from_content(change_id, intent_bytes, design_bytes)
        manifest_bytes = manifest.canonical_bytes()
        package_id = _digest(manifest_bytes)
        content = {
            "authority.json": b"",
            "design.md": design_bytes,
            "intent.md": intent_bytes,
            _MANIFEST_NAME: manifest_bytes,
        }
        with locked_roots((self._active_root,)):
            existing = self._existing_content(change_id)
            if existing is not None:
                if existing != content:
                    message = f"Design package differs: {change_id}"
                    raise DesignPackageConflictError(message)
                self._verify_package(change_id)
                return self._result(change_id, manifest, package_id, replayed=True)

        relative_root = Path(change_id)
        participants = tuple(
            TransactionParticipant(self._active_root, relative_root / name, content[name]) for name in _PACKAGE_NAMES
        )
        transaction = RuntimeTransaction(
            self._active_root,
            f"design-package-{change_id}-{package_id}",
            participants,
        )
        try:
            transaction.commit(failure=self._failure)
        except Exception as exc:
            transaction.abort()
            if isinstance(exc, TransactionConflictError):
                message = f"Design package differs: {change_id}"
                raise DesignPackageConflictError(message) from exc
            raise
        return self._result(change_id, manifest, package_id, replayed=False)

    def read_verified(self, change_id: str) -> VerifiedDesignPackage:
        """Return exact package bytes after validating their manifest binding."""
        _validate_change_id(change_id)
        RuntimeTransaction.recover_all(self._active_root)
        with locked_roots((self._active_root,)):
            manifest, content = self._verify_package(change_id)
            return VerifiedDesignPackage(
                change_id=change_id,
                package_id=_digest(manifest.canonical_bytes()),
                intent_bytes=content["intent.md"],
                design_bytes=content["design.md"],
                authority_bytes=content["authority.json"],
                manifest=manifest,
            )

    def publish_contract(
        self,
        change_id: str,
        expected_package_id: str,
        contract_bytes: bytes,
        validation_callback: Callable[[bytes, bytes, bytes], None],
    ) -> VerifiedDesignPackage:
        """Atomically bind validated generated authority to unchanged authored bytes."""
        package = self.read_verified(change_id)
        if package.package_id != expected_package_id:
            message = f"Design package changed before contract publication: {change_id}"
            raise DesignPackageConflictError(message)
        manifest = DesignPackageManifest.from_content(
            change_id,
            package.intent_bytes,
            package.design_bytes,
            contract_bytes,
        )
        relative_root = Path(change_id)
        participants = (
            ReplacementTransactionParticipant(
                self._active_root,
                relative_root / "intent.md",
                package.intent_bytes,
                package.intent_bytes,
            ),
            ReplacementTransactionParticipant(
                self._active_root,
                relative_root / "design.md",
                package.design_bytes,
                package.design_bytes,
            ),
            ReplacementTransactionParticipant(
                self._active_root,
                relative_root / "authority.json",
                package.authority_bytes,
                contract_bytes,
            ),
            ReplacementTransactionParticipant(
                self._active_root,
                relative_root / _MANIFEST_NAME,
                package.manifest.canonical_bytes(),
                manifest.canonical_bytes(),
            ),
        )
        transaction = RuntimeTransaction(
            self._active_root,
            f"design-contract-{change_id}-{expected_package_id}-{_digest(contract_bytes)}",
            participants,
        )

        def validate(stage: str) -> None:
            if stage == "before-publication":
                validation_callback(package.intent_bytes, package.design_bytes, contract_bytes)

        try:
            transaction.commit(failure=validate)
        except Exception:
            transaction.abort()
            raise
        return VerifiedDesignPackage(
            change_id=change_id,
            package_id=_digest(manifest.canonical_bytes()),
            intent_bytes=package.intent_bytes,
            design_bytes=package.design_bytes,
            authority_bytes=contract_bytes,
            manifest=manifest,
        )

    def checkpoint(self, change_id: str) -> DesignCheckpointResult:
        """Checkpoint verified package bytes without touching product Git state."""
        _validate_change_id(change_id)
        RuntimeTransaction.recover_all(self._active_root)
        with locked_roots((self._active_root,)):
            manifest, content = self._verify_package(change_id)
            package_id = _digest(manifest.canonical_bytes())
            tree = self._write_tree(content)
            reference = f"refs/owlbear/packages/{change_id}"
            current = self._resolve_reference(reference)
            if current is not None and self._git("rev-parse", f"{current}^{{tree}}") == tree:
                return DesignCheckpointResult(
                    change_id=change_id,
                    package_id=package_id,
                    commit=current,
                    replayed=True,
                )
            commit = self._write_commit(change_id, package_id, tree, current)
            try:
                self._git("update-ref", reference, commit, current or _ZERO_OID)
            except subprocess.CalledProcessError as exc:
                message = f"package checkpoint changed concurrently: {change_id}"
                raise DesignPackageConflictError(message) from exc
            return DesignCheckpointResult(
                change_id=change_id,
                package_id=package_id,
                commit=commit,
                replayed=False,
            )

    def _existing_content(self, change_id: str) -> dict[str, bytes] | None:
        package_root = self._active_root / change_id
        if package_root.is_symlink():
            message = f"Design package path is unsafe: {change_id}"
            raise DesignPackageConflictError(message)
        if package_root.exists() and (
            not package_root.is_dir() or {path.name for path in package_root.iterdir()} != set(_PACKAGE_NAMES)
        ):
            message = f"Design package entries differ: {change_id}"
            raise DesignPackageConflictError(message)
        paths = tuple(package_root / name for name in _PACKAGE_NAMES)
        existing = tuple(path.exists() for path in paths)
        if not any(existing):
            return None
        if not all(existing):
            message = f"Design package is incomplete: {change_id}"
            raise DesignPackageConflictError(message)
        return {name: _read_contained(package_root, path) for name, path in zip(_PACKAGE_NAMES, paths, strict=True)}

    def _verify_package(self, change_id: str) -> tuple[DesignPackageManifest, dict[str, bytes]]:
        content = self._existing_content(change_id)
        if content is None:
            message = f"Design package does not exist: {change_id}"
            raise DesignPackageConflictError(message)
        try:
            manifest = DesignPackageManifest.model_validate_json(content[_MANIFEST_NAME])
        except (ValidationError, ValueError) as exc:
            message = f"Design package manifest is invalid: {change_id}"
            raise DesignPackageConflictError(message) from exc
        expected = DesignPackageManifest.from_content(
            change_id,
            content["intent.md"],
            content["design.md"],
            content["authority.json"],
        )
        if manifest != expected or content[_MANIFEST_NAME] != manifest.canonical_bytes():
            message = f"Design package bytes do not match its manifest: {change_id}"
            raise DesignPackageConflictError(message)
        return manifest, content

    def _write_tree(self, content: dict[str, bytes]) -> str:
        entries = []
        for name in _PACKAGE_NAMES:
            object_id = self._git("hash-object", "-w", "--stdin", input_bytes=content[name])
            entries.append(f"100644 blob {object_id}\t{name}\n")
        return self._git("mktree", input_bytes="".join(entries).encode())

    def _write_commit(
        self,
        change_id: str,
        package_id: str,
        tree: str,
        parent: str | None,
    ) -> str:
        arguments = ["commit-tree", tree]
        if parent is not None:
            arguments.extend(("-p", parent))
        arguments.extend(("-m", f"Checkpoint Design package {change_id} ({package_id})"))
        environment = os.environ.copy()
        environment.update(
            {
                "GIT_AUTHOR_NAME": "OwlBear",
                "GIT_AUTHOR_EMAIL": "owlbear@localhost",
                "GIT_COMMITTER_NAME": "OwlBear",
                "GIT_COMMITTER_EMAIL": "owlbear@localhost",
            }
        )
        return self._git(*arguments, environment=environment)

    def _resolve_reference(self, reference: str) -> str | None:
        object_id = self._git("for-each-ref", "--format=%(objectname)", reference)
        return object_id or None

    def _git(
        self,
        *arguments: str,
        input_bytes: bytes | None = None,
        environment: dict[str, str] | None = None,
    ) -> str:
        return _stdout(self._run_git(*arguments, input_bytes=input_bytes, environment=environment))

    def _run_git(
        self,
        *arguments: str,
        input_bytes: bytes | None = None,
        environment: dict[str, str] | None = None,
        check: bool = True,
    ) -> subprocess.CompletedProcess[bytes]:
        return subprocess.run(  # noqa: S603 - fixed Git executable and argument-vector invocation.
            (_GIT_EXECUTABLE, "-C", str(self._repository), *arguments),
            check=check,
            capture_output=True,
            input=input_bytes,
            env=environment,
        )

    def _result(
        self,
        change_id: str,
        manifest: DesignPackageManifest,
        package_id: str,
        *,
        replayed: bool,
    ) -> DesignPackageResult:
        return DesignPackageResult(
            change_id=change_id,
            package_id=package_id,
            package_root=self._active_root / change_id,
            manifest=manifest,
            replayed=replayed,
        )


def _validate_change_id(change_id: str) -> None:
    if not _SAFE_CHANGE_ID.fullmatch(change_id):
        msg = "change identity must contain lowercase alphanumeric words separated by hyphens"
        raise ValueError(msg)


def _digest(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def _read_contained(package_root: Path, path: Path) -> bytes:
    resolved_root = package_root.resolve()
    resolved_path = path.resolve()
    if path.is_symlink() or resolved_root not in resolved_path.parents:
        message = f"Design package path is unsafe: {path.name}"
        raise DesignPackageConflictError(message)
    try:
        return path.read_bytes()
    except OSError as exc:
        message = f"Design package path is unreadable: {path.name}"
        raise DesignPackageConflictError(message) from exc


def _stdout(result: subprocess.CompletedProcess[bytes]) -> str:
    return result.stdout.decode().strip()
